import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { apiFetch } from '@/lib/api-client';
import type { GeneratedTasteProfile, OnboardingLifeContext } from '@/types';
import {
  BECAUSE_YOU_CARDS,
  WEEKLY_COLLECTION,
  STRETCH_PICK,
  SUMMER_RECS,
  SIGNAL_THREAD,
  TASTE_TENSION,
  MOOD_BOARDS,
  DEEP_MATCH,
  type BecauseYouCard,
  type CollectionPlace,
  type ContextRec,
  type EditorialLetter,
  type SignalThread,
  type TasteTension,
  type MoodBoard,
  type DeepMatch,
} from '@/constants/discover';

// ─── Discover cache TTL (2 hours) ─────────────────────────────────────────────
const DISCOVER_CACHE_TTL_MS = 2 * 60 * 60 * 1000;

// Discover content generated by Claude AI
export interface DiscoverContent {
  editorialLetter?: EditorialLetter;
  becauseYouCards?: BecauseYouCard[];
  signalThread?: SignalThread;
  tasteTension?: TasteTension;
  weeklyCollection?: { title: string; subtitle: string; places: CollectionPlace[] };
  moodBoards?: MoodBoard[];
  deepMatch?: DeepMatch;
  stretchPick?: typeof STRETCH_PICK;
  contextRecs?: ContextRec[];
  contextLabel?: string;
}

/**
 * Collect all place names from the initial feed + any extra pages so the
 * continuation API can avoid recommending duplicates.
 */
function collectAllPlaceNames(
  initial: DiscoverContent | null,
  extras: DiscoverContent[],
): string[] {
  const names = new Set<string>();
  function addFrom(content: DiscoverContent | null) {
    if (!content) return;
    for (const c of content.becauseYouCards || []) if (c.place) names.add(c.place);
    for (const p of content.signalThread?.places || []) if (p.name) names.add(p.name);
    if (content.tasteTension?.resolvedBy?.name) names.add(content.tasteTension.resolvedBy.name);
    for (const p of content.weeklyCollection?.places || []) if (p.name) names.add(p.name);
    for (const b of content.moodBoards || []) {
      for (const p of b.places || []) if (p.name) names.add(p.name);
    }
    if (content.deepMatch?.name) names.add(content.deepMatch.name);
    if (content.stretchPick?.name) names.add(content.stretchPick.name);
    for (const r of content.contextRecs || []) if (r.name) names.add(r.name);
  }
  addFrom(initial);
  for (const page of extras) addFrom(page);
  return Array.from(names);
}

interface UseDiscoverFeedReturn {
  discoverContent: DiscoverContent | null;
  isLoadingDiscover: boolean;
  extraPages: DiscoverContent[];
  isLoadingMore: boolean;
  hasMoreContent: boolean;
  sentinelRef: React.RefObject<HTMLDivElement | null>;
  fetchDiscoverContent: () => Promise<void>;
}

export function useDiscoverFeed(
  generatedProfile: GeneratedTasteProfile | null,
  lifeContext: OnboardingLifeContext | null,
  profile: GeneratedTasteProfile | null,
): UseDiscoverFeedReturn {
  const [discoverContent, setDiscoverContent] = useState<DiscoverContent | null>(null);
  const [isLoadingDiscover, setIsLoadingDiscover] = useState(false);

  // Infinite scroll: extra feed pages loaded on demand
  const [extraPages, setExtraPages] = useState<DiscoverContent[]>([]);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const [feedPageIndex, setFeedPageIndex] = useState(1);
  const [hasMoreContent, setHasMoreContent] = useState(true);
  const sentinelRef = useRef<HTMLDivElement | null>(null);

  // Fire-and-forget: ensure hardcoded fallback places have enrichment triggered
  const triggerHardcodedEnrichment = useCallback(() => {
    // Collect all unique places from hardcoded constants
    const seen = new Set<string>();
    const places: Array<{ googlePlaceId?: string; name: string; location: string }> = [];

    function add(name?: string, location?: string, googlePlaceId?: string) {
      if (!name) return;
      const key = googlePlaceId || `${name}||${location || ''}`;
      if (seen.has(key)) return;
      seen.add(key);
      places.push({ googlePlaceId, name, location: location || '' });
    }

    for (const c of BECAUSE_YOU_CARDS) add(c.place, c.location, c.googlePlaceId);
    for (const p of SIGNAL_THREAD.places) add(p.name, p.location, p.googlePlaceId);
    add(TASTE_TENSION.resolvedBy.name, TASTE_TENSION.resolvedBy.location, TASTE_TENSION.resolvedBy.googlePlaceId);
    for (const p of WEEKLY_COLLECTION.places) add(p.name, p.location, p.googlePlaceId);
    for (const b of MOOD_BOARDS) {
      for (const p of b.places) add(p.name, p.location, p.googlePlaceId);
    }
    add(DEEP_MATCH.name, DEEP_MATCH.location, DEEP_MATCH.googlePlaceId);
    add(STRETCH_PICK.name, STRETCH_PICK.location, STRETCH_PICK.googlePlaceId);
    for (const r of SUMMER_RECS) add(r.name, r.location, r.googlePlaceId);
    if (places.length > 0) {
      apiFetch('/api/profile/discover/ensure-places', {
        method: 'POST',
        body: JSON.stringify({ places }),
      }).catch((err: unknown) => console.warn('[profile] fire-and-forget failed:', err));
    }
  }, []);

  // Generate discover content from real profile
  const fetchDiscoverContent = useCallback(async () => {
    if (!generatedProfile) return;

    // Check localStorage cache (with 2-hour TTL)
    const cacheKey = `terrazzo_discover_${generatedProfile.overallArchetype}`;
    try {
      const cached = localStorage.getItem(cacheKey);
      if (cached) {
        const parsed = JSON.parse(cached);
        const cachedAt = parsed._cachedAt as number | undefined;
        if (cachedAt && (Date.now() - cachedAt) < DISCOVER_CACHE_TTL_MS) {
          setDiscoverContent(parsed);
          return;
        }
        // Stale cache — remove and refetch
        localStorage.removeItem(cacheKey);
      }
    } catch { /* ignore cache errors */ }

    setIsLoadingDiscover(true);
    try {
      const data = await apiFetch<DiscoverContent>('/api/profile/discover', {
        method: 'POST',
        body: JSON.stringify({
          userProfile: generatedProfile,
          lifeContext: lifeContext || undefined,
        }),
      });
      setDiscoverContent(data);
      // Store with timestamp for TTL
      try {
        const toCache = { ...data, _cachedAt: Date.now() };
        localStorage.setItem(cacheKey, JSON.stringify(toCache));
      } catch { /* quota exceeded */ }
    } catch {
      // Silently fall back to hardcoded content — trigger enrichment for hardcoded places
      triggerHardcodedEnrichment();
    } finally {
      setIsLoadingDiscover(false);
    }
  }, [generatedProfile, lifeContext, triggerHardcodedEnrichment]);

  useEffect(() => {
    fetchDiscoverContent();
  }, [fetchDiscoverContent]);

  // ─── Infinite scroll: fetch additional feed pages on demand ───

  // Reset when base content changes (e.g. profile resynthesis)
  useEffect(() => {
    setExtraPages([]);
    setFeedPageIndex(1);
    setHasMoreContent(true);
  }, [discoverContent]);

  const fetchMoreContent = useCallback(async () => {
    // Need either a real profile or at least existing discover content to continue from
    const userProfile = generatedProfile || (discoverContent ? profile : null);
    if (!userProfile || isLoadingMore || !hasMoreContent) return;

    setIsLoadingMore(true);
    try {
      const data = await apiFetch<DiscoverContent>('/api/profile/discover/more', {
        method: 'POST',
        body: JSON.stringify({
          userProfile,
          lifeContext: lifeContext || undefined,
          pageIndex: feedPageIndex,
          excludePlaces: collectAllPlaceNames(discoverContent, extraPages),
        }),
      });
      setExtraPages(prev => [...prev, data]);
      setFeedPageIndex(prev => prev + 1);
      if (feedPageIndex >= 15) setHasMoreContent(false);
    } catch {
      setHasMoreContent(false);
    } finally {
      setIsLoadingMore(false);
    }
  }, [generatedProfile, profile, discoverContent, lifeContext, isLoadingMore, hasMoreContent, feedPageIndex, extraPages]);

  // IntersectionObserver triggers fetchMoreContent when user scrolls near feed bottom
  useEffect(() => {
    const sentinel = sentinelRef.current;
    if (!sentinel) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) {
          fetchMoreContent();
        }
      },
      { rootMargin: '600px' }
    );

    observer.observe(sentinel);
    return () => observer.disconnect();
  }, [fetchMoreContent]);

  return {
    discoverContent,
    isLoadingDiscover,
    extraPages,
    isLoadingMore,
    hasMoreContent,
    sentinelRef,
    fetchDiscoverContent,
  };
}
