import type { OnboardingPhase, SceneQuestion, ImagePairQuestion } from '@/types';
import { EXPERIENCE_POOL } from './experience-pool';
import { DESIGNER_POOL } from './designer-pool';

// ─── Phase Definitions (v4 — 3-Act Structure) ───
// Act 1: Quick Read (~3 min) — fast structured signal, no LLM
// Act 2: Your Story (~5 min) — behavioral anchoring + voice + personal download
// Act 3: Deep Taste (~6 min) — structured depth + adaptive gap-fill

export const ONBOARDING_PHASES: OnboardingPhase[] = [
  // ═══════════════════════════════════════
  // ACT 1 — "Quick Read" (fast structured capture)
  // ═══════════════════════════════════════
  {
    id: 'quick-bio',
    phaseNumber: 0,
    title: 'A Few Basics',
    subtitle: "We'll keep it quick — just the essentials",
    modality: 'form',
    act: 1,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 0, Atmosphere: 0, Character: 0, Service: 0, FoodDrink: 0, Geography: 0, Wellness: 0, Sustainability: 0 },
  },
  {
    id: 'email-connect',
    phaseNumber: 1,
    title: 'One Quick Thing',
    subtitle: 'This helps us ask about places you know',
    modality: 'email-connect',
    act: 1,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 0, Atmosphere: 0, Character: 0, Service: 0, FoodDrink: 0, Geography: 0, Wellness: 0, Sustainability: 0 },
  },
  {
    id: 'instinct-round',
    phaseNumber: 2,
    title: 'Quick Instincts',
    subtitle: "Don't overthink it — go with your gut",
    modality: 'cards',
    act: 1,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 20, Atmosphere: 25, Character: 18, Service: 12, FoodDrink: 22, Setting: 28, Wellness: 20, Sustainability: 0 },
    experiencePool: EXPERIENCE_POOL,
  },
  {
    id: 'visual-taste',
    phaseNumber: 3,
    title: 'Design Eye',
    subtitle: 'Pick the space that draws you in',
    modality: 'visual',
    act: 1,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 55, Atmosphere: 35, Character: 25, Service: 18, FoodDrink: 12, Setting: 35, Wellness: 12, Sustainability: 0 },
    designerPool: DESIGNER_POOL,
  },
  // {
  //   id: 'property-reactions-0',
  //   phaseNumber: 3,
  //   title: 'First Impressions',
  //   subtitle: 'Real hotels — react honestly',
  //   modality: 'property-reactions',
  //   act: 1,
  //   ... TODO(deferred): re-enable once email parsing surfaces real places
  // },

  // ═══════════════════════════════════════
  // ACT 2 — "Your Story" (voice + structured + behavioral anchoring)
  // ═══════════════════════════════════════
  {
    id: 'behavioral-anchoring',
    phaseNumber: 4,
    title: 'Your Last Trip',
    subtitle: 'Not the dream one — the one that actually happened',
    modality: 'scene',
    act: 2,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 68, Atmosphere: 55, Character: 50, Service: 40, FoodDrink: 35, Setting: 52, Wellness: 28, Sustainability: 8 },
    sceneQuestions: [
      {
        id: 'ba1-morning',
        prompt: 'Your last trip. What did you actually do first thing most mornings?',
        domains: ['Wellness', 'Atmosphere'],
        isValidator: true,
        options: [
          { id: 'workout', label: 'Worked out — gym, run, swim, yoga', signals: ['Active-morning-actual'], domain: 'Wellness' },
          { id: 'cafe', label: 'Walked to a café nearby', signals: ['Local-café-actual', 'Neighborhood-explorer-actual'], domain: 'Atmosphere' },
          { id: 'room-service', label: 'Room service or hotel breakfast, no rush', signals: ['In-hotel-morning-actual', 'Comfort-paced'], domain: 'Service' },
          { id: 'slept-in', label: 'Slept in — I was on vacation', signals: ['Sleep-in-actual', 'Recovery-focused'], domain: 'Wellness' },
        ],
      },
      {
        id: 'ba4-discovery',
        prompt: 'How did you actually find the last hotel you booked?',
        domains: ['Core'],
        options: [
          { id: 'friend', label: 'A friend or someone I trust recommended it', signals: ['Word-of-mouth-booker', 'Trust-network'], domain: 'Core' },
          { id: 'social', label: 'I saw it on Instagram or a blog', signals: ['Social-media-discovery', 'Visual-first-booker'], domain: 'Core' },
          { id: 'search', label: 'I searched on a booking site and filtered', signals: ['Booking-site-filter', 'Data-driven-booker'], domain: 'Core' },
          { id: 'editorial', label: 'I read an article or list about the destination', signals: ['Editorial-influenced', 'Research-driven-booker'], domain: 'Core' },
        ],
      },
      {
        id: 'ba5-splurge',
        prompt: 'What did you end up spending the most unexpected money on?',
        domains: ['Core'],
        isValidator: true,
        options: [
          { id: 'upgrade', label: 'The room upgrade — I couldn\'t resist', signals: ['Upgrade-spender-actual', 'Room-priority-actual'], domain: 'Core' },
          { id: 'food', label: 'Restaurants and drinks', signals: ['Food-spender-actual', 'Dining-priority-actual'], domain: 'FoodDrink' },
          { id: 'experience', label: 'An experience — a tour, a boat, something special', signals: ['Experience-spender-actual'], domain: 'Core' },
          { id: 'nothing', label: 'Nothing really — I stuck to the plan', signals: ['Budget-disciplined-actual', 'Plan-adherent'], domain: 'Core' },
        ],
      },
      {
        id: 'ba6-regret',
        prompt: 'One thing you\'d do differently about that trip?',
        domains: ['Core'],
        isValidator: true,
        options: [
          { id: 'longer', label: 'Stay longer', signals: ['Length-regret', 'Wants-more-time'], domain: 'Core' },
          { id: 'better-hotel', label: 'Spend more on the hotel', signals: ['Upgrade-regret', 'Under-invested-property'], domain: 'Core' },
          { id: 'less-planning', label: 'Plan less — I over-scheduled', signals: ['Over-planned-actual', 'Spontaneity-regret'], domain: 'Core' },
          { id: 'nothing', label: 'Honestly, nothing — it was great', signals: ['Satisfied-traveler', 'Good-instincts'], domain: 'Core' },
        ],
      },
      {
        id: 'ba7-companion',
        prompt: 'Who did you travel with?',
        domains: ['Core'],
        options: [
          { id: 'partner', label: 'Partner', signals: ['Partner-traveler-actual'], domain: 'Core' },
          { id: 'family', label: 'Family with kids', signals: ['Family-traveler-actual'], domain: 'Core' },
          { id: 'friends', label: 'Friends', signals: ['Friends-traveler-actual'], domain: 'Core' },
          { id: 'solo', label: 'Solo', signals: ['Solo-traveler-actual'], domain: 'Core' },
        ],
      },
    ],
  },
  {
    id: 'service-style',
    phaseNumber: 5,
    title: 'How You Like to Be Taken Care Of',
    subtitle: 'Service that fits, not service that performs',
    modality: 'slider',
    act: 2,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [
      { tag: 'Service philosophy', cat: 'Service', confidence: 0.88 },
      { tag: 'Formality preference', cat: 'Service', confidence: 0.85 },
    ],
    certaintyAfter: { Design: 67, Atmosphere: 52, Character: 48, Service: 70, FoodDrink: 27, Setting: 50, Wellness: 22, Sustainability: 5 },
    sliderDefs: [
      {
        id: 'visibility',
        leftLabel: 'Invisible — I only see staff when I need them',
        rightLabel: 'Present — I want warmth and check-ins',
        leftSignals: ['Invisible-service', 'Privacy-first', 'Self-sufficient-traveler'],
        rightSignals: ['Proactive-service', 'Warmth-seeking', 'Relationship-with-staff'],
        domain: 'Service',
      },
      {
        id: 'formality',
        leftLabel: 'Formal — white gloves, last names',
        rightLabel: 'Casual — first names, no fuss',
        leftSignals: ['Formal-service', 'Traditional-hospitality', 'Protocol-appreciator'],
        rightSignals: ['Casual-service', 'First-name-basis', 'Anti-formality'],
        domain: 'Service',
      },
      {
        id: 'anticipation',
        leftLabel: 'Anticipatory — they know before I ask',
        rightLabel: "On-demand — I'll ask when I need it",
        leftSignals: ['Anticipatory-service', 'Detail-remembered', 'Preference-tracking'],
        rightSignals: ['On-demand-service', 'Autonomy-first', 'Low-touch-preferred'],
        domain: 'Service',
      },
      {
        id: 'programming',
        leftLabel: 'Minimal — just the room and the setting',
        rightLabel: 'Curated — tastings, tours, experiences',
        leftSignals: ['Minimal-programming', 'Self-directed-stay', 'Space-over-activity'],
        rightSignals: ['Programming-rich', 'Curated-experiences', 'Hotel-as-guide'],
        domain: 'Service',
      },
    ],
  },
  {
    id: 'sustainability-check',
    phaseNumber: 6,
    title: 'Values & Impact',
    subtitle: 'One question — how much this matters to you',
    modality: 'scale',
    act: 2,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [
      { tag: 'Sustainability sensitivity', cat: 'Sustainability', confidence: 0.85 },
    ],
    certaintyAfter: { Design: 67, Atmosphere: 52, Character: 48, Service: 70, FoodDrink: 27, Setting: 50, Wellness: 22, Sustainability: 30 },
  },
  {
    id: 'memorable-stays',
    phaseNumber: 7,
    title: 'Memorable Stays',
    subtitle: 'Places that stuck with you — the open canvas',
    modality: 'voice',
    act: 2,
    aiPrompt: "Let's start with the good stuff. Tell me about two or three hotel stays that really stuck with you — places you still think about, even years later. What made them special?",
    followUps: [
      "TOPIC: Dig into the specifics of one place they mentioned — what made it special. Pick ONE by name and ask what it was about THAT place specifically. Was it the space, the people, a particular moment? Adapt to whatever they said.",
      "TOPIC: Explore what they gravitate toward across those stays — do they notice a thread? Is it always the design, or the food, or how the staff made them feel? Let THEM identify the pattern if there is one.",
    ],
    sampleUserResponses: [
      "There was this masseria in Puglia — Masseria Moroseta. White stone, olive groves, communal dinners outside. The owners actually ate with you. And Aman Tokyo — the opposite vibe but equally perfect. That lobby with the ikebana and the paper screens.",
      "I'd go straight to the terrace with a glass of wine and just sit there. That view of the olive groves at sunset — that's the whole thing for me.",
    ],
    extractedSignals: [
      { tag: 'Vernacular architecture', cat: 'Design', confidence: 0.92 },
      { tag: 'Communal dining', cat: 'FoodDrink', confidence: 0.94 },
      { tag: 'Staff-as-host', cat: 'Service', confidence: 0.88 },
      { tag: 'Owner-operated', cat: 'Character', confidence: 0.91 },
      { tag: 'Anti-performative', cat: 'Design', confidence: 0.85 },
      { tag: 'Natural wine', cat: 'FoodDrink', confidence: 0.78 },
      { tag: 'Intimate-under-20', cat: 'Character', confidence: 0.86 },
    ],
    certaintyAfter: { Design: 75, Atmosphere: 58, Character: 60, Service: 75, FoodDrink: 40, Setting: 55, Wellness: 25, Sustainability: 30 },
  },
  // ─── Trip Memories (voice — captures the feeling and random moments of whole trips, not specific hotels) ───
  {
    id: 'trip-memories',
    phaseNumber: 8,
    title: 'Trip Memories',
    subtitle: 'The moments that stayed with you',
    modality: 'voice',
    act: 2,
    aiPrompt: "Now zoom out from specific hotels. Think about entire trips — maybe the best trip you've ever taken, or just one that left a mark. Not the hotel, but the whole experience. What do you remember most? Could be a random moment, a meal, a walk, a feeling.",
    followUps: [
      "TOPIC: The texture of that trip — what did a day actually feel like? Were they rushing around or drifting? Eating at planned restaurants or stumbling into places? Reference the specific trip they mentioned.",
      "TOPIC: Whether they traveled alone or with others on that trip, and how the company shaped the experience. Did they want more independence or more togetherness?",
      "TOPIC: What made that trip different from others — was it the destination, the timing in their life, who they were with, or just how everything came together?",
    ],
    sampleUserResponses: [
      "Honestly my best trip was two weeks driving through Portugal with my partner. No real plan. We'd just find a town, park, walk around, eat wherever the locals were eating. Slept at these random guesthouses. One night we ended up at this family's farm and they cooked us dinner.",
      "It was so unstructured. We'd wake up and decide over coffee. Some days we'd drive three hours, some days we'd stay put. The freedom was the whole point.",
      "I think it was the timing — we'd both just quit our jobs. There was no schedule to get back to. That feeling of not having an end date changed everything.",
    ],
    extractedSignals: [
      { tag: 'Road-trip-rhythm', cat: 'Atmosphere', confidence: 0.92 },
      { tag: 'Spontaneous-unplanned', cat: 'Atmosphere', confidence: 0.94 },
      { tag: 'Local-dining-seeker', cat: 'FoodDrink', confidence: 0.90 },
      { tag: 'Slow-travel-pace', cat: 'Atmosphere', confidence: 0.88 },
      { tag: 'Authentic-local-experience', cat: 'Character', confidence: 0.91 },
      { tag: 'Partner-travel-intimacy', cat: 'Context', confidence: 0.85 },
    ],
    certaintyAfter: { Design: 76, Atmosphere: 68, Character: 65, Service: 75, FoodDrink: 48, Setting: 60, Wellness: 26, Sustainability: 30 },
  },
  {
    id: 'anti-stay',
    phaseNumber: 9,

    title: 'The Anti-Stay',
    subtitle: 'What looked perfect but felt wrong',
    modality: 'voice',
    act: 2,
    aiPrompt: "Now the opposite. Tell me about a stay that disappointed you — maybe it looked perfect online but something felt off when you got there. Or a place where one thing just ruined it. What happened?",
    followUps: [
      "TOPIC: The specific moment or detail that made it feel wrong. Reference the actual place they named and ask what tipped them off — a moment, a detail, a feeling when they walked in.",
      "TOPIC: What would have fixed it — the one change that would have saved the stay. This reveals what they value most.",
      "TOPIC: Whether that bad experience changed how they book now — do they screen for or against anything specific because of it?",
    ],
    sampleUserResponses: [
      "There was this design hotel in Lisbon — Instagrammed to death, every corner styled for photos. But it felt like a set. The staff were in these matching outfits reciting scripts.",
      "Honestly it was walking in. The lobby was beautiful but it felt cold — like nobody actually hung out there. And the room was tiny but they'd crammed in all this 'design' furniture.",
      "Yeah, now I always look for photos that feel lived-in. If every shot looks like a magazine spread I'm suspicious.",
    ],
    extractedSignals: [
      { tag: 'Anti-Instagram-aesthetic', cat: 'Rejection', confidence: 0.97 },
      { tag: 'Anti-performative', cat: 'Rejection', confidence: 0.95 },
      { tag: 'Anti-style-over-substance', cat: 'Rejection', confidence: 0.94 },
      { tag: 'Anti-cramped-design', cat: 'Rejection', confidence: 0.89 },
      { tag: 'Lived-in-aesthetic-seeker', cat: 'Preference', confidence: 0.85 },
    ],
    certaintyAfter: { Design: 82, Atmosphere: 65, Character: 68, Service: 80, FoodDrink: 48, Setting: 58, Wellness: 28, Sustainability: 30 },
  },
  {
    id: 'last-trip',
    phaseNumber: 10,
    title: 'Your Last Trip',
    subtitle: 'Not the best one — the most recent one',
    modality: 'voice',
    act: 2,
    aiPrompt: "Tell me about your most recent trip — not necessarily the best one, just the last one. Where did you stay, and walk me through what a typical day looked like.",
    followUps: [
      "TOPIC: The highlight — what was the best part of that specific trip? Reference the place or city they mentioned. What would they keep if they did it again?",
      "TOPIC: What they'd change next time — about the hotel, the neighborhood, the pace, anything. This reveals gaps between expectation and reality.",
      "TOPIC: How they found and chose that place — friend recommendation, reviews, photos, random find? What made them pull the trigger?",
    ],
    sampleUserResponses: [
      "We went to Barcelona last month. Stayed at this boutique place in El Born — small, maybe 20 rooms. We'd wake up, grab coffee at this place around the corner, then just walk for hours. Lunch wherever looked good. Back to the hotel for a nap, then out for dinner around 9.",
      "Honestly, the neighborhood. Being able to walk out the door and immediately be in it. The hotel was fine but the location made the trip.",
      "A friend had stayed there. I looked it up, the photos felt real — not too polished — and the reviews mentioned the staff by name, which I liked.",
    ],
    extractedSignals: [
      { tag: 'Boutique-scale-actual', cat: 'Preference', confidence: 0.93 },
      { tag: 'Neighborhood-walker-actual', cat: 'Behavior', confidence: 0.95 },
      { tag: 'Spontaneous-dining-actual', cat: 'Behavior', confidence: 0.90 },
      { tag: 'Afternoon-return-rhythm', cat: 'Behavior', confidence: 0.88 },
      { tag: 'Friend-referral-booker', cat: 'Behavior', confidence: 0.85 },
    ],
    certaintyAfter: { Design: 85, Atmosphere: 72, Character: 72, Service: 82, FoodDrink: 55, Setting: 62, Wellness: 35, Sustainability: 32 },
  },
  // ─── Companion Shifts (voice — how preferences change based on travel companion) ───
  {
    id: 'companion-shifts',
    phaseNumber: 11,
    title: 'How You Shift',
    subtitle: 'Same person, different traveler',
    modality: 'voice',
    act: 2,
    aiPrompt: "Here's what I'm curious about — does the kind of trip you want change depending on who you're with? Like, do you want something completely different when you're solo versus with your partner or friends?",
    followUps: [
      "TOPIC: Go deeper on one specific companion dynamic they mentioned. If they talked about their partner, ask what that looks like concretely — the pace, the kind of hotel, what they prioritize together versus alone. Use names if they've shared them.",
      "TOPIC: The solo version of them. What do they seek out when nobody else's preferences matter? Does solo travel feel like freedom or does it shift what kind of place they want?",
      "TOPIC: Whether there's a version of travel they haven't done much of but are curious about — maybe they always travel with their partner but wonder what a solo trip would feel like, or vice versa.",
    ],
    sampleUserResponses: [
      "Totally different. With my wife it's all about the room and the restaurant — we want to nest. Slower pace, longer breakfasts, a great spa. Solo or with friends, I barely use the room. It's all about the neighborhood and being out.",
      "When I'm alone I become weirdly adventurous. I'll eat at some random counter spot, walk for hours, stay at a place that's more interesting than comfortable. With my partner I want guaranteed quality — I'm not experimenting with someone else's vacation.",
      "I haven't really done a proper solo trip in years. I think I'd want something different from what I'd expect — probably something quieter, more structured. Like a retreat rather than a city trip.",
    ],
    extractedSignals: [
      { tag: 'Partner-nesting-mode', cat: 'Context', confidence: 0.92 },
      { tag: 'Solo-adventure-mode', cat: 'Context', confidence: 0.90 },
      { tag: 'Friends-neighborhood-mode', cat: 'Context', confidence: 0.88 },
      { tag: 'Companion-driven-pace-shift', cat: 'Behavior', confidence: 0.91 },
      { tag: 'Partner-comfort-priority', cat: 'Preference', confidence: 0.87 },
      { tag: 'Solo-curiosity-seeker', cat: 'Behavior', confidence: 0.85 },
      { tag: 'Room-importance-varies', cat: 'Context', confidence: 0.83 },
    ],
    certaintyAfter: { Design: 87, Atmosphere: 78, Character: 76, Service: 84, FoodDrink: 60, Setting: 68, Wellness: 38, Sustainability: 34 },
  },
  // ─── Dream Destinations (voice — captures aspirational places: cities, hotels, restaurants, countries) ───
  {
    id: 'dream-destinations',
    phaseNumber: 12,
    title: 'Dream Destinations',
    subtitle: 'The places you keep thinking about',
    modality: 'voice',
    act: 2,
    aiPrompt: "Now let's talk about places you dream about. Not where you've been — where you've always wanted to go. Could be a city, a country, a specific hotel you've bookmarked, a restaurant you've seen on someone's Instagram. What are the places that live in your head?",
    followUps: [
      "TOPIC: What specifically draws them to the places they named — pick one and dig in. Is it something they saw, read about, or just a feeling? Reference their actual words.",
      "TOPIC: If they could book one of those trips tomorrow, what would matter most — the destination itself or the kind of experience they'd have there?",
      "TOPIC: Whether there's a gap between what they dream about and what they actually book — do their real trips look different from their aspirations?",
    ],
    sampleUserResponses: [
      "Japan — Kyoto specifically. I've been saving posts about these tiny ryokans where someone curates your entire evening. And the food culture there just seems on another level.",
      "Honestly it's more a feeling. I want that sense of total immersion — where the place changes how you move through a day. Kyoto feels like that.",
      "Yeah, actually. I usually end up at nice beach resorts because they're easy to book for two. But what I really dream about is more intentional, more cultural. The gap is real.",
    ],
    extractedSignals: [
      { tag: 'Curated-experience-dreamer', cat: 'Service', confidence: 0.90 },
      { tag: 'Cultural-immersion-aspirational', cat: 'Character', confidence: 0.88 },
      { tag: 'Intentional-travel-seeker', cat: 'Atmosphere', confidence: 0.85 },
      { tag: 'Aspiration-reality-gap-aware', cat: 'Preference', confidence: 0.80 },
    ],
    certaintyAfter: { Design: 86, Atmosphere: 74, Character: 75, Service: 83, FoodDrink: 56, Setting: 68, Wellness: 36, Sustainability: 33 },
  },
  // ─── The Thing Nobody Asks (open voice — captures signals that don't fit any box) ───
  {
    id: 'nobody-asks',
    phaseNumber: 13,
    title: 'The Thing Nobody Asks',
    subtitle: 'The detail only you would notice',
    modality: 'voice',
    act: 2,
    aiPrompt: "Last thing before we shift gears — is there anything about how you travel that we haven't touched on? Could be a weird non-negotiable, a habit, a detail you always notice. Totally fine if nothing comes to mind.",
    followUps: [
      "TOPIC: When they realized this thing mattered — reference the specific detail they shared and ask if there was a trip or moment that crystallized it.",
      "TOPIC: Whether this applies universally or depends on the kind of trip — does the context change it?",
    ],
    sampleUserResponses: [
      "I need a bathtub. Not a jacuzzi, not a rain shower — a real, deep bathtub. That's my end-of-day ritual and without it the whole trip feels off.",
      "I figured it out in Japan. The onsen culture — soaking is just part of how you process the day. Now I literally filter for it when I book.",
      "Yeah — I also care about the minibar. Not whether it exists, but what's in it. If it's local wine, local snacks, local water — I know the hotel gets it. If it's Pringles and Heineken, I know they don't.",
    ],
    extractedSignals: [
      { tag: 'Bathtub-non-negotiable', cat: 'Preference', confidence: 0.97 },
      { tag: 'Evening-soak-ritual', cat: 'Behavior', confidence: 0.95 },
      { tag: 'Minibar-as-taste-signal', cat: 'Preference', confidence: 0.92 },
      { tag: 'Local-curation-detector', cat: 'Preference', confidence: 0.90 },
    ],
    certaintyAfter: { Design: 88, Atmosphere: 76, Character: 78, Service: 84, FoodDrink: 58, Setting: 65, Wellness: 40, Sustainability: 34 },
  },

  // ═══════════════════════════════════════
  // ACT 3 — "Deep Taste" (structured depth + adaptive gap-fill)
  // ═══════════════════════════════════════
  {
    id: 'food-and-senses',
    phaseNumber: 14,
    title: 'Food & Senses',
    subtitle: 'How you taste the world',
    modality: 'scene',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 87, Atmosphere: 76, Character: 74, Service: 84, FoodDrink: 65, Setting: 64, Wellness: 38, Sustainability: 34 },
    sceneQuestions: [
      {
        id: 'fd7-market',
        prompt: 'You stumble onto an incredible local food market. You:',
        domains: ['FoodDrink', 'Character'],
        options: [
          { id: 'cook', label: 'Buy ingredients and ask the hotel if I can use their kitchen', signals: ['Cook-on-vacation', 'Hands-on-food'], domain: 'FoodDrink' },
          { id: 'graze', label: 'Try everything — this is why I travel', signals: ['Grazer-explorer', 'Food-adventurer'], domain: 'FoodDrink' },
          { id: 'photo', label: 'Take photos but eat somewhere proper later', signals: ['Visual-collector', 'Dining-formality'], domain: 'FoodDrink' },
          { id: 'queue', label: 'Find the one stall everyone\'s lining up at', signals: ['Crowd-signal-follower', 'Local-consensus'], domain: 'FoodDrink' },
        ],
      },
      {
        id: 'sp1-sound',
        prompt: 'Close your eyes. Which place are you in?',
        domains: ['Atmosphere'],
        isValidator: true,
        options: [
          { id: 'waves', label: 'Waves, distant wind, silence between them', signals: ['Coastal-silence', 'Sea-drawn', 'Natural-quiet'], domain: 'Atmosphere' },
          { id: 'cafe', label: 'Espresso machines, low conversation, a spoon against ceramic', signals: ['Café-culture-ambient', 'Urban-soundtrack'], domain: 'Atmosphere' },
          { id: 'nature', label: 'Birdsong, rustling leaves, a creek somewhere', signals: ['Nature-immersion', 'Rural-drawn', 'Biophilic'], domain: 'Atmosphere' },
          { id: 'social', label: 'Music from somewhere — live, not a speaker — glasses clinking', signals: ['Social-music-energy', 'Convivial-atmosphere'], domain: 'Atmosphere' },
        ],
      },
      {
        id: 'sp4-light',
        prompt: 'Your favorite light:',
        domains: ['Atmosphere', 'Design'],
        options: [
          { id: 'dawn', label: 'Early morning — that pale blue before the sun is fully up', signals: ['Dawn-drawn', 'Early-riser-aesthetic'], domain: 'Atmosphere' },
          { id: 'midday', label: 'Midday Mediterranean — hard shadows, white walls, blinding', signals: ['Mediterranean-brightness', 'High-contrast'], domain: 'Atmosphere' },
          { id: 'golden', label: 'Golden hour — everything warm, long shadows', signals: ['Golden-hour-romantic', 'Warm-light-seeker'], domain: 'Atmosphere' },
          { id: 'dusk', label: 'Candlelight and dusk — the world getting softer', signals: ['Evening-mood', 'Intimate-light', 'Nocturnal-drawn'], domain: 'Atmosphere' },
        ],
      },
      {
        id: 'wb2-spa',
        prompt: 'Free afternoon at the hotel:',
        domains: ['Wellness'],
        options: [
          { id: 'spa', label: 'Book a treatment — this is what hotels are for', signals: ['Spa-user', 'Wellness-ritual-seeker'], domain: 'Wellness' },
          { id: 'never', label: 'I\'ve literally never used a hotel spa', signals: ['Spa-indifferent', 'Non-wellness-traveler'], domain: 'Wellness' },
          { id: 'specific', label: 'Depends — if it\'s a hammam or onsen, absolutely. Generic spa, no.', signals: ['Specific-spa-seeker', 'Cultural-wellness'], domain: 'Wellness' },
          { id: 'local', label: 'I\'d rather find a local bathhouse than use the hotel\'s', signals: ['Local-wellness-seeker', 'Authenticity-in-wellness'], domain: 'Wellness' },
        ],
      },
      {
        id: 'ad6-indoor-outdoor',
        prompt: 'The boundary between inside and outside:',
        domains: ['Design', 'Geography'],
        options: [
          { id: 'open', label: 'Should disappear — sliding walls, no glass, fully open to the air', signals: ['Open-air-obsessed', 'Tropical-drawn', 'Boundary-dissolving'], domain: 'Design' },
          { id: 'windows', label: 'Big windows, but clearly inside — I want the view without the bugs', signals: ['View-seeker-protected', 'Controlled-connection'], domain: 'Design' },
          { id: 'refuge', label: 'Thick walls, small windows — the room is a refuge from outside', signals: ['Cocoon-builder', 'Interior-sanctuary'], domain: 'Design' },
          { id: 'courtyard', label: 'A courtyard — the outside is brought inside, contained', signals: ['Courtyard-dweller', 'Contained-nature', 'Mediterranean-plan'], domain: 'Design' },
        ],
      },
    ],
  },
  {
    id: 'visual-pairs',
    phaseNumber: 15,
    title: 'What Draws You In',
    subtitle: 'Two images — tap the one that pulls you',
    modality: 'image-pair',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 92, Atmosphere: 82, Character: 80, Service: 78, FoodDrink: 72, Setting: 72, Wellness: 62, Sustainability: 34 },
    imagePairQuestions: [
      {
        id: 'cuisine-compass',
        prompt: 'Saturday night — where are you going?',
        a: { imageUrl: '/onboarding/pairs/cuisine-a.jpg', label: 'The omakase counter' },
        b: { imageUrl: '/onboarding/pairs/cuisine-b.jpg', label: 'The trattoria' },
        aSignals: ['Precision-dining', 'Counter-culture', 'Japanese-aesthetic-drawn'],
        bSignals: ['Convivial-dining', 'Italian-warmth', 'Family-energy'],
        domain: 'FoodDrink',
      },
      {
        id: 'temperature-as-taste',
        prompt: 'Which room pulls you in?',
        a: { imageUrl: '/onboarding/pairs/temperature-a.jpg', label: 'Warm enclosure' },
        b: { imageUrl: '/onboarding/pairs/temperature-b.jpg', label: 'Cool breeze' },
        aSignals: ['Warm-enclosure', 'Cocoon-seeker', 'Interior-focused'],
        bSignals: ['Airflow-obsessed', 'Light-over-warmth', 'Open-element'],
        domain: 'Atmosphere',
      },
      {
        id: 'pool-philosophy',
        prompt: 'Your pool:',
        a: { imageUrl: '/onboarding/pairs/pool-a.jpg', label: 'Wild swimming' },
        b: { imageUrl: '/onboarding/pairs/pool-b.jpg', label: 'Poolside service' },
        aSignals: ['Wild-swimming', 'Cold-water', 'Landscape-immersion', 'Anti-amenity'],
        bSignals: ['Pool-as-luxury', 'Attended-comfort', 'Classic-resort'],
        domain: 'Wellness',
        isValidator: true,
      },
      {
        id: 'conversion-vs-built',
        prompt: 'Where would you rather sleep?',
        a: { imageUrl: '/onboarding/pairs/conversion-a.jpg', label: 'The converted palazzo' },
        b: { imageUrl: '/onboarding/pairs/conversion-b.jpg', label: 'The architect\'s vision' },
        aSignals: ['Adaptive-reuse', 'Layered-history', 'Imperfection-lover'],
        bSignals: ['Architectural-intent', 'Clean-vision', 'Site-specific-modernism'],
        domain: 'Design',
        isValidator: true,
      },
      {
        id: 'color-temperature',
        prompt: 'Your room:',
        a: { imageUrl: '/onboarding/pairs/color-a.jpg', label: 'Warm palette' },
        b: { imageUrl: '/onboarding/pairs/color-b.jpg', label: 'Cool palette' },
        aSignals: ['Warm-palette', 'Earth-tones', 'Mediterranean-drawn'],
        bSignals: ['Cool-palette', 'Mineral-tones', 'Scandinavian-drawn'],
        domain: 'Design',
      },
    ],
  },
  {
    id: 'details-matter',
    phaseNumber: 16,
    title: 'The Details That Matter',
    subtitle: 'Rank what changes everything for you',
    modality: 'force-rank',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [
      { tag: 'Detail-priority-ranked', cat: 'Design', confidence: 0.93 },
    ],
    certaintyAfter: { Design: 90, Atmosphere: 78, Character: 78, Service: 85, FoodDrink: 60, Setting: 68, Wellness: 55, Sustainability: 34 },
    forceRankItems: [
      {
        id: 'light-quality',
        label: 'The quality of light',
        description: 'Natural light, the way it falls through a room, how it changes through the day',
        signals: ['Light-obsessed', 'Natural-light-priority', 'Window-first'],
        domain: 'Design',
      },
      {
        id: 'textiles',
        label: 'How the bed feels',
        description: 'The linens, the mattress, the pillows — that first moment you lie down',
        signals: ['Textile-sensitive', 'Bed-quality-priority', 'Tactile-standards'],
        domain: 'Design',
      },
      {
        id: 'silence',
        label: 'Silence and stillness',
        description: 'No hum of AC, no hallway noise, the ability to actually rest',
        signals: ['Silence-sensitive', 'Acoustic-aware', 'Stillness-seeker'],
        domain: 'Atmosphere',
      },
      {
        id: 'scent',
        label: 'How a place smells',
        description: 'Fresh air, no synthetic fragrance, maybe woodfire or salt air',
        signals: ['Scent-conscious', 'Anti-synthetic-fragrance', 'Fresh-air-obsessive'],
        domain: 'Wellness',
      },
      {
        id: 'food-on-site',
        label: 'The food at the hotel itself',
        description: 'A restaurant worth eating at, not just room service as an afterthought',
        signals: ['Hotel-food-matters', 'Destination-dining', 'In-house-restaurant-priority'],
        domain: 'FoodDrink',
      },
      {
        id: 'arrival-moment',
        label: 'The first five minutes',
        description: 'Check-in, the welcome, walking into the room — that initial impression',
        signals: ['Arrival-ritual-matters', 'First-impression-sensitive', 'Check-in-experience'],
        domain: 'Service',
      },
      {
        id: 'bathroom',
        label: 'The bathroom',
        description: 'Water pressure, good products, a bathtub, proper lighting',
        signals: ['Bathroom-quality-priority', 'Shower-pressure-aware', 'Bathing-ritual'],
        domain: 'Wellness',
      },
      {
        id: 'view',
        label: 'What you see from the room',
        description: 'The view, the balcony, the connection to the landscape',
        signals: ['View-priority', 'Room-landscape-connection', 'Outdoor-access'],
        domain: 'Geography',
      },
    ],
  },
  {
    id: 'emotional-core',
    phaseNumber: 17,
    title: 'Why You Travel',
    subtitle: 'What a great trip actually gives you',
    modality: 'quick-choice',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [
      { tag: 'Emotional-drivers-identified', cat: 'Emotion', confidence: 0.90 },
    ],
    certaintyAfter: { Design: 94, Atmosphere: 85, Character: 85, Service: 88, FoodDrink: 72, Setting: 78, Wellness: 62, Sustainability: 38 },
    quickChoiceMax: 3,
    quickChoiceOptions: [
      {
        id: 'recalibrate-eye',
        label: 'My eye gets recalibrated',
        description: 'I come home noticing things differently — a material, a color, a way of arranging space',
        signals: ['Aesthetic-expansion', 'Sensory-recalibration', 'Design-driven-traveler'],
        domain: 'Emotion',
      },
      {
        id: 'deep-rest',
        label: 'I actually rest',
        description: 'Not just sleep — a deeper unwinding that takes days to build',
        signals: ['Deep-rest-seeker', 'Slow-unwinding', 'Recovery-traveler'],
        domain: 'Emotion',
      },
      {
        id: 'connect-people',
        label: 'I connect with the people I\'m with',
        description: 'Travel strips away the noise — the best trips bring us closer',
        signals: ['Relational-traveler', 'Shared-experience-priority', 'Bonding-through-travel'],
        domain: 'Emotion',
      },
      {
        id: 'surprise-discovery',
        label: 'I discover something I didn\'t expect',
        description: 'A neighborhood, a flavor, a conversation — the unplanned moments',
        signals: ['Spontaneous-discovery', 'Serendipity-seeker', 'Anti-over-planning'],
        domain: 'Core',
      },
      {
        id: 'sense-of-place',
        label: 'I feel where I am',
        description: 'The place seeps in — its rhythms, its light, the way people live there',
        signals: ['Place-immersion', 'Local-rhythm-seeker', 'Cultural-absorption'],
        domain: 'Core',
      },
      {
        id: 'eat-differently',
        label: 'I eat things I\'d never eat at home',
        description: 'Travel is permission to be adventurous, indulgent, or both',
        signals: ['Culinary-adventurer', 'Food-as-travel-driver', 'Eating-adventurously'],
        domain: 'FoodDrink',
      },
      {
        id: 'beauty-quiet',
        label: 'Beauty makes me quiet',
        description: 'A view, a room, a courtyard — certain moments demand stillness',
        signals: ['Beauty-seeker', 'Contemplative-traveler', 'Aesthetic-reverence'],
        domain: 'Atmosphere',
      },
      {
        id: 'come-home-changed',
        label: 'I come home slightly changed',
        description: 'New influences, new references, a subtly different version of myself',
        signals: ['Influence-collector', 'Transformation-seeker', 'Identity-through-travel'],
        domain: 'Core',
      },
    ],
  },
  {
    id: 'travel-scenarios',
    phaseNumber: 18,
    title: 'How You Travel',
    subtitle: 'Real situations, honest answers',
    modality: 'scene',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 95, Atmosphere: 87, Character: 87, Service: 90, FoodDrink: 78, Setting: 82, Wellness: 66, Sustainability: 40 },
    sceneQuestions: [
      {
        id: 'tr1-day3',
        prompt: 'Day 3 of a week-long trip. You\'ve done a lot. Today you:',
        domains: ['Atmosphere'],
        isValidator: true,
        options: [
          { id: 'keep-going', label: 'Keep going — I\'ll rest when I\'m home', signals: ['Pace-maximizer', 'FOMO-driven'], domain: 'Atmosphere' },
          { id: 'half-day', label: 'Take the morning off, then head out after lunch', signals: ['Half-day-rest', 'Balanced-pacer'], domain: 'Atmosphere' },
          { id: 'full-rest', label: 'Full rest day — pool, book, nowhere to be', signals: ['Full-rest-day', 'Decompression-needer'], domain: 'Atmosphere' },
          { id: 'scene-change', label: 'Leave the hotel entirely — rent a car, day trip, change the scenery', signals: ['Scene-changer', 'Novelty-within-trip'], domain: 'Character' },
        ],
      },
      {
        id: 'tr3-planning',
        prompt: 'Your trip planning approach:',
        domains: ['Core'],
        options: [
          { id: 'spreadsheet', label: 'Spreadsheet. Restaurants, times, backup options, driving distances.', signals: ['Hyper-planner', 'Control-maximizer'], domain: 'Core' },
          { id: 'loose', label: 'I know the hotel and the flights. Everything else is day-of.', signals: ['Loose-framework', 'Spontaneity-comfortable'], domain: 'Core' },
          { id: 'advisor', label: 'I hire someone — a travel advisor handles it.', signals: ['Advisor-delegator', 'Premium-service-buyer'], domain: 'Core' },
          { id: 'passive', label: 'My partner/friend plans. I show up.', signals: ['Passive-traveler', 'Delegation-natural'], domain: 'Core' },
        ],
      },
      {
        id: 'sc1-rain',
        prompt: 'It\'s raining all day on your beach vacation. You:',
        domains: ['Atmosphere', 'Character'],
        options: [
          { id: 'explore', label: 'Find a museum, gallery, or market — rain is an excuse to explore differently', signals: ['Rain-explorer', 'Adaptive-traveler'], domain: 'Character' },
          { id: 'hotel', label: 'This is why I picked a hotel with a great bar and a library', signals: ['Hotel-as-refuge', 'Property-is-destination'], domain: 'Atmosphere' },
          { id: 'anyway', label: 'Put on a raincoat and go anyway — I\'m not made of sugar', signals: ['Weather-indifferent', 'Determination-over-comfort'], domain: 'Character' },
          { id: 'indulge', label: 'Spa, movie, room service — lean into it', signals: ['Indoor-indulger', 'Self-care-traveler'], domain: 'Wellness' },
        ],
      },
      {
        id: 'sc3-wedding',
        prompt: 'You arrive and discover the hotel is hosting a 200-person wedding this weekend.',
        domains: ['Atmosphere'],
        isValidator: true,
        options: [
          { id: 'fun', label: 'That sounds fun — weddings mean good energy', signals: ['Social-energy-positive', 'Crowd-embracer'], domain: 'Atmosphere' },
          { id: 'deal', label: 'I\'m annoyed but I\'ll deal — noise-canceling headphones', signals: ['Tolerant-adapter', 'Pragmatic-traveler'], domain: 'Atmosphere' },
          { id: 'room-change', label: 'I\'m asking for a different room, far from the event', signals: ['Quiet-seeker-negotiator', 'Proactive-comfort'], domain: 'Atmosphere' },
          { id: 'leave', label: 'I\'m changing hotels', signals: ['Non-negotiable-quiet', 'Zero-tolerance-disruption'], domain: 'Atmosphere' },
        ],
      },
      {
        id: 'bv3-upgrade',
        prompt: 'At check-in, they offer an upgrade to a suite for $200 more per night. You:',
        domains: ['Core', 'Service'],
        options: [
          { id: 'yes', label: 'Yes, immediately — life\'s short', signals: ['Impulse-upgrader', 'Experience-maximizer'], domain: 'Core' },
          { id: 'see-it', label: 'Can I see it first?', signals: ['Visual-confirmer', 'Evidence-based-spender'], domain: 'Core' },
          { id: 'worth-it', label: 'What\'s the suite actually like? I need to know it\'s worth it', signals: ['Value-analyzer', 'ROI-thinker'], domain: 'Core' },
          { id: 'no', label: 'No — I researched my room, I want what I booked', signals: ['Plan-committed', 'Research-confident'], domain: 'Core' },
        ],
      },
    ],
  },
  // ─── New: Dining & Drink Depth (expands FoodDrink signal for restaurants, bars, cafés) ───
  {
    id: 'dining-depth',
    phaseNumber: 19,
    title: 'How You Eat',
    subtitle: 'Restaurants, markets, bars — not just hotel food',
    modality: 'scene',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 96, Atmosphere: 89, Character: 89, Service: 91, FoodDrink: 85, Setting: 85, Wellness: 68, Sustainability: 40 },
    sceneQuestions: [
      {
        id: 'fd1-discovery',
        prompt: 'You land in a city you\'ve never been to. Dinner tonight:',
        domains: ['FoodDrink'],
        isValidator: true,
        options: [
          { id: 'reservation', label: 'I already have a reservation — booked it 3 weeks ago', signals: ['Restaurant-planner', 'Research-driven-eater', 'Control-over-spontaneity'], domain: 'FoodDrink' },
          { id: 'taxi', label: 'I\'ll ask the taxi driver', signals: ['Spontaneous-diner', 'Local-trust', 'Adventure-eater'], domain: 'FoodDrink' },
          { id: 'walk', label: 'Walk the neighborhood until something feels right', signals: ['Wanderer-eater', 'Intuition-diner', 'Street-scanner'], domain: 'FoodDrink' },
          { id: 'hotel', label: 'Eat at the hotel — I\'m tired, and it\'s probably good', signals: ['Hotel-diner-default', 'Convenience-eater', 'Arrival-rest'], domain: 'FoodDrink' },
        ],
      },
      {
        id: 'ba2-where-ate',
        prompt: 'Your last trip — where did you eat most of your meals?',
        domains: ['FoodDrink'],
        isValidator: true,
        options: [
          { id: 'researched', label: 'Restaurants I\'d researched before the trip', signals: ['Pre-researched-eater-actual', 'Dining-planner'], domain: 'FoodDrink' },
          { id: 'walking', label: 'Places I found just walking around', signals: ['Wanderer-eater-actual', 'Serendipity-diner'], domain: 'FoodDrink' },
          { id: 'street', label: 'Street food, markets, casual spots', signals: ['Street-food-actual', 'Casual-eater', 'Market-grazer'], domain: 'FoodDrink' },
          { id: 'mixed', label: 'A mix — nice dinners out, casual everything else', signals: ['Mixed-strategy-actual', 'Occasion-calibrated-eater'], domain: 'FoodDrink' },
        ],
      },
      {
        id: 'fd5-kitchen',
        prompt: 'The restaurant:',
        domains: ['FoodDrink', 'Service'],
        options: [
          { id: 'open', label: 'I want to see the kitchen — fire, chefs working, the energy', signals: ['Open-kitchen-drawn', 'Process-interested', 'Theater-of-cooking'], domain: 'FoodDrink' },
          { id: 'hidden', label: 'I want to forget the kitchen exists — just the plate, perfectly', signals: ['Presentation-focused', 'Seamless-service', 'Outcome-oriented'], domain: 'FoodDrink' },
          { id: 'counter', label: 'A counter seat — close enough to watch, but not a show', signals: ['Counter-culture', 'Proximity-dining', 'Intimate-food'], domain: 'FoodDrink' },
          { id: 'outdoors', label: 'Outside — I barely notice the kitchen if the setting is right', signals: ['Al-fresco-priority', 'Setting-over-food', 'Terrace-diner'], domain: 'Geography' },
        ],
      },
      {
        id: 'sc2-fullbooked',
        prompt: 'The restaurant you wanted most is fully booked. You:',
        domains: ['FoodDrink', 'Core'],
        options: [
          { id: 'show-up', label: 'Show up anyway and wait at the bar — something always opens up', signals: ['Persistent-optimist', 'Bar-comfortable', 'Walk-in-warrior'], domain: 'FoodDrink' },
          { id: 'concierge', label: 'Ask the hotel concierge to pull strings', signals: ['Concierge-leverager', 'Service-network-user'], domain: 'Service' },
          { id: 'find-another', label: 'Find somewhere else — there\'s always another great place', signals: ['Adaptable-eater', 'Anti-scarcity-mindset'], domain: 'FoodDrink' },
          { id: 'pre-book', label: 'This is why I book restaurants before I book flights', signals: ['Advance-restaurant-planner', 'Dining-priority-over-logistics'], domain: 'FoodDrink' },
        ],
      },
      {
        id: 'fd3-breakfast',
        prompt: 'Your ideal hotel breakfast:',
        domains: ['FoodDrink', 'Service'],
        options: [
          { id: 'pastry-door', label: 'Fresh pastries left at the door in a paper bag', signals: ['Pastry-door-ritual', 'Private-morning', 'French-touch'], domain: 'FoodDrink' },
          { id: 'buffet', label: 'Long buffet — eggs to order, fresh juice bar, the works', signals: ['Buffet-lover', 'Abundance-seeker', 'Choice-maximizer'], domain: 'FoodDrink' },
          { id: 'skip-cafe', label: 'Skip it — I\'ll find a café in the neighborhood', signals: ['Skip-hotel-breakfast', 'Neighborhood-café-seeker', 'Local-morning-routine'], domain: 'FoodDrink' },
          { id: 'terrace', label: 'Full spread on a terrace with a view', signals: ['Terrace-breakfast', 'View-plus-food', 'Morning-ritual-scenic'], domain: 'FoodDrink' },
        ],
      },
    ],
  },
  // ─── New: Cultural Immersion (strong signal for neighborhoods, experiences, activities) ───
  {
    id: 'cultural-immersion',
    phaseNumber: 20,
    title: 'How Deep You Go',
    subtitle: 'Culture, language, neighborhoods',
    modality: 'scene',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 96, Atmosphere: 90, Character: 92, Service: 91, FoodDrink: 86, Setting: 88, Wellness: 70, Sustainability: 41 },
    sceneQuestions: [
      {
        id: 'ci1-language',
        prompt: 'You\'re in a country where you don\'t speak the language:',
        domains: ['Character'],
        options: [
          { id: 'love-it', label: 'I love it — pointing, gesturing, Google Translate, it\'s part of the adventure', signals: ['Language-adventurer', 'Friction-embracer', 'Communication-improvisor'], domain: 'Character' },
          { id: 'english', label: 'I need enough English speakers around to feel comfortable', signals: ['English-baseline-needed', 'Communication-comfort-first'], domain: 'Character' },
          { id: 'learn', label: 'I\'ll learn a few phrases — I want to try', signals: ['Phrase-learner', 'Cultural-respecter', 'Effort-signaler'], domain: 'Character' },
          { id: 'guide', label: 'I hire a local guide who can bridge the gap', signals: ['Guide-dependent', 'Cultural-access-buyer', 'Bridge-seeker'], domain: 'Character' },
        ],
      },
      {
        id: 'ci3-depth',
        prompt: 'Free day in Kyoto. You:',
        domains: ['Character', 'Geography'],
        options: [
          { id: 'temples', label: 'Visit the temples everyone talks about — they\'re famous for a reason', signals: ['Landmark-visitor', 'Canon-respecter', 'Completionist'], domain: 'Character' },
          { id: 'wander', label: 'Find a neighborhood nobody mentions and just walk', signals: ['Neighborhood-wanderer', 'Off-path-explorer', 'Drift-traveler'], domain: 'Geography' },
          { id: 'class', label: 'Book a private tea ceremony or cooking class', signals: ['Cultural-experience-seeker', 'Hands-on-culture', 'Activity-booker'], domain: 'Character' },
          { id: 'hotel-rec', label: 'Go where the hotel recommends — they know best', signals: ['Hotel-guided', 'Trust-property-concierge', 'Delegation-natural'], domain: 'Service' },
        ],
      },
      {
        id: 'ci4-bar',
        prompt: 'The hotel bar:',
        domains: ['Character', 'Atmosphere'],
        options: [
          { id: 'locals', label: 'Full of locals — you\'re the only tourist', signals: ['Local-integration', 'Authenticity-seeker', 'Insider-energy'], domain: 'Character' },
          { id: 'international', label: 'International mix — interesting people from everywhere', signals: ['Cosmopolitan-mix', 'International-energy', 'Cross-cultural-draw'], domain: 'Character' },
          { id: 'quiet', label: 'Mostly empty — just a bartender who knows what they\'re doing', signals: ['Quiet-bar-seeker', 'Craft-cocktail-appreciator', 'Solo-drink-comfortable'], domain: 'Atmosphere' },
          { id: 'skip', label: 'I rarely use the hotel bar — I\'d rather find a real one nearby', signals: ['Anti-hotel-bar', 'Neighborhood-bar-seeker', 'Local-nightlife-drawn'], domain: 'Geography' },
        ],
      },
      {
        id: 'mu1-museum',
        prompt: 'You have one free afternoon and two options:',
        domains: ['Character', 'Geography'],
        options: [
          { id: 'big-museum', label: 'The city\'s major museum — it\'s world-class and you haven\'t been', signals: ['Major-museum-drawn', 'Canonical-culture', 'Institution-visitor'], domain: 'Character' },
          { id: 'small-gallery', label: 'A tiny gallery a local recommended — only open on Thursdays', signals: ['Small-gallery-seeker', 'Local-art-scene', 'Hidden-cultural-gem'], domain: 'Character' },
          { id: 'street-art', label: 'Skip both — you\'d rather walk a neighborhood with great street art and architecture', signals: ['Anti-museum', 'Street-culture-drawn', 'Architecture-walker', 'Outdoor-art-preferred'], domain: 'Geography' },
          { id: 'market', label: 'Neither — you\'d find the best food market or vintage market instead', signals: ['Market-over-museum', 'Browse-and-taste', 'Market-explorer'], domain: 'FoodDrink' },
        ],
      },
      {
        id: 'mu2-gallery-style',
        prompt: 'When you do visit a museum or gallery, you tend to:',
        domains: ['Character'],
        options: [
          { id: 'deep-dive', label: 'Spend hours — I read every panel, sit with pieces I love', signals: ['Museum-deep-diver', 'Contemplative-viewer', 'Art-engaged'], domain: 'Character' },
          { id: 'highlights', label: 'Hit the highlights, take a few photos, move on within an hour', signals: ['Museum-skimmer', 'Highlight-hitter', 'Culture-efficient'], domain: 'Character' },
          { id: 'café-gift', label: 'Honestly, I\'m there for the café and the gift shop', signals: ['Museum-peripheral', 'Café-culture', 'Design-shop-drawn'], domain: 'FoodDrink' },
          { id: 'rarely', label: 'I rarely go — it\'s just not my thing', signals: ['Museum-averse', 'Anti-institution', 'Experience-over-exhibit'], domain: 'Character' },
        ],
      },
      {
        id: 'sc4-checkout',
        prompt: 'It\'s checkout day. Flight\'s not until 8pm. You:',
        domains: ['Core', 'Atmosphere'],
        options: [
          { id: 'late-checkout', label: 'Negotiate late checkout — I\'m not leaving this room until I have to', signals: ['Late-checkout-negotiator', 'Room-attached', 'Every-last-minute'], domain: 'Atmosphere' },
          { id: 'explore', label: 'Check out, leave bags, explore the neighborhood one last time', signals: ['Last-minute-explorer', 'Neighborhood-completionist', 'Saver-of-moments'], domain: 'Geography' },
          { id: 'airport-early', label: 'Head to the airport early — I like being ahead of schedule', signals: ['Airport-buffer', 'Logistics-anxiety', 'Transition-planner'], domain: 'Core' },
          { id: 'day-room', label: 'Book a day room at a different hotel near the airport', signals: ['Logistics-optimizer', 'Hotel-as-utility', 'Comfort-maximizer'], domain: 'Core' },
        ],
      },
      {
        id: 'sc5-empty',
        prompt: 'You arrive at a beautiful hotel and realize you might be the only guest.',
        domains: ['Atmosphere', 'Character'],
        options: [
          { id: 'paradise', label: 'Paradise — this is the dream', signals: ['Solitude-lover', 'Empty-hotel-dream', 'Privacy-maximizer'], domain: 'Atmosphere' },
          { id: 'unsettling', label: 'Actually unsettling — I want some life around me', signals: ['Social-baseline-needed', 'Ambient-human-energy', 'Crowd-comforted'], domain: 'Atmosphere' },
          { id: 'depends', label: 'Depends on the hotel — a big resort, weird. A tiny guesthouse, perfect.', signals: ['Scale-aware', 'Context-sensitive-solitude', 'Intimate-property-drawn'], domain: 'Character' },
          { id: 'ask-why', label: 'I\'d wonder what\'s wrong — is there something I don\'t know?', signals: ['Crowd-signal-reader', 'Popularity-as-quality-signal', 'Risk-aware-booker'], domain: 'Core' },
        ],
      },
    ],
  },
  // ─── New: Rhythm & Pace (sliders + scenes for travel style) ───
  {
    id: 'rhythm-and-pace',
    phaseNumber: 21,
    title: 'Your Rhythm',
    subtitle: 'How you move through a trip',
    modality: 'slider',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 96, Atmosphere: 91, Character: 93, Service: 91, FoodDrink: 87, Setting: 90, Wellness: 72, Sustainability: 42 },
    sliderDefs: [
      {
        id: 'stay-length',
        leftLabel: '2–3 nights per city — keep moving',
        rightLabel: 'A full week minimum — I need to settle in',
        leftSignals: ['City-hopper', 'Variety-seeker', 'Multi-stop-trip'],
        rightSignals: ['Deep-dwell', 'Slow-immersion', 'One-base-trip'],
        domain: 'Character',
      },
      {
        id: 'return-vs-new',
        leftLabel: 'I almost never go back to the same place',
        rightLabel: 'I have places I return to every year',
        leftSignals: ['Novelty-seeker', 'One-and-done', 'New-over-known'],
        rightSignals: ['Loyalty-returner', 'Depth-over-breadth', 'Annual-ritual-place'],
        domain: 'Core',
      },
      {
        id: 'room-time',
        leftLabel: 'I was barely in the room — just to sleep',
        rightLabel: 'I spent serious time there — it was part of the trip',
        leftSignals: ['Room-as-bed-actual', 'Exterior-focused-actual', 'Explorer-over-lounger'],
        rightSignals: ['Room-dweller-actual', 'Interior-focused-actual', 'Property-is-destination'],
        domain: 'Design',
      },
      {
        id: 'tourist-infrastructure',
        leftLabel: 'Well-traveled — good infrastructure, reliable, easy',
        rightLabel: 'Barely on the map — figuring it out is half the point',
        leftSignals: ['Infrastructure-valued', 'Reliability-first', 'Convenience-traveler'],
        rightSignals: ['Pioneer-traveler', 'Friction-as-adventure', 'Off-grid-drawn'],
        domain: 'Geography',
      },
      {
        id: 'drink-philosophy',
        leftLabel: 'I know exactly what I want to drink',
        rightLabel: 'Surprise me — dealer\'s choice',
        leftSignals: ['Drink-connoisseur', 'Specific-palate', 'Wine-literate'],
        rightSignals: ['Drink-delegator', 'Trust-the-sommelier', 'Openness-to-surprise'],
        domain: 'FoodDrink',
      },
      {
        id: 'meal-length',
        leftLabel: 'Dinner should be 45 minutes — I have things to do',
        rightLabel: 'Dinner is the main event — 3 hours, wine pairings',
        leftSignals: ['Efficient-eater', 'Meal-as-fuel', 'Time-conscious-diner'],
        rightSignals: ['Dining-ritualist', 'Meal-as-performance', 'Multi-course-lover'],
        domain: 'FoodDrink',
      },
      {
        id: 'sleep-priority',
        leftLabel: 'I can sleep anywhere — it barely matters',
        rightLabel: 'Sleep quality makes or breaks the trip',
        leftSignals: ['Sleep-flexible', 'Adaptable-sleeper'],
        rightSignals: ['Sleep-obsessive', 'Bed-non-negotiable', 'Blackout-curtain-hunter'],
        domain: 'Wellness',
      },
    ],
  },
  // ─── New: Movement & Wellness (non-hotel signal: spas, activities, outdoor venues) ───
  {
    id: 'movement-and-wellness',
    phaseNumber: 22,
    title: 'Body & Movement',
    subtitle: 'How you take care of yourself on the road',
    modality: 'quick-choice',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 96, Atmosphere: 91, Character: 93, Service: 91, FoodDrink: 87, Setting: 90, Wellness: 80, Sustainability: 42 },
    quickChoiceMax: 2,
    quickChoiceMin: 1,
    quickChoiceOptions: [
      { id: 'run-walk', label: 'Run or walk — I explore by covering distance', signals: ['Run-explorer', 'Distance-mover', 'Walking-as-discovery'], domain: 'Wellness' },
      { id: 'swim', label: 'Swim — ocean, pool, lake, whatever\'s available', signals: ['Swimmer', 'Water-drawn', 'Aquatic-movement'], domain: 'Wellness' },
      { id: 'yoga', label: 'Yoga or stretching — I need to reset', signals: ['Yoga-traveler', 'Reset-seeker', 'Mindful-movement'], domain: 'Wellness' },
      { id: 'hike', label: 'Hiking or outdoor activity with purpose', signals: ['Hiker-adventurer', 'Purpose-driven-movement', 'Nature-active'], domain: 'Wellness' },
      { id: 'none', label: 'I don\'t — vacation means not exercising', signals: ['Exercise-free-vacation', 'Full-rest-mode', 'Anti-gym-on-holiday'], domain: 'Wellness' },
      { id: 'whatever', label: 'Whatever the place offers — surfing, tennis, biking', signals: ['Activity-opportunist', 'Spontaneous-athlete', 'Place-driven-activity'], domain: 'Wellness' },
    ],
  },
  // ─── New: Scent & Texture (sensory depth for place matching) ───
  {
    id: 'scent-and-texture',
    phaseNumber: 23,
    title: 'Scent & Texture',
    subtitle: 'The sensory details that make a place yours',
    modality: 'quick-choice',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 97, Atmosphere: 93, Character: 93, Service: 91, FoodDrink: 87, Setting: 91, Wellness: 81, Sustainability: 42 },
    quickChoiceMax: 2,
    quickChoiceMin: 2,
    quickChoiceOptions: [
      { id: 'woodsmoke', label: 'Woodsmoke and cold air', signals: ['Woodsmoke-drawn', 'Mountain-cabin-scent', 'Fire-ritual'], domain: 'Atmosphere' },
      { id: 'salt', label: 'Salt water and sunscreen', signals: ['Coastal-scent', 'Beach-drawn', 'Sea-memory'], domain: 'Geography' },
      { id: 'linen', label: 'Fresh linen, just out of the sun', signals: ['Linen-scent', 'Clean-air-drawn', 'Textile-sensitive'], domain: 'Design' },
      { id: 'coffee', label: 'Coffee and warm bread', signals: ['Café-scent', 'Morning-ritual-drawn', 'Bakery-walker'], domain: 'FoodDrink' },
      { id: 'jasmine', label: 'Jasmine at night', signals: ['Night-jasmine', 'Tropical-drawn', 'Garden-scent-lover'], domain: 'Geography' },
      { id: 'stone', label: 'Old books and stone', signals: ['Heritage-scent', 'Library-drawn', 'Mineral-air-lover'], domain: 'Design' },
    ],
  },
  // ─── New: Browsing & Discovery (shops, markets, browsing style — fills shop/market signal gap) ───
  {
    id: 'browsing-and-discovery',
    phaseNumber: 24,
    title: 'Browsing & Discovery',
    subtitle: 'How you find things worth bringing home',
    modality: 'scene',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 97, Atmosphere: 93, Character: 94, Service: 91, FoodDrink: 88, Setting: 92, Wellness: 82, Sustainability: 43 },
    sceneQuestions: [
      {
        id: 'sh1-shopping-style',
        prompt: 'You\'re walking through a new city with no agenda. You\'re most likely to wander into:',
        domains: ['Character', 'Geography'],
        options: [
          { id: 'design-shop', label: 'A beautifully curated design or homeware shop', signals: ['Design-shopper', 'Curation-drawn', 'Homeware-browser', 'Shop-aesthetic-sensitive'], domain: 'Design' },
          { id: 'food-market', label: 'A food hall or covered market full of local producers', signals: ['Market-explorer', 'Food-market-drawn', 'Local-produce-seeker', 'Taste-led-browser'], domain: 'FoodDrink' },
          { id: 'vintage', label: 'A vintage or secondhand shop — clothes, books, records', signals: ['Vintage-hunter', 'Secondhand-drawn', 'Treasure-seeker', 'Anti-new-retail'], domain: 'Character' },
          { id: 'none', label: 'Honestly, I don\'t really shop when I travel', signals: ['Anti-shopper', 'Experience-over-things', 'Non-material-traveler'], domain: 'Core' },
        ],
      },
      {
        id: 'sh2-souvenir',
        prompt: 'You want to bring something home from a trip. You\'re looking for:',
        domains: ['Character', 'Design'],
        options: [
          { id: 'craft', label: 'Something handmade by a local artisan — ceramics, textiles, leather', signals: ['Artisan-seeker', 'Craft-buyer', 'Maker-culture-drawn', 'Shop-for-craft'], domain: 'Character' },
          { id: 'food-drink', label: 'Something edible — local olive oil, wine, spices, chocolate', signals: ['Food-souvenir', 'Pantry-traveler', 'Taste-memory-keeper'], domain: 'FoodDrink' },
          { id: 'design-object', label: 'A design piece — a print, a lamp, a piece of furniture if you could ship it', signals: ['Design-collector', 'Object-driven-traveler', 'Shop-for-design'], domain: 'Design' },
          { id: 'nothing', label: 'Photos and memories — I don\'t bring stuff home', signals: ['Anti-souvenir', 'Minimalist-traveler', 'Memory-over-object'], domain: 'Core' },
        ],
      },
      {
        id: 'sh3-market-morning',
        prompt: 'Saturday morning in a European city. A friend says: "There\'s an incredible flea market 20 minutes away."',
        domains: ['Character', 'Geography'],
        options: [
          { id: 'absolutely', label: 'I\'m already getting dressed — flea markets are my thing', signals: ['Flea-market-lover', 'Treasure-hunter', 'Saturday-market-ritual', 'Browse-happy'], domain: 'Character' },
          { id: 'maybe', label: 'Depends — what kind of stuff? I\'m picky about markets', signals: ['Selective-market-goer', 'Curated-over-chaotic', 'Quality-market-filter'], domain: 'Character' },
          { id: 'café-first', label: 'I\'d go if there\'s good coffee nearby — the market is the excuse, the café is the point', signals: ['Café-first', 'Market-as-excuse', 'Coffee-destination'], domain: 'FoodDrink' },
          { id: 'pass', label: 'I\'d rather sleep in and find a good brunch spot', signals: ['Anti-market', 'Brunch-over-browsing', 'Slow-morning-priority'], domain: 'FoodDrink' },
        ],
      },
      {
        id: 'sh4-neighborhood-shops',
        prompt: 'The hotel concierge says: "The best shops in the city are in [neighborhood] — independent boutiques, a great bookshop, a local perfumer."',
        domains: ['Geography', 'Character'],
        options: [
          { id: 'spend-afternoon', label: 'That\'s my afternoon sorted — I\'ll walk the whole strip', signals: ['Shop-strip-walker', 'Independent-boutique-drawn', 'Neighborhood-browser'], domain: 'Geography' },
          { id: 'one-stop', label: 'I\'d go for the perfumer or bookshop specifically — I don\'t browse aimlessly', signals: ['Targeted-shopper', 'Specialist-shop-seeker', 'Purpose-driven-browser'], domain: 'Character' },
          { id: 'food-instead', label: 'I\'d ask about the restaurants in that neighborhood instead', signals: ['Food-over-shops', 'Restaurant-priority', 'Dining-navigator'], domain: 'FoodDrink' },
          { id: 'skip', label: 'I\'d nod politely and go to the beach', signals: ['Shop-indifferent', 'Leisure-over-browsing', 'Anti-retail'], domain: 'Wellness' },
        ],
      },
    ],
  },
  // ─── New: Trade-offs & Compromises (what they'll sacrifice — strong sorting signal) ───
  {
    id: 'trade-offs',
    phaseNumber: 25,
    title: 'Trade-offs',
    subtitle: 'What you\'ll give up — and what you won\'t',
    modality: 'scene',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 97, Atmosphere: 94, Character: 94, Service: 92, FoodDrink: 88, Setting: 92, Wellness: 82, Sustainability: 43 },
    sceneQuestions: [
      {
        id: 'bv1-value',
        prompt: 'Two hotels in the same city, same dates:',
        domains: ['Core'],
        options: [
          { id: 'value', label: '$300/night — beautiful, great reviews, slightly outside the center', signals: ['Value-conscious', 'Smart-splurge', 'Location-flexible'], domain: 'Core' },
          { id: 'splurge', label: '$800/night — extraordinary, heart of everything, once-in-a-lifetime', signals: ['Experience-over-price', 'Splurge-for-exceptional', 'Location-premium'], domain: 'Core' },
          { id: 'depends', label: 'Depends on the trip — anniversary yes, Tuesday no', signals: ['Occasion-calibrated-spender', 'Context-aware-budget'], domain: 'Core' },
          { id: 'airbnb', label: 'Neither — I\'d look for an apartment with character for $200', signals: ['Alternative-accommodation', 'Value-hacker', 'Apartment-drawn'], domain: 'Core' },
        ],
      },
      {
        id: 'dn3-tradeoff',
        prompt: 'You can only have one:',
        domains: ['Geography', 'Design'],
        options: [
          { id: 'location', label: 'Perfect location, average hotel', signals: ['Location-over-property', 'Context-first', 'Neighborhood-priority'], domain: 'Geography' },
          { id: 'hotel', label: 'Average location, extraordinary hotel', signals: ['Property-over-location', 'Destination-in-itself', 'Hotel-as-world'], domain: 'Design' },
          { id: 'neither', label: 'I\'d keep looking — I refuse to compromise on either', signals: ['Uncompromising-searcher', 'High-standards-both'], domain: 'Core' },
          { id: 'location-charm', label: 'The most interesting neighborhood, whatever the hotel', signals: ['Neighborhood-over-everything', 'Street-life-priority', 'Local-immersion-max'], domain: 'Geography' },
        ],
      },
      {
        id: 'dn2-sacrifice',
        prompt: 'Your dream hotel has everything except — which could you live without?',
        domains: ['Core'],
        options: [
          { id: 'pool', label: 'Pool — I can swim in the sea', signals: ['Pool-dispensable', 'Sea-swimmer', 'Natural-water-priority'], domain: 'Wellness' },
          { id: 'restaurant', label: 'Restaurant on site — I\'ll eat in town', signals: ['On-site-restaurant-dispensable', 'Town-diner', 'External-dining-preferred'], domain: 'FoodDrink' },
          { id: 'gym', label: 'Gym or fitness — I\'ll run outside or skip it', signals: ['Gym-dispensable', 'Outdoor-exerciser', 'Exercise-optional'], domain: 'Wellness' },
          { id: 'room-service', label: 'Room service — I\'ll get dressed and go down', signals: ['Room-service-dispensable', 'Self-sufficient-eater', 'Anti-in-room-dining'], domain: 'Service' },
        ],
      },
      {
        id: 'tr4-jetlag',
        prompt: 'You wake up at 5:30am, wide awake, jet-lagged. You:',
        domains: ['Atmosphere', 'Wellness'],
        options: [
          { id: 'dawn-walk', label: 'Go for a walk — the city at dawn is magic', signals: ['Dawn-explorer', 'Early-city-walker', 'Jet-lag-as-opportunity'], domain: 'Atmosphere' },
          { id: 'room-service', label: 'Order room service and watch the sunrise from bed', signals: ['In-room-comfort', 'Dawn-viewer', 'Room-sanctuary-morning'], domain: 'Service' },
          { id: 'gym', label: 'Find the gym or pool — burn it off', signals: ['Active-coper', 'Early-gym-user', 'Exercise-as-reset'], domain: 'Wellness' },
          { id: 'ease-in', label: 'Read, reply to emails, ease in slowly', signals: ['Slow-adjustor', 'Gradual-starter', 'Connected-traveler'], domain: 'Core' },
        ],
      },
    ],
  },
  {
    id: 'deal-breakers',
    phaseNumber: 26,
    title: 'Deal-Breakers',
    subtitle: 'The things that genuinely ruin a stay',
    modality: 'quick-choice',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 97, Atmosphere: 95, Character: 94, Service: 93, FoodDrink: 89, Setting: 93, Wellness: 83, Sustainability: 44 },
    quickChoiceMax: 3,
    quickChoiceMin: 3,
    quickChoiceOptions: [
      { id: 'noise', label: 'Noisy room — traffic, hallway, neighboring rooms', signals: ['Noise-dealbreaker', 'Acoustic-sensitive', 'Anti-noise'], domain: 'Atmosphere' },
      { id: 'bad-bed', label: 'Bad bed — too soft, too hard, wrong pillows', signals: ['Bed-dealbreaker', 'Sleep-non-negotiable'], domain: 'Wellness' },
      { id: 'rude-staff', label: 'Rude or indifferent staff', signals: ['Service-dealbreaker', 'Anti-indifference'], domain: 'Service' },
      { id: 'ugly-room', label: 'Ugly or poorly designed room', signals: ['Design-dealbreaker', 'Aesthetic-non-negotiable'], domain: 'Design' },
      { id: 'bad-food', label: 'Bad food with no good alternatives nearby', signals: ['Food-dealbreaker', 'Dining-dependent'], domain: 'FoodDrink' },
      { id: 'weak-wifi', label: 'Weak wifi', signals: ['Connectivity-dealbreaker', 'Digital-dependent'], domain: 'Core' },
      { id: 'no-light', label: 'No natural light in the room', signals: ['Light-dealbreaker', 'Natural-light-non-negotiable'], domain: 'Design' },
      { id: 'bad-location', label: 'Far from anything interesting', signals: ['Location-dealbreaker', 'Walkability-dependent'], domain: 'Geography' },
    ],
  },
  {
    id: 'consistency-check',
    phaseNumber: 27,
    title: 'Final Reads',
    subtitle: 'A few gut checks before we build your profile',
    modality: 'scene',
    act: 3,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 98, Atmosphere: 96, Character: 95, Service: 94, FoodDrink: 90, Setting: 94, Wellness: 84, Sustainability: 45 },
    sceneQuestions: [
      {
        id: 'cv1-formality',
        prompt: 'Be honest. You walk into a hotel and everyone is in linen and loafers. You\'re in sneakers and a hoodie. You feel:',
        domains: ['Service'],
        isValidator: true,
        options: [
          { id: 'underdressed', label: 'Underdressed — I should have checked the vibe', signals: ['Formality-aware', 'Dress-code-sensitive'], domain: 'Service' },
          { id: 'fine', label: 'Totally fine — I don\'t dress for hotels', signals: ['Formality-indifferent', 'Anti-dress-code'], domain: 'Service' },
          { id: 'never', label: 'I\'d never be in sneakers and a hoodie at a nice hotel', signals: ['Always-dressed', 'Self-presentation-important'], domain: 'Service' },
          { id: 'briefly', label: 'Slightly self-conscious but I\'d get over it in 5 minutes', signals: ['Mild-code-awareness', 'Adaptable-social'], domain: 'Service' },
        ],
      },
      {
        id: 'cv2-comfort',
        prompt: 'The most beautiful room you\'ve ever seen. But the bed is just okay, the shower is weak, and there\'s no blackout curtain.',
        domains: ['Design', 'Wellness'],
        isValidator: true,
        options: [
          { id: 'stay', label: 'I\'d still stay — I\'d sleep anywhere for a room like that', signals: ['Design-over-comfort-confirmed', 'Aesthetic-priority'], domain: 'Design' },
          { id: 'comfort', label: 'Beautiful doesn\'t matter if I can\'t sleep', signals: ['Comfort-non-negotiable', 'Functional-first'], domain: 'Wellness' },
        ],
      },
      {
        id: 'cv3-crowds',
        prompt: 'Dream hotel, dream location. But it\'s peak season — fully booked, pool is packed, restaurant needs reservations 3 days ahead.',
        domains: ['Atmosphere'],
        isValidator: true,
        options: [
          { id: 'fine', label: 'Fine — popular for a reason, I can handle crowds', signals: ['Peak-season-tolerant', 'Experience-over-crowds'], domain: 'Atmosphere' },
          { id: 'off-season', label: 'I\'d rather go off-season, even if the weather is worse', signals: ['Off-season-seeker', 'Crowd-averse', 'Solitude-premium'], domain: 'Atmosphere' },
        ],
      },
      {
        id: 'cv4-recommendation',
        prompt: 'A close friend raves about a hotel. You look it up and it\'s not your style at all. You:',
        domains: ['Core'],
        isValidator: true,
        options: [
          { id: 'book', label: 'Book it anyway — I trust them more than photos', signals: ['Trust-over-aesthetics', 'Open-minded-traveler'], domain: 'Core' },
          { id: 'investigate', label: 'Ask them what specifically they loved — maybe I\'m missing something', signals: ['Curious-investigator', 'Detail-seeker'], domain: 'Core' },
          { id: 'skip', label: 'Skip it — I know what I like', signals: ['Confident-self-knower', 'Rigid-taste'], domain: 'Core' },
          { id: 'bookmark', label: 'Bookmark it for a different kind of trip', signals: ['Context-flexible', 'Trip-type-aware'], domain: 'Core' },
        ],
      },
    ],
  },
  {
    id: 'gap-fill-reactions',
    phaseNumber: 28,
    title: 'Places You Know',
    subtitle: 'Rate places from your recent travels',
    modality: 'property-reactions',
    act: 3,
    isAdaptive: true,
    aiPrompt: '',
    followUps: [],
    sampleUserResponses: [],
    extractedSignals: [],
    certaintyAfter: { Design: 98, Atmosphere: 96, Character: 96, Service: 95, FoodDrink: 91, Setting: 95, Wellness: 85, Sustainability: 46 },
    cardCount: 12,
    propertySource: 'email', // Pull from parsed email history (past hotels & restaurants)
    // targetDomains set at runtime from Act 1 gap analysis
  },
];

export const MAX_ADAPTIVE_PHASES = 3;
