'use client';

import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

import PageTransition from '@/components/PageTransition';
import { SafeFadeIn } from '@/components/animations/SafeFadeIn';
import { SafeMotionDiv, SafeMotionSpan, SafeMotionButton, SafeMotionH2, SafeMotionP } from '@/components/animations/AnimatedElements';
import TabBar from '@/components/TabBar';
import DesktopNav from '@/components/DesktopNav';
import ProfileDeepDive from '@/components/profile/ProfileDeepDive';
import ExpandMosaicView from '@/components/profile/ExpandMosaicView';
import WrappedExperience from '@/components/wrapped/WrappedExperience';
import { TerrazzoMosaic } from '@/components/TerrazzoMosaic';
import TasteStone from '@/components/profile/TasteStone';
import ScoreArc from '@/components/profile/ScoreArc';
import { TASTE_PROFILE, DIMENSION_COLORS } from '@/constants/profile';
import type { TasteProfile as NumericProfile, ImportedPlace, PlaceRating } from '@/types';
import { PerriandIcon } from '@/components/icons/PerriandIcons';
import { useOnboardingStore } from '@/stores/onboardingStore';
import { useIsDesktop } from '@/hooks/useBreakpoint';
import PlacePhoto from '@/components/PlacePhoto';
import {
  BECAUSE_YOU_CARDS,
  WEEKLY_COLLECTION,
  STRETCH_PICK,
  SUMMER_RECS,
  FRIEND_SAVES,
  EDITORIAL_LETTER,
  SIGNAL_THREAD,
  TASTE_TENSION,
  MOOD_BOARDS,
  DEEP_MATCH,
  type BecauseYouCard,
  type CollectionPlace,
  type FriendSave,
  type ContextRec,
  type EditorialLetter,
  type SignalThread,
  type TasteTension,
  type MoodBoard,
  type DeepMatch,
} from '@/constants/discover';
import { getPlaceImage } from '@/constants/placeImages';
import { FONT, INK } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { apiFetch } from '@/lib/api-client';
import PlaceLink from '@/components/PlaceLink';
import { PlaceDetailProvider } from '@/context/PlaceDetailContext';
import { useSavedStore } from '@/stores/savedStore';

// Discover content generated by Claude AI
interface DiscoverContent {
  editorialLetter?: EditorialLetter;
  becauseYouCards?: BecauseYouCard[];
  signalThread?: SignalThread;
  tasteTension?: TasteTension;
  weeklyCollection?: { title: string; subtitle: string; places: CollectionPlace[] };
  moodBoards?: MoodBoard[];
  deepMatch?: DeepMatch;
  stretchPick?: typeof STRETCH_PICK;
  contextRecs?: ContextRec[];
  contextLabel?: string;
}

/**
 * Collect all place names from the initial feed + any extra pages so the
 * continuation API can avoid recommending duplicates.
 */
function collectAllPlaceNames(
  initial: DiscoverContent | null,
  extras: DiscoverContent[],
): string[] {
  const names = new Set<string>();
  function addFrom(content: DiscoverContent | null) {
    if (!content) return;
    for (const c of content.becauseYouCards || []) if (c.place) names.add(c.place);
    for (const p of content.signalThread?.places || []) if (p.name) names.add(p.name);
    if (content.tasteTension?.resolvedBy?.name) names.add(content.tasteTension.resolvedBy.name);
    for (const p of content.weeklyCollection?.places || []) if (p.name) names.add(p.name);
    for (const b of content.moodBoards || []) {
      for (const p of b.places || []) if (p.name) names.add(p.name);
    }
    if (content.deepMatch?.name) names.add(content.deepMatch.name);
    if (content.stretchPick?.name) names.add(content.stretchPick.name);
    for (const r of content.contextRecs || []) if (r.name) names.add(r.name);
  }
  addFrom(initial);
  for (const page of extras) addFrom(page);
  return Array.from(names);
}

const SETTINGS_LINKS = [
  { label: 'Connected Accounts', action: 'accounts' },
  { label: 'Import History', action: 'history' },
  { label: 'Notification Preferences', action: 'notifications' },
  { label: 'About Terrazzo', action: 'about' },
];

function getGreeting() {
  const hour = new Date().getHours();
  if (hour < 12) return 'Good morning';
  if (hour < 17) return 'Good afternoon';
  return 'Good evening';
}

type ProfileTab = 'discover' | 'profile';

export default function ProfilePage() {
  const ratePlace = useSavedStore(s => s.ratePlace);

  const handleSavePreview = useCallback(async (place: ImportedPlace) => {
    // Save to library via API — PlaceDetailContext will close the preview state
    try {
      const googlePlaceId = (place.google as Record<string, unknown> & { placeId?: string })?.placeId;
      if (!googlePlaceId) return;
      await apiFetch('/api/places/save', {
        method: 'POST',
        body: JSON.stringify({
          googlePlaceId,
          name: place.name,
          type: place.type,
          location: place.location,
          source: { type: 'url', name: 'Discover Feed' },
        }),
      });
    } catch (err) {
      console.error('Failed to save discover place:', err);
    }
  }, []);

  return (
    <PlaceDetailProvider config={{
      onRate: (place, rating) => {
        ratePlace(place.id, rating);
      },
      onSavePreview: handleSavePreview,
    }}>
      <ProfilePageContent />
    </PlaceDetailProvider>
  );
}

function ProfilePageContent() {

  const router = useRouter();
  const isDesktop = useIsDesktop();
  const [showWrapped, setShowWrapped] = useState(false);
  const [showMosaic, setShowMosaic] = useState(false);
  const [expandedSection, setExpandedSection] = useState<string | null>(null);
  const [activeTab, setActiveTabRaw] = useState<ProfileTab>(() => {
    if (typeof window !== 'undefined') {
      return (sessionStorage.getItem('profile_active_tab') as ProfileTab) || 'discover';
    }
    return 'discover';
  });
  const setActiveTab = useCallback((tab: ProfileTab) => {
    setActiveTabRaw(tab);
    sessionStorage.setItem('profile_active_tab', tab);
  }, []);
  const [discoverContent, setDiscoverContent] = useState<DiscoverContent | null>(null);
  const [isLoadingDiscover, setIsLoadingDiscover] = useState(false);
  const [isResynthesizing, setIsResynthesizing] = useState(false);

  // Infinite scroll: extra feed pages loaded on demand
  const [extraPages, setExtraPages] = useState<DiscoverContent[]>([]);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const [feedPageIndex, setFeedPageIndex] = useState(1);
  const [hasMoreContent, setHasMoreContent] = useState(true);
  const sentinelRef = useRef<HTMLDivElement | null>(null);

  const [resynthesisResult, setResynthesisResult] = useState<'success' | 'error' | null>(null);

  // ── Email / Connected Accounts state ─────────────────────────────────────
  const [emailStatus, setEmailStatus] = useState<{
    connected: boolean;
    email?: string;
    provider?: string;
    connectedAt?: string;
  } | null>(null);
  const [emailLoading, setEmailLoading] = useState(false);
  const [scanState, setScanState] = useState<'idle' | 'scanning' | 'parsing' | 'done' | 'failed'>('idle');
  const [scanResult, setScanResult] = useState<{
    emailsFound: number;
    scanId: string;
    emailsParsed?: number;
    reservationsFound?: number;
  } | null>(null);
  const [importHistory, setImportHistory] = useState<Array<{
    id: string;
    type: 'email-scan' | 'url-import' | 'manual';
    date: string;
    title: string;
    subtitle: string;
    count: number;
    status?: string;
    scanId?: string;
  }>>([]);
  const [historyLoading, setHistoryLoading] = useState(false);

  const { isAuthenticated, user, signOut } = useAuth();
  const resetForRedo = useOnboardingStore(s => s.resetForRedo);
  const triggerResynthesis = useOnboardingStore(s => s.triggerResynthesis);
  const generatedProfile = useOnboardingStore(s => s.generatedProfile);
  const lifeContext = useOnboardingStore(s => s.lifeContext);
  const allSignals = useOnboardingStore(s => s.allSignals);
  const dbHydrated = useOnboardingStore(s => s.dbHydrated);

  // Debug: log every state change that could trigger a re-render
  const prevDbHydrated = useRef(dbHydrated);
  const prevActiveTab = useRef(activeTab);
  const prevDiscoverContent = useRef(discoverContent);
  useEffect(() => {
    if (prevDbHydrated.current !== dbHydrated) {
      console.log(`%c[PAGE ProfilePage] 💧 dbHydrated: ${prevDbHydrated.current} → ${dbHydrated} @ ${performance.now().toFixed(1)}ms`, 'color: #FF6F00; font-weight: bold; font-size: 13px');
      prevDbHydrated.current = dbHydrated;
    }
  }, [dbHydrated]);
  useEffect(() => {
    if (prevActiveTab.current !== activeTab) {
      console.log(`%c[PAGE ProfilePage] 🔄 activeTab: ${prevActiveTab.current} → ${activeTab} @ ${performance.now().toFixed(1)}ms`, 'color: #FF6F00; font-weight: bold');
      prevActiveTab.current = activeTab;
    }
  }, [activeTab]);
  useEffect(() => {
    const had = prevDiscoverContent.current !== null;
    const has = discoverContent !== null;
    if (had !== has) {
      console.log(`%c[PAGE ProfilePage] 📡 discoverContent: ${had ? 'loaded' : 'null'} → ${has ? 'loaded' : 'null'} @ ${performance.now().toFixed(1)}ms`, 'color: #FF6F00; font-weight: bold');
      prevDiscoverContent.current = discoverContent;
    }
  }, [discoverContent]);

  // Restore scroll position after back-navigation from a place detail page
  useEffect(() => {
    const savedY = sessionStorage.getItem('profile_scroll_y');
    if (savedY) {
      sessionStorage.removeItem('profile_scroll_y');
      // Delay to let content render before scrolling
      requestAnimationFrame(() => {
        window.scrollTo(0, parseInt(savedY, 10));
      });
    }
  }, []);

  // DB is the source of truth — show loading until hydration completes,
  // then use the real profile (no hardcoded demo fallback for auth users)
  const profile = generatedProfile || TASTE_PROFILE;
  const userName = lifeContext?.firstName || 'Greg';
  const signalCount = allSignals?.length || 238;

  // Build numeric profile for mosaic visualization from radar data
  const numericProfile: NumericProfile = useMemo(() => {
    const radarMap: Record<string, string> = {
      Sensory: 'Atmosphere', Material: 'Design',
      Authenticity: 'Character', Social: 'Service',
      Cultural: 'Character', Spatial: 'Setting',
      Rhythm: 'Atmosphere', Ethics: 'Sustainability',
    };
    const result: NumericProfile = { Design: 0.5, Atmosphere: 0.5, Character: 0.5, Service: 0.5, FoodDrink: 0.5, Setting: 0.5, Wellness: 0.5, Sustainability: 0.5 };
    const radarData = (profile as { radarData?: { axis: string; value: number }[] }).radarData;
    if (radarData) {
      for (const r of radarData) {
        const domain = radarMap[r.axis];
        if (domain && domain in result) {
          result[domain as keyof NumericProfile] = Math.max(result[domain as keyof NumericProfile], r.value);
        }
      }
    }
    return result;
  }, [profile]);

  // Generate discover content from real profile
  const fetchDiscoverContent = useCallback(async () => {
    if (!generatedProfile) return;

    // Check localStorage cache
    const cacheKey = `terrazzo_discover_${generatedProfile.overallArchetype}`;
    try {
      const cached = localStorage.getItem(cacheKey);
      if (cached) {
        setDiscoverContent(JSON.parse(cached));
        return;
      }
    } catch { /* ignore cache errors */ }

    setIsLoadingDiscover(true);
    try {
      const data = await apiFetch<DiscoverContent>('/api/profile/discover', {
        method: 'POST',
        body: JSON.stringify({
          userProfile: generatedProfile,
          lifeContext: lifeContext || undefined,
        }),
      });
      setDiscoverContent(data);
      try { localStorage.setItem(cacheKey, JSON.stringify(data)); } catch { /* quota exceeded */ }
    } catch {
      // Silently fall back to hardcoded content
    } finally {
      setIsLoadingDiscover(false);
    }
  }, [generatedProfile, lifeContext]);

  useEffect(() => {
    fetchDiscoverContent();
  }, [fetchDiscoverContent]);

  // ─── Infinite scroll: fetch additional feed pages on demand ───

  // Reset when base content changes (e.g. profile resynthesis)
  useEffect(() => {
    setExtraPages([]);
    setFeedPageIndex(1);
    setHasMoreContent(true);
  }, [discoverContent]);

  const fetchMoreContent = useCallback(async () => {
    // Need either a real profile or at least existing discover content to continue from
    const userProfile = generatedProfile || (discoverContent ? profile : null);
    if (!userProfile || isLoadingMore || !hasMoreContent) return;

    setIsLoadingMore(true);
    try {
      const data = await apiFetch<DiscoverContent>('/api/profile/discover/more', {
        method: 'POST',
        body: JSON.stringify({
          userProfile,
          lifeContext: lifeContext || undefined,
          pageIndex: feedPageIndex,
          excludePlaces: collectAllPlaceNames(discoverContent, extraPages),
        }),
      });
      setExtraPages(prev => [...prev, data]);
      setFeedPageIndex(prev => prev + 1);
      if (feedPageIndex >= 5) setHasMoreContent(false);
    } catch {
      setHasMoreContent(false);
    } finally {
      setIsLoadingMore(false);
    }
  }, [generatedProfile, profile, discoverContent, lifeContext, isLoadingMore, hasMoreContent, feedPageIndex, extraPages]);

  // IntersectionObserver triggers fetchMoreContent when user scrolls near feed bottom
  useEffect(() => {
    const sentinel = sentinelRef.current;
    if (!sentinel) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) {
          fetchMoreContent();
        }
      },
      { rootMargin: '600px' }
    );

    observer.observe(sentinel);
    return () => observer.disconnect();
  }, [fetchMoreContent]);

  const handleSettingTap = (action: string) => {
    const next = expandedSection === action ? null : action;
    setExpandedSection(next);
    // Fetch email status when accounts panel opens
    if (next === 'accounts' && !emailStatus) fetchEmailStatus();
    // Fetch import history when history panel opens
    if (next === 'history' && importHistory.length === 0) fetchImportHistory();
  };

  const fetchEmailStatus = async () => {
    setEmailLoading(true);
    try {
      const data = await apiFetch<{ connected: boolean; email?: string; provider?: string; connectedAt?: string }>('/api/email/status');
      setEmailStatus(data);
      // If connected and we don't already have scan state, check for latest scan
      if (data.connected && scanState === 'idle') {
        restoreLatestScan();
      }
    } catch { setEmailStatus({ connected: false }); }
    finally { setEmailLoading(false); }
  };

  // Restore state from the most recent scan (so the "Review" button persists across navigation)
  const restoreLatestScan = async () => {
    try {
      const data = await apiFetch<{
        scans: Array<{
          id: string;
          status: string;
          emailsFound: number;
          emailsParsed: number;
          reservationsFound: number;
        }>;
      }>('/api/email/scan');
      const latest = data.scans?.[0];
      if (!latest) return;

      setScanResult({
        scanId: latest.id,
        emailsFound: latest.emailsFound,
        emailsParsed: latest.emailsParsed,
        reservationsFound: latest.reservationsFound,
      });

      if (latest.status === 'parsing' || latest.status === 'scanning') {
        // Still running — resume polling
        setScanState('parsing');
        pollScanProgress(latest.id, latest.emailsFound);
      } else if (latest.status === 'completed') {
        setScanState('done');
      } else if (latest.status === 'failed') {
        setScanState('failed');
      }
    } catch {
      // No scan history — that's fine
    }
  };

  const handleDisconnect = async () => {
    try {
      await apiFetch('/api/auth/nylas/disconnect', { method: 'POST' });
      setEmailStatus({ connected: false });
      setScanState('idle');
      setScanResult(null);
    } catch (err) { console.error('Disconnect failed:', err); }
  };

  // Poll a scan for progress until it completes or fails
  const pollScanProgress = useCallback(async (scanId: string, emailsFound: number) => {
    const POLL_INTERVAL = 3000;

    const poll = async () => {
      try {
        const status = await apiFetch<{
          scanId: string;
          status: string;
          emailsFound: number;
          emailsParsed: number;
          reservationsFound: number;
          errorMessage: string | null;
        }>(`/api/email/scan/${scanId}`);

        setScanResult({
          emailsFound: status.emailsFound,
          scanId: status.scanId,
          emailsParsed: status.emailsParsed,
          reservationsFound: status.reservationsFound,
        });

        if (status.status === 'completed') {
          setScanState('done');
          console.log(`[terrazzo] Scan complete: ${status.emailsParsed} parsed → ${status.reservationsFound} reservations`);
          return; // stop polling
        } else if (status.status === 'failed') {
          setScanState('failed');
          console.error('[terrazzo] Scan failed:', status.errorMessage);
          return; // stop polling
        }

        // Still running — poll again
        setScanState('parsing');
        setTimeout(poll, POLL_INTERVAL);
      } catch (err) {
        console.error('[terrazzo] Poll failed:', err);
        // Keep polling on transient errors
        setTimeout(poll, POLL_INTERVAL * 2);
      }
    };

    // Start polling after a short initial delay
    setTimeout(poll, 2000);
  }, []);

  const handleScanNow = async () => {
    setScanState('scanning');
    setScanResult(null);
    try {
      // Fire the scan — server will search emails then parse in the background
      const data = await apiFetch<{
        scanId: string;
        status: string;
        emailsFound: number;
        queriesRun: number;
      }>('/api/email/scan', {
        method: 'POST',
        body: JSON.stringify({ scanType: 'full' }),
      });

      console.log('[terrazzo] Scan kicked off:', data.emailsFound, 'emails found');
      setScanResult({ emailsFound: data.emailsFound, scanId: data.scanId });

      if (data.emailsFound === 0) {
        setScanState('done');
        return;
      }

      // Start polling for background parse progress
      setScanState('parsing');
      pollScanProgress(data.scanId, data.emailsFound);
    } catch (err) {
      console.error('[terrazzo] Email scan failed:', err);
      setScanState('idle');
    }
  };

  const handleDebugEmail = async () => {
    try {
      const data = await apiFetch<Record<string, unknown>>('/api/email/debug');
      console.log('[terrazzo] EMAIL DEBUG:', JSON.stringify(data, null, 2));
      alert(`Debug result — check console.\nRecent emails: ${JSON.stringify((data.tests as Record<string, unknown> & { recentMessages: { count: number } })?.recentMessages?.count ?? 'error')}`);
    } catch (err) {
      console.error('[terrazzo] Debug failed:', err);
      alert('Debug failed — check console');
    }
  };

  const fetchImportHistory = async () => {
    setHistoryLoading(true);
    try {
      const data = await apiFetch<{ timeline: Array<{ id: string; type: 'email-scan' | 'url-import' | 'manual'; date: string; title: string; subtitle: string; count: number; status?: string; scanId?: string }> }>('/api/import-history');
      setImportHistory(data.timeline || []);
    } catch { /* ignore */ }
    finally { setHistoryLoading(false); }
  };

  const handleResynthesis = async () => {
    setIsResynthesizing(true);
    setResynthesisResult(null);
    const ok = await triggerResynthesis();
    setIsResynthesizing(false);
    setResynthesisResult(ok ? 'success' : 'error');
    // Clear the discover cache so it regenerates with new profile
    if (ok) {
      try {
        const keys = Object.keys(localStorage).filter(k => k.startsWith('terrazzo_discover_'));
        keys.forEach(k => localStorage.removeItem(k));
      } catch { /* ignore */ }
      // Re-fetch discover content
      fetchDiscoverContent();
    }
    // Auto-clear the result badge after 4s
    setTimeout(() => setResynthesisResult(null), 4000);
  };

  const handleRedoOnboarding = () => {
    resetForRedo();
    router.push('/onboarding');
  };

  // Wait for DB hydration before rendering profile data
  if (!dbHydrated) {
    return (
      <div className="min-h-dvh flex items-center justify-center" style={{ background: 'var(--t-cream)' }}>
        <div className="animate-pulse text-[13px]" style={{ color: INK['85'] }}>Loading your profile…</div>
      </div>
    );
  }

  // Full-screen overlays
  if (showWrapped) {
    return <WrappedExperience onClose={() => setShowWrapped(false)} />;
  }
  if (showMosaic) {
    return <ExpandMosaicView onClose={() => setShowMosaic(false)} />;
  }

  /* ─── Shared header + tab component ─── */
  const headerBlock = (
    <>
      <div className="flex items-start justify-between mb-5">
        <div className="flex items-center gap-3">
          <div
            className="w-12 h-12 rounded-full flex items-center justify-center"
            style={{ background: 'rgba(200,146,58,0.1)' }}
          >
            <PerriandIcon name="profile" size={24} color="var(--t-honey)" />
          </div>
          <div>
            <div className="text-[15px] font-semibold" style={{ color: 'var(--t-ink)' }}>{userName}</div>
            <div className="text-[11px]" style={{ color: INK['90'] }}>{profile.overallArchetype}</div>
          </div>
        </div>
        <TerrazzoMosaic profile={numericProfile} size="xs" />
      </div>

      {/* Inner tab toggle */}
      <div
        className="flex gap-1 p-0.5 rounded-lg mb-1"
        style={{ background: 'var(--t-linen)' }}
      >
        {(['discover', 'profile'] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className="flex-1 py-1.5 px-2 rounded-md text-[11px] font-medium transition-all"
            style={{
              background: activeTab === tab ? 'white' : 'transparent',
              color: activeTab === tab ? 'var(--t-ink)' : INK['85'],
              border: 'none',
              cursor: 'pointer',
              fontFamily: FONT.sans,
              boxShadow: activeTab === tab ? '0 1px 3px rgba(0,0,0,0.06)' : 'none',
            }}
          >
            {tab === 'discover' ? 'Discover' : 'My Profile'}
          </button>
        ))}
      </div>
    </>
  );

  const discoverFeed = (
    <>
      {/* Initial feed — all sections visible */}
      <EditorialLetterSection letter={discoverContent?.editorialLetter} />
      <BecauseYouSection cards={discoverContent?.becauseYouCards} />
      <SignalThreadSection thread={discoverContent?.signalThread} />
      <TasteTensionSection tension={discoverContent?.tasteTension} />
      <WeeklyEditSection collection={discoverContent?.weeklyCollection} />
      <MoodBoardSection boards={discoverContent?.moodBoards} />
      <DeepMatchSection match={discoverContent?.deepMatch} />
      <StretchPickSection stretch={discoverContent?.stretchPick} />
      <ContextModeSection recs={discoverContent?.contextRecs} contextLabel={discoverContent?.contextLabel} />
      <VocabTeaser profile={profile} />
      <FriendsSavingSection />

      {/* Extra pages loaded via infinite scroll */}
      {extraPages.map((page, i) => (
        <div key={`extra-page-${i}`}>
          {/* Subtle divider between pages */}
          <div className="flex items-center gap-4 my-10 px-4">
            <div className="flex-1 h-px" style={{ background: 'var(--t-linen)' }} />
            <span style={{ fontFamily: FONT.mono, fontSize: 9, color: INK['60'], textTransform: 'uppercase', letterSpacing: '0.15em' }}>
              More for you
            </span>
            <div className="flex-1 h-px" style={{ background: 'var(--t-linen)' }} />
          </div>

          {/* Render whichever sections this page contains */}
          {page.editorialLetter && <EditorialLetterSection letter={page.editorialLetter} />}
          {page.becauseYouCards && <BecauseYouSection cards={page.becauseYouCards} />}
          {page.signalThread && <SignalThreadSection thread={page.signalThread} />}
          {page.tasteTension && <TasteTensionSection tension={page.tasteTension} />}
          {page.weeklyCollection && <WeeklyEditSection collection={page.weeklyCollection} />}
          {page.moodBoards && <MoodBoardSection boards={page.moodBoards} />}
          {page.deepMatch && <DeepMatchSection match={page.deepMatch} />}
          {page.stretchPick && <StretchPickSection stretch={page.stretchPick} />}
          {page.contextRecs && <ContextModeSection recs={page.contextRecs} contextLabel={page.contextLabel} />}
        </div>
      ))}

      {/* Sentinel + loading indicator for infinite scroll */}
      {hasMoreContent && (
        <div
          ref={sentinelRef}
          className="flex flex-col items-center justify-center py-10 gap-2"
          style={{ minHeight: 80 }}
        >
          {isLoadingMore ? (
            <>
              <div className="animate-spin w-5 h-5 rounded-full border-2" style={{ borderColor: 'var(--t-linen)', borderTopColor: 'var(--t-honey)' }} />
              <span style={{ fontFamily: FONT.mono, fontSize: 10, color: INK['60'], letterSpacing: '0.05em' }}>
                Curating more…
              </span>
            </>
          ) : (
            <span
              className="animate-pulse"
              style={{ fontFamily: FONT.mono, fontSize: 10, color: INK['60'], letterSpacing: '0.05em' }}
            >
              Scroll for more
            </span>
          )}
        </div>
      )}
    </>
  );

  /* ─── Desktop Profile layout ─── */
  if (isDesktop) {
    return (
      <PageTransition className="min-h-screen" style={{ background: 'var(--t-cream)' }}>
        <DesktopNav />
        <div style={{ maxWidth: 1400, margin: '0 auto', padding: '36px 48px 48px' }}>
          <div className="flex gap-10">
            {/* Left: profile card (sticky) */}
            <div className="flex-shrink-0" style={{ width: 300 }}>
              <div
                className="rounded-2xl p-6 sticky"
                style={{
                  top: 88, /* 56 nav + 32 padding */
                  background: 'white',
                  border: '1px solid var(--t-linen)',
                  boxShadow: '0 2px 8px rgba(0,0,0,0.03)',
                }}
              >
                {headerBlock}

                {/* Quick stats — 3-col grid */}
                <div
                  className="grid grid-cols-3 gap-3 mt-5 pt-5"
                  style={{ borderTop: '1px solid var(--t-linen)' }}
                >
                  <div className="text-center">
                    <div style={{ fontFamily: FONT.mono, fontSize: 20, fontWeight: 700, color: 'var(--t-ink)' }}>{signalCount}</div>
                    <div style={{ fontFamily: FONT.mono, fontSize: 9, color: INK['60'], textTransform: 'uppercase', letterSpacing: '0.1em' }}>Signals</div>
                  </div>
                  <div className="text-center">
                    <div style={{ fontFamily: FONT.mono, fontSize: 20, fontWeight: 700, color: 'var(--t-ink)' }}>{profile.contradictions?.length || 3}</div>
                    <div style={{ fontFamily: FONT.mono, fontSize: 9, color: INK['60'], textTransform: 'uppercase', letterSpacing: '0.1em' }}>Tensions</div>
                  </div>
                  <div className="text-center">
                    <div style={{ fontFamily: FONT.mono, fontSize: 20, fontWeight: 700, color: 'var(--t-ink)' }}>{Object.values(profile.microTasteSignals || {}).flat().length || 35}</div>
                    <div style={{ fontFamily: FONT.mono, fontSize: 9, color: INK['60'], textTransform: 'uppercase', letterSpacing: '0.1em' }}>Terms</div>
                  </div>
                </div>

                {/* Wrapped CTA */}
                <SafeMotionButton
                  onClick={() => setShowWrapped(true)}
                  className="w-full flex items-center justify-between p-3 rounded-xl mt-4 cursor-pointer border-none transition-all hover:opacity-90"
                  style={{ background: '#2d3a2d' }}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <span className="text-[11px] font-semibold" style={{ color: '#f5f5f0', fontFamily: FONT.sans }}>
                    Your Taste Dossier
                  </span>
                  <span className="text-[10px] px-2 py-1 rounded-full" style={{ background: 'rgba(245,245,240,0.12)', color: '#f5f5f0', fontFamily: FONT.mono }}>
                    Replay →
                  </span>
                </SafeMotionButton>

                {/* Expand Your Mosaic CTA */}
                <SafeMotionButton
                  onClick={() => setShowMosaic(true)}
                  className="w-full flex items-center justify-between p-3 rounded-xl mt-3 cursor-pointer border-none transition-all hover:opacity-90"
                  style={{ background: 'linear-gradient(135deg, #e8dcc8 0%, #f5f0e6 100%)', border: '1px solid rgba(200,146,58,0.12)' }}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <div>
                    <span className="text-[11px] font-semibold block" style={{ color: 'var(--t-ink)', fontFamily: FONT.sans }}>
                      Expand Your Mosaic
                    </span>
                    <span className="text-[9px]" style={{ color: INK['50'], fontFamily: FONT.mono }}>
                      Sharpen your matches
                    </span>
                  </div>
                  <span className="text-[10px] px-2 py-1 rounded-full" style={{ background: 'rgba(28,26,23,0.06)', color: 'var(--t-ink)', fontFamily: FONT.mono }}>
                    Play →
                  </span>
                </SafeMotionButton>

                {/* Settings links */}
                <div className="mt-5 pt-4" style={{ borderTop: '1px solid var(--t-linen)' }}>
                  {SETTINGS_LINKS.map(({ label, action }) => (
                    <div key={action}>
                      <div
                        onClick={() => handleSettingTap(action)}
                        className="flex items-center justify-between py-2.5 px-2 -mx-2 rounded-lg cursor-pointer nav-hover"
                        style={{ fontSize: 12, color: expandedSection === action ? 'var(--t-ink)' : INK['60'], fontFamily: FONT.sans }}
                      >
                        <span>{label}</span>
                        <span style={{ color: INK['30'], transform: expandedSection === action ? 'rotate(90deg)' : 'none', transition: 'transform 0.2s', display: 'inline-block' }}>→</span>
                      </div>
                      {expandedSection === 'accounts' && action === 'accounts' && (
                        <div className="px-2 py-2.5 mt-1 rounded-lg" style={{ background: 'rgba(107,139,154,0.05)', fontSize: 11 }}>
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <PerriandIcon name="email" size={11} color="var(--t-ink)" />
                              <span style={{ color: 'var(--t-ink)' }}>Gmail</span>
                            </div>
                            {emailLoading ? (
                              <span className="text-[10px]" style={{ color: INK['40'] }}>Checking…</span>
                            ) : emailStatus?.connected ? (
                              <span className="text-[10px] px-2 py-0.5 rounded-full" style={{ background: 'rgba(42,122,86,0.08)', color: 'var(--t-verde)' }}>Connected</span>
                            ) : (
                              <a href="/api/auth/nylas/connect" className="text-[10px] font-semibold px-2 py-0.5 rounded-full" style={{ background: 'var(--t-verde)', color: 'white', textDecoration: 'none' }}>Connect</a>
                            )}
                          </div>
                          {emailStatus?.connected && (
                            <div className="ml-5 mb-2">
                              <span className="text-[10px] block mb-2" style={{ color: INK['50'] }}>{emailStatus.email}</span>
                              <div className="flex items-center gap-2 flex-wrap mb-2">
                                <button onClick={handleScanNow} disabled={scanState === 'scanning' || scanState === 'parsing'} className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer" style={{ background: '#2a7a56', color: 'white', opacity: scanState === 'scanning' || scanState === 'parsing' ? 0.7 : 1 }}>
                                  {scanState === 'scanning' ? 'Scanning…' : scanState === 'parsing' ? `Parsing${scanResult?.emailsParsed ? ` ${scanResult.emailsParsed}/${scanResult.emailsFound}` : '…'}` : scanState === 'done' ? '✓ Done' : scanState === 'failed' ? 'Retry Scan' : 'Scan Inbox'}
                                </button>
                                <button onClick={handleDebugEmail} className="text-[10px] px-2 py-1 rounded-full border-none cursor-pointer" style={{ background: 'rgba(0,0,0,0.06)', color: INK['60'] }}>
                                  Debug
                                </button>
                                {scanState === 'parsing' && scanResult && (scanResult.reservationsFound ?? 0) > 0 && (
                                  <button onClick={() => router.push('/email/inbox')} className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer" style={{ background: 'var(--t-honey)', color: 'white' }}>
                                    Review {scanResult.reservationsFound} so far →
                                  </button>
                                )}
                                {scanState === 'done' && scanResult && (scanResult.reservationsFound ?? 0) > 0 && (
                                  <button onClick={() => router.push('/email/inbox')} className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer" style={{ background: 'var(--t-honey)', color: 'white' }}>
                                    Review {scanResult.reservationsFound} reservations →
                                  </button>
                                )}
                                {scanState === 'done' && scanResult && (scanResult.reservationsFound ?? 0) === 0 && (
                                  <span className="text-[10px]" style={{ color: INK['40'] }}>
                                    {scanResult.emailsFound} emails scanned · no reservations found
                                  </span>
                                )}
                              </div>
                              <button onClick={handleDisconnect} className="text-[9px] px-2 py-0.5 rounded-full border-none cursor-pointer" style={{ background: 'rgba(196,80,32,0.08)', color: '#c45020' }}>Disconnect</button>
                            </div>
                          )}
                          <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                              <PerriandIcon name="pin" size={11} color="var(--t-ink)" />
                              <span style={{ color: 'var(--t-ink)' }}>Google Maps</span>
                            </div>
                            <span className="text-[10px] px-2 py-0.5 rounded-full" style={{ background: 'rgba(42,122,86,0.08)', color: 'var(--t-verde)' }}>Via import</span>
                          </div>
                        </div>
                      )}
                      {expandedSection === 'history' && action === 'history' && (
                        <div className="px-2 py-2.5 mt-1 rounded-lg" style={{ background: 'rgba(107,139,154,0.05)', fontSize: 11 }}>
                          {historyLoading ? (
                            <span className="text-[10px]" style={{ color: INK['40'] }}>Loading history…</span>
                          ) : importHistory.length === 0 ? (
                            <span className="text-[10px]" style={{ color: INK['40'] }}>No import history yet. Connect Gmail or import from a URL to get started.</span>
                          ) : (
                            <div className="flex flex-col gap-1.5">
                              {importHistory.slice(0, 10).map((item) => (
                                <div key={item.id} className="flex items-center justify-between py-1 cursor-pointer" onClick={() => item.scanId ? router.push('/email/inbox') : undefined}>
                                  <div className="flex items-center gap-2 min-w-0">
                                    <PerriandIcon name={item.type === 'email-scan' ? 'email' : item.type === 'url-import' ? 'article' : 'manual'} size={9} color={INK['50']} />
                                    <span className="text-[10px] truncate" style={{ color: 'var(--t-ink)' }}>{item.title}</span>
                                  </div>
                                  <span className="text-[9px] flex-shrink-0 ml-2" style={{ color: INK['30'] }}>{new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>
                                </div>
                              ))}
                              <button onClick={() => router.push('/email/inbox')} className="text-[10px] font-medium mt-1 bg-transparent border-none cursor-pointer text-left" style={{ color: 'var(--t-honey)' }}>View email reservations →</button>
                            </div>
                          )}
                        </div>
                      )}
                      {expandedSection === 'notifications' && action === 'notifications' && (
                        <div className="px-2 py-2.5 mt-1 rounded-lg text-[10px]" style={{ background: 'rgba(107,139,154,0.05)', color: INK['50'] }}>Notification preferences coming soon.</div>
                      )}
                      {expandedSection === 'about' && action === 'about' && (
                        <div className="px-2 py-2.5 mt-1 rounded-lg text-[10px]" style={{ background: 'rgba(107,139,154,0.05)', color: INK['50'] }}>Terrazzo v0.1 — Your taste-driven travel companion.</div>
                      )}
                    </div>
                  ))}
                  <button
                    onClick={handleRedoOnboarding}
                    className="flex items-center gap-1.5 mt-2 py-2 bg-transparent border-none cursor-pointer"
                    style={{ fontSize: 11, color: '#c45020', fontFamily: FONT.sans }}
                  >
                    <PerriandIcon name="discover" size={10} color="#c45020" />
                    Redo Onboarding
                  </button>
                  <button
                    onClick={handleResynthesis}
                    disabled={isResynthesizing}
                    className="flex items-center gap-1.5 mt-1 py-2 bg-transparent border-none cursor-pointer"
                    style={{ fontSize: 11, color: isResynthesizing ? INK['30'] : 'var(--t-verde)', fontFamily: FONT.sans, opacity: isResynthesizing ? 0.6 : 1 }}
                  >
                    <PerriandIcon name="sparkle" size={10} color={isResynthesizing ? INK['30'] : 'var(--t-verde)'} />
                    {isResynthesizing ? 'Re-synthesizing…' : 'Refresh Taste Profile'}
                    {resynthesisResult === 'success' && <span style={{ color: 'var(--t-verde)', marginLeft: 4 }}>✓</span>}
                    {resynthesisResult === 'error' && <span style={{ color: '#c44', marginLeft: 4 }}>Failed</span>}
                  </button>
                </div>

                {/* Auth */}
                <div className="mt-4 pt-3" style={{ borderTop: '1px solid var(--t-linen)' }}>
                  {isAuthenticated ? (
                    <div className="flex items-center justify-between">
                      <span className="text-[10px]" style={{ color: INK['50'] }}>{user?.email}</span>
                      <button onClick={signOut} className="text-[10px] font-medium px-2 py-1 rounded-full cursor-pointer" style={{ background: 'rgba(214,48,32,0.08)', color: '#c44', border: 'none', fontFamily: FONT.sans }}>Sign out</button>
                    </div>
                  ) : (
                    <Link href="/login" className="text-[11px] font-semibold" style={{ color: 'var(--t-verde)', textDecoration: 'none' }}>Sign in →</Link>
                  )}
                </div>
              </div>
            </div>

            {/* Right: content feed */}
            <div className="flex-1 min-w-0">
              {activeTab === 'discover' ? discoverFeed : (
                <>
                  <ProfileDeepDive />
                </>
              )}
            </div>
          </div>
        </div>
      </PageTransition>
    );
  }

  /* ─── Mobile Profile layout (unchanged) ─── */
  return (
    <PageTransition className="min-h-screen" style={{ background: 'var(--t-cream)', maxWidth: 480, margin: '0 auto', paddingBottom: 64 }}>
      <div className="px-5 pt-6 pb-2">
        {headerBlock}
      </div>

      {activeTab === 'discover' ? (
        discoverFeed
      ) : (
        /* ═══════════ MY PROFILE ═══════════ */
        <>
          {/* Action buttons */}
          <div className="px-5 pt-2 pb-4 flex flex-col gap-2.5">
            <SafeMotionButton
              onClick={() => setShowWrapped(true)}
              className="w-full flex items-center justify-between p-3.5 rounded-xl cursor-pointer border-none transition-all hover:opacity-90"
              style={{ background: '#2d3a2d' }}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <div className="flex flex-col items-start gap-0.5">
                <span
                  className="text-[12px] font-semibold"
                  style={{ color: '#f5f5f0', fontFamily: FONT.sans }}
                >
                  Your Taste Dossier
                </span>
                <span
                  className="text-[9px]"
                  style={{ color: 'rgba(245,245,240,0.45)', fontFamily: FONT.mono }}
                >
                  {signalCount} signals · {profile.contradictions?.length || 3} tensions
                </span>
              </div>
              <span
                className="text-[10px] px-2.5 py-1 rounded-full font-semibold"
                style={{
                  background: 'rgba(245,245,240,0.12)',
                  color: '#f5f5f0',
                  fontFamily: FONT.mono,
                }}
              >
                Replay →
              </span>
            </SafeMotionButton>

            <SafeMotionButton
              onClick={() => setShowMosaic(true)}
              className="w-full flex items-center justify-between p-3.5 rounded-xl cursor-pointer border-none transition-all hover:opacity-90"
              style={{
                background: 'linear-gradient(135deg, #e8dcc8 0%, #f5f0e6 100%)',
                border: '1px solid rgba(200,146,58,0.12)',
              }}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <div className="flex flex-col items-start gap-0.5">
                <span
                  className="text-[12px] font-semibold"
                  style={{ color: 'var(--t-ink)', fontFamily: FONT.sans }}
                >
                  Expand Your Mosaic
                </span>
                <span
                  className="text-[9px]"
                  style={{ color: INK['50'], fontFamily: FONT.mono }}
                >
                  Quick questions that sharpen your matches
                </span>
              </div>
              <span
                className="text-[10px] px-2.5 py-1 rounded-full font-semibold"
                style={{
                  background: 'rgba(28,26,23,0.06)',
                  color: 'var(--t-ink)',
                  fontFamily: FONT.mono,
                }}
              >
                Play →
              </span>
            </SafeMotionButton>
          </div>

          {/* Deep Dive */}
          <ProfileDeepDive />

          {/* Settings */}
          <div className="px-4 py-6">
            <h3
              className="text-[10px] uppercase tracking-[0.2em] mb-4"
              style={{ color: '#8a6a2a', fontFamily: FONT.mono, fontWeight: 700 }}
            >
              Settings
            </h3>
            <div className="flex flex-col gap-2">
              {SETTINGS_LINKS.map(({ label, action }) => (
                <div key={action}>
                  <div
                    onClick={() => handleSettingTap(action)}
                    className="flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all"
                    style={{ background: expandedSection === action ? 'rgba(200,146,58,0.06)' : INK['03'] }}
                  >
                    <span className="text-[12px]" style={{ color: 'var(--t-ink)' }}>{label}</span>
                    <span style={{ color: INK['95'], transform: expandedSection === action ? 'rotate(90deg)' : 'none', transition: 'transform 0.2s' }}>→</span>
                  </div>
                  {expandedSection === 'accounts' && action === 'accounts' && (
                    <div className="px-3 py-3 mt-1 rounded-xl" style={{ background: 'rgba(107,139,154,0.05)' }}>
                      {/* Gmail row — dynamic */}
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <PerriandIcon name="email" size={12} color="var(--t-ink)" />
                          <span className="text-[11px]" style={{ color: 'var(--t-ink)' }}>Gmail</span>
                        </div>
                        {emailLoading ? (
                          <span className="text-[10px]" style={{ color: INK['40'] }}>Checking…</span>
                        ) : emailStatus?.connected ? (
                          <span className="text-[10px] px-2.5 py-1 rounded-full" style={{ background: 'rgba(42,122,86,0.08)', color: 'var(--t-verde)' }}>
                            Connected
                          </span>
                        ) : (
                          <a
                            href="/api/auth/nylas/connect"
                            className="text-[10px] font-semibold px-2.5 py-1 rounded-full"
                            style={{ background: 'var(--t-verde)', color: 'white', textDecoration: 'none' }}
                          >
                            Connect
                          </a>
                        )}
                      </div>
                      {/* Connected: show email, scan, disconnect */}
                      {emailStatus?.connected && (
                        <div className="ml-5 mb-3">
                          <span className="text-[10px] block mb-2" style={{ color: INK['50'] }}>
                            {emailStatus.email}
                          </span>
                          <div className="flex items-center gap-2 flex-wrap mb-2">
                            <button
                              onClick={handleScanNow}
                              disabled={scanState === 'scanning' || scanState === 'parsing'}
                              className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer"
                              style={{ background: '#2a7a56', color: 'white', opacity: scanState === 'scanning' || scanState === 'parsing' ? 0.7 : 1 }}
                            >
                              {scanState === 'scanning' ? 'Scanning…' : scanState === 'parsing' ? `Parsing${scanResult?.emailsParsed ? ` ${scanResult.emailsParsed}/${scanResult.emailsFound}` : '…'}` : scanState === 'done' ? '✓ Done' : scanState === 'failed' ? 'Retry Scan' : 'Scan Inbox'}
                            </button>
                            <button onClick={handleDebugEmail} className="text-[10px] px-2 py-1 rounded-full border-none cursor-pointer" style={{ background: 'rgba(0,0,0,0.06)', color: INK['60'] }}>
                              Debug
                            </button>
                            {scanState === 'parsing' && scanResult && (scanResult.reservationsFound ?? 0) > 0 && (
                              <button
                                onClick={() => router.push('/email/inbox')}
                                className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer"
                                style={{ background: 'var(--t-honey)', color: 'white' }}
                              >
                                Review {scanResult.reservationsFound} so far →
                              </button>
                            )}
                            {scanState === 'done' && scanResult && (scanResult.reservationsFound ?? 0) > 0 && (
                              <button
                                onClick={() => router.push('/email/inbox')}
                                className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer"
                                style={{ background: 'var(--t-honey)', color: 'white' }}
                              >
                                Review {scanResult.reservationsFound} reservations →
                              </button>
                            )}
                            {scanState === 'done' && scanResult && (scanResult.reservationsFound ?? 0) === 0 && (
                              <span className="text-[10px]" style={{ color: INK['40'] }}>
                                {scanResult.emailsFound} emails scanned · no reservations found
                              </span>
                            )}
                          </div>
                          <button
                            onClick={handleDisconnect}
                            className="text-[9px] px-2 py-0.5 rounded-full border-none cursor-pointer"
                            style={{ background: 'rgba(196,80,32,0.08)', color: '#c45020' }}
                          >
                            Disconnect
                          </button>
                        </div>
                      )}
                      {/* Google Maps row — static */}
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <PerriandIcon name="pin" size={12} color="var(--t-ink)" />
                          <span className="text-[11px]" style={{ color: 'var(--t-ink)' }}>Google Maps</span>
                        </div>
                        <span className="text-[10px] px-2.5 py-1 rounded-full" style={{ background: 'rgba(42,122,86,0.08)', color: 'var(--t-verde)' }}>
                          Via import
                        </span>
                      </div>
                    </div>
                  )}
                  {/* Import History panel */}
                  {expandedSection === 'history' && action === 'history' && (
                    <div className="px-3 py-3 mt-1 rounded-xl" style={{ background: 'rgba(107,139,154,0.05)' }}>
                      {historyLoading ? (
                        <span className="text-[10px]" style={{ color: INK['40'] }}>Loading history…</span>
                      ) : importHistory.length === 0 ? (
                        <span className="text-[10px]" style={{ color: INK['40'] }}>
                          No import history yet. Connect Gmail or import from a URL to get started.
                        </span>
                      ) : (
                        <div className="flex flex-col gap-2">
                          {importHistory.slice(0, 15).map((item) => (
                            <div
                              key={item.id}
                              className="flex items-center justify-between py-1.5 cursor-pointer"
                              onClick={() => item.scanId ? router.push('/email/inbox') : undefined}
                            >
                              <div className="flex items-center gap-2 min-w-0">
                                <PerriandIcon
                                  name={item.type === 'email-scan' ? 'email' : item.type === 'url-import' ? 'article' : 'manual'}
                                  size={10}
                                  color={INK['50']}
                                />
                                <div className="min-w-0">
                                  <span className="text-[10px] font-medium block truncate" style={{ color: 'var(--t-ink)' }}>
                                    {item.title}
                                  </span>
                                  <span className="text-[9px] block" style={{ color: INK['40'] }}>
                                    {item.subtitle}
                                  </span>
                                </div>
                              </div>
                              <span className="text-[9px] flex-shrink-0 ml-2" style={{ color: INK['30'] }}>
                                {new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                              </span>
                            </div>
                          ))}
                          {/* Link to staging inbox */}
                          <button
                            onClick={() => router.push('/email/inbox')}
                            className="text-[10px] font-medium mt-1 bg-transparent border-none cursor-pointer text-left"
                            style={{ color: 'var(--t-honey)' }}
                          >
                            View email reservations →
                          </button>
                        </div>
                      )}
                    </div>
                  )}
                  {expandedSection === 'notifications' && action === 'notifications' && (
                    <div className="px-3 py-3 mt-1 rounded-xl text-[11px]" style={{ background: 'rgba(107,139,154,0.05)', color: INK['95'] }}>
                      Notification preferences will be available in a future update.
                    </div>
                  )}
                  {expandedSection === 'about' && action === 'about' && (
                    <div className="px-3 py-3 mt-1 rounded-xl text-[11px]" style={{ background: 'rgba(107,139,154,0.05)', color: INK['95'] }}>
                      Terrazzo v0.1 — Your taste-driven travel companion. Built with Forme Libere design principles.
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Redo Onboarding */}
            <button
              onClick={handleRedoOnboarding}
              className="w-full flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all mt-2"
              style={{
                background: 'rgba(232,115,58,0.06)',
                border: '1px dashed rgba(232,115,58,0.2)',
              }}
            >
              <div className="flex items-center gap-2">
                <PerriandIcon name="discover" size={12} color="var(--t-panton-orange)" />
                <span className="text-[12px] font-medium" style={{ color: '#c45020' }}>
                  Redo Onboarding
                </span>
              </div>
              <span style={{ color: '#c45020', fontSize: 12 }}>→</span>
            </button>

            {/* Refresh Taste Profile */}
            <button
              onClick={handleResynthesis}
              disabled={isResynthesizing}
              className="w-full flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all mt-2"
              style={{
                background: isResynthesizing ? 'rgba(42,122,86,0.03)' : 'rgba(42,122,86,0.06)',
                border: '1px dashed rgba(42,122,86,0.2)',
                opacity: isResynthesizing ? 0.7 : 1,
              }}
            >
              <div className="flex items-center gap-2">
                <PerriandIcon name="sparkle" size={12} color="var(--t-verde)" />
                <span className="text-[12px] font-medium" style={{ color: 'var(--t-verde)' }}>
                  {isResynthesizing ? 'Re-synthesizing…' : 'Refresh Taste Profile'}
                </span>
                {resynthesisResult === 'success' && <span style={{ color: 'var(--t-verde)', fontSize: 12 }}>✓ Updated</span>}
                {resynthesisResult === 'error' && <span style={{ color: '#c44', fontSize: 12 }}>Failed</span>}
              </div>
              {!isResynthesizing && !resynthesisResult && (
                <span style={{ color: 'var(--t-verde)', fontSize: 12 }}>→</span>
              )}
            </button>

            {/* Account / Sign In-Out */}
            <div className="mt-4 p-3 rounded-xl" style={{ background: INK['03'] }}>
              {isAuthenticated ? (
                <div className="flex items-center justify-between">
                  <div>
                    <span className="text-[11px]" style={{ color: INK['50'], fontFamily: FONT.sans }}>
                      Signed in as
                    </span>
                    <span className="text-[12px] ml-1 font-medium" style={{ color: 'var(--t-ink)', fontFamily: FONT.sans }}>
                      {user?.email}
                    </span>
                  </div>
                  <button
                    onClick={signOut}
                    className="text-[11px] font-medium px-3 py-1.5 rounded-full cursor-pointer"
                    style={{
                      background: 'rgba(214,48,32,0.08)',
                      color: '#c44',
                      border: 'none',
                      fontFamily: FONT.sans,
                    }}
                  >
                    Sign out
                  </button>
                </div>
              ) : (
                <div className="flex items-center justify-between">
                  <span className="text-[11px]" style={{ color: INK['50'], fontFamily: FONT.sans }}>
                    Sign in to save your places and trips
                  </span>
                  <Link
                    href="/login"
                    className="text-[11px] font-semibold px-3 py-1.5 rounded-full"
                    style={{
                      background: 'var(--t-verde)',
                      color: 'white',
                      textDecoration: 'none',
                      fontFamily: FONT.sans,
                    }}
                  >
                    Sign in
                  </Link>
                </div>
              )}
            </div>
          </div>
        </>
      )}

      <TabBar />
    </PageTransition>
  );
}


// ═══════════════════════════════════════════
// DISCOVER FEED SECTIONS — Editorial Intelligence
// ═══════════════════════════════════════════

function SectionLabel({ children, color = 'var(--t-honey)' }: { children: React.ReactNode; color?: string }) {
  return (
    <div
      className="text-[10px] uppercase tracking-[0.2em] font-bold"
      style={{ color, fontFamily: FONT.mono }}
    >
      {children}
    </div>
  );
}

// ── EDITORIAL LETTER — The opening essay ──
function EditorialLetterSection({ letter }: { letter?: EditorialLetter }) {
  const l = letter || EDITORIAL_LETTER;
  return (
    <SafeMotionDiv
      
      className="px-5 pt-5 pb-6"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <div className="mb-4">
        <div className="flex items-center gap-2 mb-4">
          <SafeMotionDiv
            className="w-5 h-[1px]"
            style={{ background: 'var(--t-honey)' }}
            initial={{ scaleX: 0 }}
            whileInView={{ scaleX: 1 }}
            transition={{ duration: 0.8, delay: 0.1 }}
            viewport={{ once: true, margin: '-100px' }}
          />
          <SafeMotionSpan
            className="text-[9px] uppercase tracking-[0.25em]"
            style={{ color: 'var(--t-honey)', fontFamily: FONT.mono }}
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            viewport={{ once: true, margin: '-100px' }}
          >
            A note from Terrazzo
          </SafeMotionSpan>
        </div>
        <SafeMotionH2
          className="text-[20px] leading-snug mb-4"
          style={{ fontFamily: FONT.serif, color: 'var(--t-ink)' }}
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.3 }}
          viewport={{ once: true, margin: '-100px' }}
        >
          {l.headline}
        </SafeMotionH2>
        <SafeMotionP
          className="text-[13px] leading-relaxed"
          style={{ color: INK['70'], fontFamily: FONT.sans }}
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.4 }}
          viewport={{ once: true, margin: '-100px' }}
        >
          {l.body}
        </SafeMotionP>
      </div>
      <SafeMotionDiv
        className="flex items-center gap-2"
        initial={{ opacity: 0, scale: 0.95 }}
        whileInView={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5, delay: 0.5 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <span className="text-[9px] px-2.5 py-1 rounded-full" style={{ background: 'rgba(200,146,58,0.08)', color: 'var(--t-honey)', fontFamily: FONT.mono }}>
          Sparked by: {l.signalHighlight}
        </span>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

// ── BECAUSE YOU — Signal-to-place insight cards ──
function BecauseYouSection({ cards }: { cards?: BecauseYouCard[] }) {
  const displayCards = cards || BECAUSE_YOU_CARDS;
  return (
    <SafeMotionDiv
      
      className="mb-7 px-5"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <div className="mb-3">
        <SectionLabel>Because you...</SectionLabel>
      </div>
      <div
        className="flex gap-3 overflow-x-auto pb-2 -mr-5 pr-5"
        style={{ scrollbarWidth: 'none', scrollSnapType: 'x mandatory' }}
      >
        {displayCards.map((card, idx) => {
          const domainColor = DIMENSION_COLORS[card.signalDomain] || '#8b6b4a';
          return (
            <PlaceLink key={card.place} name={card.place} location={card.location} googlePlaceId={card.googlePlaceId}>
              <SafeMotionDiv
                className="flex-shrink-0 p-5 rounded-2xl flex flex-col justify-between"
                style={{ background: card.bg, width: 280, minHeight: 230, scrollSnapAlign: 'start' }}
                initial={{ opacity: 0, x: -20, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1, x: 0 }}
                transition={{ duration: 0.5, delay: idx * 0.1 }}
                viewport={{ once: true, margin: '-100px' }}
              >
                <div>
                  <div className="flex items-center gap-2 mb-4">
                    <PerriandIcon name="sparkle" size={12} color={domainColor} />
                    <span className="text-[9px] uppercase tracking-wider px-2 py-0.5 rounded-full" style={{ background: `${domainColor}40`, color: domainColor, fontFamily: FONT.mono }}>
                      {card.signalDomain}
                    </span>
                  </div>
                  <p className="text-[12px] leading-relaxed mb-1" style={{ color: 'rgba(245,245,240,0.72)', fontFamily: FONT.sans }}>
                    Because you love
                  </p>
                  <p className="text-[16px] font-semibold mb-4 italic" style={{ color: '#f5f5f0', fontFamily: FONT.serif }}>
                    &ldquo;{card.signal}&rdquo;
                  </p>
                </div>
                <div>
                  <div className="flex items-center gap-2.5 mb-2">
                    <ScoreArc score={card.score} size={34} color="#f5f5f0" />
                    <div>
                      <div className="text-[14px] font-semibold" style={{ color: '#f5f5f0' }}>{card.place}</div>
                      <div className="text-[11px]" style={{ color: 'rgba(245,245,240,0.6)' }}>{card.location}</div>
                    </div>
                  </div>
                  <p className="text-[11px] leading-relaxed" style={{ color: 'rgba(245,245,240,0.7)' }}>{card.why}</p>
                </div>
              </SafeMotionDiv>
            </PlaceLink>
          );
        })}
      </div>
    </SafeMotionDiv>
  );
}

// ── SIGNAL THREAD — One signal, many manifestations ──
function SignalThreadSection({ thread }: { thread?: SignalThread }) {
  const t = thread || SIGNAL_THREAD;
  const domainColor = DIMENSION_COLORS[t.domain] || '#8b6b4a';
  const TYPE_ICONS: Record<string, string> = { hotel: 'hotel', restaurant: 'restaurant', bar: 'bar', cafe: 'cafe', neighborhood: 'neighborhood' };

  return (
    <SafeMotionDiv
      className="px-5 mb-7"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel>The thread</SectionLabel>
      <SafeMotionDiv
        className="mt-3 p-5 rounded-2xl"
        style={{ background: 'white', border: '1px solid var(--t-linen)' }}
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.1 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <div className="flex items-center gap-2 mb-3">
          <span className="text-[10px] px-2.5 py-1 rounded-full font-semibold" style={{ background: `${domainColor}12`, color: domainColor, fontFamily: FONT.mono }}>
            {t.signal}
          </span>
        </div>
        <p className="text-[13px] leading-relaxed mb-5" style={{ color: INK['70'], fontFamily: FONT.sans }}>
          {t.thread}
        </p>
        {/* Vertical thread line connecting places */}
        <div className="flex flex-col gap-0">
          {t.places.map((place, i) => (
            <PlaceLink key={place.name} name={place.name} location={place.location} googlePlaceId={place.googlePlaceId}>
              <SafeMotionDiv
                className="flex gap-3"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.2 + i * 0.1 }}
                viewport={{ once: true, margin: '-100px' }}
              >
                {/* Thread line */}
                <div className="flex flex-col items-center" style={{ width: 20 }}>
                  <SafeMotionDiv
                    className="w-2 h-2 rounded-full flex-shrink-0"
                    style={{ background: domainColor, marginTop: 4 }}
                    initial={{ scale: 0.95 }}
                    whileInView={{ scale: 1 }}
                    transition={{ duration: 0.4, delay: 0.2 + i * 0.1 }}
                    viewport={{ once: true, margin: '-100px' }}
                  />
                  {i < t.places.length - 1 && (
                    <SafeMotionDiv
                      className="w-[1px] flex-1"
                      style={{ background: INK['10'] }}
                      initial={{ scaleY: 0 }}
                      whileInView={{ scaleY: 1 }}
                      transition={{ duration: 0.5, delay: 0.3 + i * 0.1 }}
                      viewport={{ once: true, margin: '-100px' }}
                    />
                  )}
                </div>
                {/* Place card */}
                <div className="flex-1 pb-4">
                  <div className="flex items-center gap-1.5 mb-1">
                    <PerriandIcon name={(TYPE_ICONS[place.type] || 'discover') as import('@/types').PerriandIconName} size={12} color={INK['55']} />
                    <span className="text-[9px] uppercase tracking-wider" style={{ color: INK['55'], fontFamily: FONT.mono }}>{place.type}</span>
                  </div>
                  <div className="flex items-baseline gap-2 mb-1">
                    <span className="text-[13px] font-semibold" style={{ color: 'var(--t-ink)' }}>{place.name}</span>
                    <span className="text-[10px]" style={{ color: INK['50'] }}>{place.location}</span>
                    <span className="text-[10px] font-bold ml-auto" style={{ color: domainColor, fontFamily: FONT.mono }}>{place.score <= 1 ? Math.round(place.score * 100) : place.score}</span>
                  </div>
                  <p className="text-[11px] leading-relaxed" style={{ color: INK['75'] }}>{place.connection}</p>
                </div>
              </SafeMotionDiv>
            </PlaceLink>
          ))}
        </div>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

// ── TASTE TENSION — Editorial exploration of a contradiction ──
function TasteTensionSection({ tension }: { tension?: TasteTension }) {
  const t = tension || TASTE_TENSION;
  return (
    <SafeMotionDiv
      className="px-5 mb-7"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel color="var(--t-panton-violet)">Taste tension</SectionLabel>
      <SafeMotionDiv
        className="mt-3 rounded-2xl overflow-hidden"
        style={{ background: '#2a2535' }}
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7, delay: 0.1 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <div className="p-5">
          <h3 className="text-[18px] leading-snug mb-4" style={{ fontFamily: FONT.serif, color: '#f5f5f0' }}>
            {t.title}
          </h3>
          <div className="flex gap-3 mb-4">
            <SafeMotionDiv
              className="flex-1 p-3 rounded-xl"
              style={{ background: 'rgba(245,245,240,0.06)' }}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              viewport={{ once: true, margin: '-100px' }}
            >
              <div className="text-[9px] uppercase tracking-wider mb-1.5" style={{ color: 'rgba(245,245,240,0.4)', fontFamily: FONT.mono }}>You think</div>
              <p className="text-[12px] italic leading-snug" style={{ color: 'rgba(245,245,240,0.85)' }}>&ldquo;{t.stated}&rdquo;</p>
            </SafeMotionDiv>
            <SafeMotionDiv
              className="flex-1 p-3 rounded-xl"
              style={{ background: 'rgba(245,245,240,0.06)' }}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              viewport={{ once: true, margin: '-100px' }}
            >
              <div className="text-[9px] uppercase tracking-wider mb-1.5" style={{ color: 'rgba(245,245,240,0.4)', fontFamily: FONT.mono }}>You do</div>
              <p className="text-[12px] italic leading-snug" style={{ color: 'rgba(245,245,240,0.85)' }}>&ldquo;{t.revealed}&rdquo;</p>
            </SafeMotionDiv>
          </div>
          <p className="text-[12px] leading-relaxed mb-4" style={{ color: 'rgba(245,245,240,0.8)', fontFamily: FONT.sans }}>
            {t.editorial}
          </p>
        </div>
        <PlaceLink name={t.resolvedBy.name} location={t.resolvedBy.location} googlePlaceId={t.resolvedBy.googlePlaceId}>
          <div className="px-5 py-4" style={{ background: 'rgba(245,245,240,0.05)', borderTop: '1px solid rgba(245,245,240,0.08)' }}>
            <div className="text-[9px] uppercase tracking-wider mb-2" style={{ color: 'rgba(104,68,160,0.7)', fontFamily: FONT.mono }}>Resolved by</div>
            <div className="text-[13px] font-semibold mb-1" style={{ color: '#f5f5f0' }}>
              {t.resolvedBy.name} <span className="font-normal text-[11px]" style={{ color: 'rgba(245,245,240,0.5)' }}>{t.resolvedBy.location}</span>
            </div>
            <p className="text-[11px] leading-relaxed" style={{ color: 'rgba(245,245,240,0.75)' }}>{t.resolvedBy.how}</p>
          </div>
        </PlaceLink>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

// ── THIS WEEK'S EDIT ──
function WeeklyEditSection({ collection: propCollection }: { collection?: { title: string; subtitle: string; places: CollectionPlace[] } }) {
  const collection = propCollection || WEEKLY_COLLECTION;
  return (
    <SafeMotionDiv
      className="mb-7 px-5"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <div className="mb-1"><SectionLabel>This week&apos;s edit</SectionLabel></div>
      <div className="mb-3">
        <h3 className="text-[18px] leading-snug mb-1" style={{ fontFamily: FONT.serif, color: 'var(--t-ink)' }}>{collection.title}</h3>
        <p className="text-[11px]" style={{ color: INK['60'], fontFamily: FONT.mono }}>{collection.subtitle}</p>
      </div>
      <div className="flex gap-3 overflow-x-auto pb-2 -mr-5 pr-5" style={{ scrollbarWidth: 'none', scrollSnapType: 'x mandatory' }}>
        {collection.places.map((place, idx) => {
          const domainColor = DIMENSION_COLORS[place.signalDomain] || '#8b6b4a';
          const imageUrl = getPlaceImage(place.name);
          return (
            <PlaceLink key={place.name} name={place.name} location={place.location} googlePlaceId={place.googlePlaceId}>
              <SafeMotionDiv
                className="flex-shrink-0 rounded-xl flex flex-col overflow-hidden"
                style={{ background: 'white', border: '1px solid var(--t-linen)', width: 240, scrollSnapAlign: 'start' }}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: idx * 0.1 }}
                viewport={{ once: true, margin: '-100px' }}
              >
                {imageUrl && (
                  <div style={{ height: 100, overflow: 'hidden', position: 'relative' }}>
                    <PlacePhoto src={imageUrl} alt={place.name} fill sizes="240px" />
                  </div>
                )}
                <div className="p-4 flex flex-col">
                  <div className="flex items-start justify-between mb-2">
                    <div>
                      <div className="text-[14px] font-semibold" style={{ color: 'var(--t-ink)' }}>{place.name}</div>
                      <div className="text-[11px]" style={{ color: INK['60'] }}>{place.location}</div>
                    </div>
                    <ScoreArc score={place.score} size={38} color="#4a6741" />
                  </div>
                  <div className="flex flex-wrap gap-1 mb-2.5">
                    {(Array.isArray(place.signals) ? place.signals : []).map(s => (
                      <span key={s} className="text-[9px] px-2 py-0.5 rounded-full" style={{ background: `${domainColor}12`, color: domainColor, fontFamily: FONT.sans }}>{s}</span>
                    ))}
                  </div>
                  <p className="text-[11px] leading-relaxed" style={{ color: INK['75'] }}>{place.note}</p>
                </div>
              </SafeMotionDiv>
            </PlaceLink>
          );
        })}
      </div>
    </SafeMotionDiv>
  );
}

// ── MOOD BOARDS — Curated moods ──
function MoodBoardSection({ boards }: { boards?: MoodBoard[] }) {
  const displayBoards = boards || MOOD_BOARDS;
  return (
    <SafeMotionDiv
      className="px-5 mb-7"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel>Travel moods</SectionLabel>
      <div className="flex flex-col gap-3 mt-3">
        {displayBoards.map((board, idx) => (
          <SafeMotionDiv
            key={board.mood}
            className="p-4 rounded-2xl"
            style={{ background: 'white', border: '1px solid var(--t-linen)', borderLeft: `3px solid ${board.color}` }}
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: idx * 0.1 }}
            viewport={{ once: true, margin: '-100px' }}
          >
            <h4 className="text-[14px] font-semibold mb-1" style={{ fontFamily: FONT.serif, color: 'var(--t-ink)' }}>{board.mood}</h4>
            <p className="text-[11px] mb-4" style={{ color: INK['70'], fontFamily: FONT.sans }}>{board.description}</p>
            <div className="flex flex-col gap-2">
              {board.places.map((p, pIdx) => {
                const imageUrl = getPlaceImage(p.name);
                return (
                  <PlaceLink key={p.name} name={p.name} location={p.location} googlePlaceId={p.googlePlaceId}>
                    <SafeMotionDiv
                      className="flex items-center gap-3"
                      initial={{ opacity: 0, y: 20 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.4, delay: idx * 0.1 + pIdx * 0.05 }}
                      viewport={{ once: true, margin: '-100px' }}
                    >
                      {imageUrl ? (
                        <div style={{ width: 40, height: 40, borderRadius: 10, overflow: 'hidden', flexShrink: 0, position: 'relative' }}>
                          <PlacePhoto src={imageUrl} alt={p.name} fill sizes="40px" />
                        </div>
                      ) : (
                        <ScoreArc score={p.score} size={40} color={board.color} />
                      )}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-baseline gap-1.5">
                          <span className="text-[12px] font-semibold" style={{ color: 'var(--t-ink)' }}>{p.name}</span>
                          <span className="text-[10px]" style={{ color: INK['60'] }}>{p.location}</span>
                        </div>
                        <p className="text-[10px] italic" style={{ color: INK['70'] }}>{p.vibe}</p>
                      </div>
                      <span className="text-[10px] font-bold flex-shrink-0" style={{ color: board.color, fontFamily: FONT.mono }}>{p.score <= 1 ? Math.round(p.score * 100) : p.score}</span>
                    </SafeMotionDiv>
                  </PlaceLink>
                );
              })}
            </div>
          </SafeMotionDiv>
        ))}
      </div>
    </SafeMotionDiv>
  );
}

// ── DEEP MATCH — Signal-by-signal breakdown ──
function DeepMatchSection({ match }: { match?: DeepMatch }) {
  const m = match || DEEP_MATCH;
  return (
    <SafeMotionDiv
      className="px-5 mb-7"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel color="var(--t-verde)">Your deepest match</SectionLabel>
      <PlaceLink name={m.name} location={m.location} googlePlaceId={m.googlePlaceId}>
        <SafeMotionDiv
          className="mt-3 rounded-2xl overflow-hidden"
          style={{ background: '#1e2e24' }}
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.1 }}
          viewport={{ once: true, margin: '-100px' }}
        >
          <div className="p-5">
            <div className="flex items-center gap-3 mb-3">
              <ScoreArc score={m.score} size={48} color="#7aba6e" />
              <div>
                <div className="text-[16px] font-semibold" style={{ color: '#f5f5f0' }}>{m.name}</div>
                <div className="text-[11px]" style={{ color: 'rgba(245,245,240,0.55)' }}>{m.location}</div>
              </div>
            </div>
          <p className="text-[13px] italic leading-relaxed mb-5" style={{ fontFamily: FONT.serif, color: 'rgba(245,245,240,0.8)' }}>{m.headline}</p>
          {/* Signal breakdown bars */}
          <div className="flex flex-col gap-3">
            {m.signalBreakdown.map((s, idx) => {
              const domainColor = DIMENSION_COLORS[s.domain] || '#8b6b4a';
              return (
                <div key={s.signal}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-[10px] font-semibold" style={{ color: 'rgba(245,245,240,0.7)' }}>{s.signal}</span>
                    <span className="text-[10px] font-bold" style={{ color: domainColor, fontFamily: FONT.mono }}>{s.strength}%</span>
                  </div>
                  <div className="h-1 rounded-full mb-1.5" style={{ background: 'rgba(245,245,240,0.08)' }}>
                    <SafeMotionDiv
                      className="h-1 rounded-full"
                      style={{ background: domainColor, opacity: 0.7 }}
                      whileInView={{ width: `${s.strength}%` }}
                      transition={{ duration: 1, delay: 0.2 + idx * 0.1 }}
                      viewport={{ once: true, margin: '-100px' }}
                    />
                  </div>
                  <p className="text-[10px] leading-snug" style={{ color: 'rgba(245,245,240,0.65)' }}>{s.note}</p>
                </div>
              );
            })}
          </div>
        </div>
        <div className="px-5 py-4" style={{ background: 'rgba(245,245,240,0.04)', borderTop: '1px solid rgba(245,245,240,0.06)' }}>
          <div className="text-[9px] uppercase tracking-wider mb-1.5" style={{ color: 'rgba(42,122,86,0.6)', fontFamily: FONT.mono }}>Tension resolved</div>
          <p className="text-[11px] leading-relaxed" style={{ color: 'rgba(245,245,240,0.75)' }}>{m.tensionResolved}</p>
        </div>
        </SafeMotionDiv>
      </PlaceLink>
    </SafeMotionDiv>
  );
}

// ── STRETCH PICK ──
function StretchPickSection({ stretch }: { stretch?: typeof STRETCH_PICK }) {
  const s = stretch || STRETCH_PICK;
  return (
    <SafeMotionDiv
      className="px-5 mb-7"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel color="var(--t-panton-orange)">Stretch pick</SectionLabel>
      <PlaceLink name={s.name} location={s.location} googlePlaceId={(s as Record<string, unknown>).googlePlaceId as string | undefined}>
        <SafeMotionDiv
          className="p-4 rounded-xl mt-3"
          style={{ background: 'white', border: '2px dashed var(--t-panton-orange)' }}
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5, delay: 0.1, type: 'spring', stiffness: 200 }}
          viewport={{ once: true, margin: '-100px' }}
        >
          <div className="flex items-center gap-1.5 mb-3">
            <PerriandIcon name="discover" size={10} color="var(--t-panton-orange)" />
            <span className="text-[10px] uppercase tracking-wider font-bold" style={{ color: '#c45020', fontFamily: FONT.mono }}>
              This isn&apos;t your usual pick
            </span>
          </div>
          <div className="flex items-start gap-3 mb-3">
            <ScoreArc score={s.score} size={44} color="var(--t-panton-orange)" />
            <div>
              <div className="text-[15px] font-semibold" style={{ color: 'var(--t-ink)' }}>{s.name}</div>
              <div className="text-[11px]" style={{ color: INK['60'] }}>{s.location}</div>
            <div className="flex gap-2 mt-1.5">
              <span className="text-[9px] px-2 py-0.5 rounded-full" style={{ background: 'rgba(74,107,139,0.1)', color: '#4a6b8b', fontFamily: FONT.mono }}>{s.strongAxis} {s.strongScore}%</span>
              <span className="text-[9px] px-2 py-0.5 rounded-full" style={{ background: 'rgba(107,107,74,0.1)', color: '#6b6b4a', fontFamily: FONT.mono }}>{s.weakAxis} {s.weakScore}%</span>
            </div>
          </div>
        </div>
        <div className="p-3 rounded-lg" style={{ background: 'rgba(232,104,48,0.04)' }}>
          <div className="text-[9px] uppercase tracking-wider mb-1" style={{ color: '#c45020', fontFamily: FONT.mono }}>Why we&apos;re suggesting it</div>
          <p className="text-[11px] leading-relaxed" style={{ color: INK['75'] }}>{s.why}</p>
        </div>
        <p className="text-[10px] italic leading-relaxed mt-2.5" style={{ color: INK['70'] }}>{s.tension}</p>
        </SafeMotionDiv>
      </PlaceLink>
    </SafeMotionDiv>
  );
}

// ── CONTEXT MODE ──
function ContextModeSection({ recs, contextLabel }: { recs?: ContextRec[]; contextLabel?: string }) {
  const displayRecs = recs || SUMMER_RECS;
  const label = contextLabel || 'Summer';
  return (
    <SafeMotionDiv
      className="px-5 mb-7"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel>Context mode</SectionLabel>
      <SafeMotionDiv
        className="p-4 rounded-xl mt-3"
        style={{ background: 'white', border: '1px solid var(--t-linen)', borderTop: '3px solid #6b8b4a' }}
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.1 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <div className="flex items-center gap-2 mb-1">
          <PerriandIcon name="summer" size={16} color="var(--t-ink)" />
          <span className="text-[14px] font-semibold" style={{ fontFamily: FONT.serif, color: 'var(--t-ink)' }}>
            If you&apos;re traveling this {label.toLowerCase()}...
          </span>
        </div>
        <p className="text-[11px] mb-4" style={{ color: INK['60'], fontFamily: FONT.mono }}>Indoor-outdoor flow · terrace dining · natural pool</p>
        <div className="flex flex-col gap-2.5">
          {displayRecs.map((rec, idx) => {
            const imageUrl = getPlaceImage(rec.name);
            return (
              <PlaceLink key={rec.name} name={rec.name} location={rec.location} googlePlaceId={rec.googlePlaceId}>
                <SafeMotionDiv
                  className="flex items-center gap-3"
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: 0.15 + idx * 0.05 }}
                  viewport={{ once: true, margin: '-100px' }}
                >
                  {imageUrl ? (
                    <div style={{ width: 36, height: 36, borderRadius: 10, overflow: 'hidden', flexShrink: 0, position: 'relative' }}>
                      <PlacePhoto src={imageUrl} alt={rec.name} fill sizes="36px" />
                    </div>
                  ) : (
                    <ScoreArc score={rec.score} size={36} color="#6b8b4a" />
                  )}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-baseline gap-1.5">
                      <span className="text-[12px] font-semibold" style={{ color: 'var(--t-ink)' }}>{rec.name}</span>
                      <span className="text-[10px]" style={{ color: INK['60'] }}>{rec.location}</span>
                    </div>
                    <p className="text-[10px] leading-snug" style={{ color: INK['70'] }}>{rec.whyFits}</p>
                  </div>
                </SafeMotionDiv>
              </PlaceLink>
            );
          })}
        </div>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

// ── VOCAB TEASER ──
function VocabTeaser({ profile }: { profile: typeof TASTE_PROFILE }) {
  const domains = Object.entries(profile.microTasteSignals).slice(0, 4);
  const allTerms: Array<{ term: string; domain: string }> = [];
  domains.forEach(([domain, terms]) => { terms.slice(0, 2).forEach(term => allTerms.push({ term, domain })); });
  const rejections = profile.microTasteSignals['Rejection']?.slice(0, 2) || [];
  rejections.forEach(term => allTerms.push({ term, domain: 'Rejection' }));

  return (
    <SafeMotionDiv
      className="px-5 mb-7"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel>Your taste vocabulary</SectionLabel>
      <SafeMotionDiv
        className="p-4 rounded-xl mt-3"
        style={{ background: 'white', border: '1px solid var(--t-linen)' }}
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.1 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <div className="flex flex-wrap gap-1.5 mb-3">
          {allTerms.map(({ term, domain }, idx) => {
            const color = DIMENSION_COLORS[domain] || '#8b6b4a';
            const isRejection = domain === 'Rejection';
            const randomDelay = Math.random() * 0.3;
            return (
              <SafeMotionSpan
                key={term}
                className="text-[10px] px-2.5 py-1 rounded-full"
                style={{ background: isRejection ? 'rgba(139,74,74,0.08)' : `${color}12`, color: isRejection ? '#8b4a4a' : color, fontFamily: FONT.sans }}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.4, delay: randomDelay }}
                viewport={{ once: true, margin: '-100px' }}
              >
                {term}
              </SafeMotionSpan>
            );
          })}
          <SafeMotionSpan
            className="text-[10px] px-2.5 py-1 rounded-full"
            style={{ background: INK['04'], color: INK['50'] }}
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.4, delay: 0.3 }}
            viewport={{ once: true, margin: '-100px' }}
          >
            +{Object.values(profile.microTasteSignals).flat().length - allTerms.length} more
          </SafeMotionSpan>
        </div>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

// ── FRIENDS SAVING ──
function FriendsSavingSection() {
  return (
    <SafeMotionDiv
      className="px-5 mb-8"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel>Friends are saving</SectionLabel>
      <div className="flex flex-col gap-3 mt-3">
        {FRIEND_SAVES.map((save, idx) => (
          <PlaceLink key={save.place} name={save.place} location={save.location} googlePlaceId={save.googlePlaceId}>
            <SafeMotionDiv
              className="p-3.5 rounded-xl flex items-start gap-3"
              style={{ background: 'white', border: '1px solid var(--t-linen)' }}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              viewport={{ once: true, margin: '-100px' }}
            >
              <div className="w-8 h-8 rounded-full flex items-center justify-center text-[11px] font-bold flex-shrink-0" style={{ background: `${save.color}15`, color: save.color, fontFamily: FONT.mono }}>
                {save.friendInitial}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-1.5 mb-0.5">
                  <span className="text-[11px] font-semibold" style={{ color: 'var(--t-ink)' }}>{save.friendName}</span>
                  <span className="text-[11px]" style={{ color: INK['60'] }}>saved</span>
                  <span className="text-[11px] font-semibold" style={{ color: 'var(--t-ink)' }}>{save.place}</span>
                </div>
                <div className="text-[10px] mb-1" style={{ color: INK['60'] }}>{save.location} · {save.type}</div>
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-bold" style={{ color: save.color, fontFamily: FONT.mono }}>{save.score <= 1 ? Math.round(save.score * 100) : save.score}% match</span>
                  <span className="text-[10px]" style={{ color: INK['70'] }}>{save.whyMatches}</span>
                </div>
              </div>
            </SafeMotionDiv>
          </PlaceLink>
        ))}
      </div>
    </SafeMotionDiv>
  );
}
