'use client';

import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

import PageTransition from '@/components/PageTransition';
import { SafeFadeIn } from '@/components/animations/SafeFadeIn';
import { SafeMotionDiv, SafeMotionSpan, SafeMotionButton, SafeMotionH2, SafeMotionP } from '@/components/animations/AnimatedElements';
import TabBar from '@/components/TabBar';
import DesktopNav from '@/components/DesktopNav';
import ProfileDeepDive from '@/components/profile/ProfileDeepDive';
import ExpandMosaicView from '@/components/profile/ExpandMosaicView';
import WrappedExperience from '@/components/wrapped/WrappedExperience';
import { TerrazzoMosaic } from '@/components/TerrazzoMosaic';
import TasteStone from '@/components/profile/TasteStone';
import ScoreArc from '@/components/profile/ScoreArc';
import { TASTE_PROFILE, DIMENSION_COLORS } from '@/constants/profile';
import type { TasteProfile as NumericProfile, ImportedPlace, PlaceRating } from '@/types';
import { PerriandIcon } from '@/components/icons/PerriandIcons';
import { useOnboardingStore } from '@/stores/onboardingStore';
import { useIsDesktop } from '@/hooks/useBreakpoint';
import PlacePhoto from '@/components/PlacePhoto';
import BrandLoader from '@/components/BrandLoader';
import {
  BECAUSE_YOU_CARDS,
  WEEKLY_COLLECTION,
  STRETCH_PICK,
  SUMMER_RECS,
  EDITORIAL_LETTER,
  SIGNAL_THREAD,
  TASTE_TENSION,
  MOOD_BOARDS,
  DEEP_MATCH,
  type BecauseYouCard,
  type CollectionPlace,
  type ContextRec,
  type EditorialLetter,
  type SignalThread,
  type TasteTension,
  type MoodBoard,
  type DeepMatch,
} from '@/constants/discover';
import { getPlaceImage } from '@/constants/placeImages';
import { COLOR, FONT, INK, TEXT } from '@/constants/theme';
import { TasteTensionCard, DeepMatchBreakdown, StretchPickAxis } from '@/components/intelligence';
import type { TasteTension as IntelTasteTension, DeepMatch as IntelDeepMatch, StretchPick as IntelStretchPick } from '@/components/intelligence';
import type { TasteDomain } from '@/types';
import { useAuth } from '@/context/AuthContext';
import { apiFetch } from '@/lib/api-client';
import PlaceLink from '@/components/PlaceLink';
import { PlaceDetailProvider } from '@/context/PlaceDetailContext';
import { useSavedStore } from '@/stores/savedStore';
import { useEmailScanStore } from '@/stores/emailScanStore';

// ─── Discover cache TTL (2 hours) ─────────────────────────────────────────────
const DISCOVER_CACHE_TTL_MS = 2 * 60 * 60 * 1000;

// Discover content generated by Claude AI
interface DiscoverContent {
  editorialLetter?: EditorialLetter;
  becauseYouCards?: BecauseYouCard[];
  signalThread?: SignalThread;
  tasteTension?: TasteTension;
  weeklyCollection?: { title: string; subtitle: string; places: CollectionPlace[] };
  moodBoards?: MoodBoard[];
  deepMatch?: DeepMatch;
  stretchPick?: typeof STRETCH_PICK;
  contextRecs?: ContextRec[];
  contextLabel?: string;
}

/**
 * Collect all place names from the initial feed + any extra pages so the
 * continuation API can avoid recommending duplicates.
 */
function collectAllPlaceNames(
  initial: DiscoverContent | null,
  extras: DiscoverContent[],
): string[] {
  const names = new Set<string>();
  function addFrom(content: DiscoverContent | null) {
    if (!content) return;
    for (const c of content.becauseYouCards || []) if (c.place) names.add(c.place);
    for (const p of content.signalThread?.places || []) if (p.name) names.add(p.name);
    if (content.tasteTension?.resolvedBy?.name) names.add(content.tasteTension.resolvedBy.name);
    for (const p of content.weeklyCollection?.places || []) if (p.name) names.add(p.name);
    for (const b of content.moodBoards || []) {
      for (const p of b.places || []) if (p.name) names.add(p.name);
    }
    if (content.deepMatch?.name) names.add(content.deepMatch.name);
    if (content.stretchPick?.name) names.add(content.stretchPick.name);
    for (const r of content.contextRecs || []) if (r.name) names.add(r.name);
  }
  addFrom(initial);
  for (const page of extras) addFrom(page);
  return Array.from(names);
}

const SETTINGS_LINKS = [
  { label: 'Connected Accounts', action: 'accounts' },
  { label: 'Import History', action: 'history' },
  { label: 'Notification Preferences', action: 'notifications' },
  { label: 'About Terrazzo', action: 'about' },
];

function getGreeting() {
  const hour = new Date().getHours();
  if (hour < 12) return 'Good morning';
  if (hour < 17) return 'Good afternoon';
  return 'Good evening';
}

type ProfileTab = 'discover' | 'profile';

export default function ProfilePage() {
  const ratePlace = useSavedStore(s => s.ratePlace);

  const addPlace = useSavedStore(s => s.addPlace);
  const myPlaces = useSavedStore(s => s.myPlaces);

  const handleSavePreview = useCallback(async (place: ImportedPlace): Promise<string | void> => {
    // Save to library via API — returns the real server ID so PlaceDetailContext
    // can update the detailItem and subsequent actions (rate, etc.) target the
    // correct record instead of the synthetic discover-prefixed ID.
    try {
      const googlePlaceId = (place.google as Record<string, unknown> & { placeId?: string })?.placeId;
      if (!googlePlaceId) return;

      // Check if already in library — if so, just return the existing ID
      const existing = myPlaces.find(p => p.google?.placeId === googlePlaceId);
      if (existing) return existing.id;

      const res = await apiFetch<{ place?: { id: string } }>('/api/places/save', {
        method: 'POST',
        body: JSON.stringify({
          googlePlaceId,
          name: place.name,
          type: place.type,
          location: place.location,
          source: { type: 'url', name: 'Discover Feed' },
        }),
      });

      const realId = res?.place?.id;
      if (realId) {
        // Add to Zustand store so the place appears in the library immediately
        // and future actions resolve the correct ID.
        addPlace({ ...place, id: realId });
        return realId;
      }
    } catch (err) {
      console.error('Failed to save discover place:', err);
    }
  }, [addPlace, myPlaces]);

  return (
    <PlaceDetailProvider config={{
      onRate: (place, rating) => {
        ratePlace(place.id, rating);
      },
      onSavePreview: handleSavePreview,
    }}>
      <ProfilePageContent />
    </PlaceDetailProvider>
  );
}

function ProfilePageContent() {

  const router = useRouter();
  const isDesktop = useIsDesktop();
  const [showWrapped, setShowWrapped] = useState(false);
  const [showMosaic, setShowMosaic] = useState(false);
  const [expandedSection, setExpandedSection] = useState<string | null>(null);
  const [activeTab, setActiveTabRaw] = useState<ProfileTab>(() => {
    if (typeof window !== 'undefined') {
      return (sessionStorage.getItem('profile_active_tab') as ProfileTab) || 'discover';
    }
    return 'discover';
  });
  const setActiveTab = useCallback((tab: ProfileTab) => {
    setActiveTabRaw(tab);
    sessionStorage.setItem('profile_active_tab', tab);
  }, []);
  const [discoverContent, setDiscoverContent] = useState<DiscoverContent | null>(null);
  const [isLoadingDiscover, setIsLoadingDiscover] = useState(false);
  const [isResynthesizing, setIsResynthesizing] = useState(false);

  // Infinite scroll: extra feed pages loaded on demand
  const [extraPages, setExtraPages] = useState<DiscoverContent[]>([]);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const [feedPageIndex, setFeedPageIndex] = useState(1);
  const [hasMoreContent, setHasMoreContent] = useState(true);
  const sentinelRef = useRef<HTMLDivElement | null>(null);

  const [resynthesisResult, setResynthesisResult] = useState<'success' | 'error' | null>(null);

  // ── Email / Connected Accounts state ─────────────────────────────────────
  const [emailStatus, setEmailStatus] = useState<{
    connected: boolean;
    email?: string;
    provider?: string;
    connectedAt?: string;
  } | null>(null);
  const [emailLoading, setEmailLoading] = useState(false);
  // Email scan — driven by global Zustand store (survives navigation)
  const scanProgress = useEmailScanStore(s => s.progress);
  const startScan = useEmailScanStore(s => s.startScan);
  const resumeScan = useEmailScanStore(s => s.resumeIfNeeded);
  const scanState = scanProgress.status;
  const scanResult = {
    scanId: scanProgress.scanId,
    emailsFound: scanProgress.emailsFound,
    emailsParsed: scanProgress.emailsParsed,
    reservationsFound: scanProgress.reservationsFound,
  };

  const [importHistory, setImportHistory] = useState<Array<{
    id: string;
    type: 'email-scan' | 'url-import' | 'manual';
    date: string;
    title: string;
    subtitle: string;
    count: number;
    status?: string;
    scanId?: string;
  }>>([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const hasGoogleMapsImport = importHistory.some(h => h.title.toLowerCase().includes('google maps') || h.title.toLowerCase().includes('google-maps'));

  const { isAuthenticated, user, signOut } = useAuth();
  const resetForRedo = useOnboardingStore(s => s.resetForRedo);
  const triggerResynthesis = useOnboardingStore(s => s.triggerResynthesis);
  const generatedProfile = useOnboardingStore(s => s.generatedProfile);
  const lifeContext = useOnboardingStore(s => s.lifeContext);
  const allSignals = useOnboardingStore(s => s.allSignals);
  const dbHydrated = useOnboardingStore(s => s.dbHydrated);

  // Debug: log every state change that could trigger a re-render
  const prevDbHydrated = useRef(dbHydrated);
  const prevActiveTab = useRef(activeTab);
  const prevDiscoverContent = useRef(discoverContent);
  useEffect(() => {
    if (prevDbHydrated.current !== dbHydrated) {
      console.log(`%c[PAGE ProfilePage] 💧 dbHydrated: ${prevDbHydrated.current} → ${dbHydrated} @ ${performance.now().toFixed(1)}ms`, 'color: #FF6F00; font-weight: bold; font-size: 13px');
      prevDbHydrated.current = dbHydrated;
    }
  }, [dbHydrated]);
  useEffect(() => {
    if (prevActiveTab.current !== activeTab) {
      console.log(`%c[PAGE ProfilePage] 🔄 activeTab: ${prevActiveTab.current} → ${activeTab} @ ${performance.now().toFixed(1)}ms`, 'color: #FF6F00; font-weight: bold');
      prevActiveTab.current = activeTab;
    }
  }, [activeTab]);
  useEffect(() => {
    const had = prevDiscoverContent.current !== null;
    const has = discoverContent !== null;
    if (had !== has) {
      console.log(`%c[PAGE ProfilePage] 📡 discoverContent: ${had ? 'loaded' : 'null'} → ${has ? 'loaded' : 'null'} @ ${performance.now().toFixed(1)}ms`, 'color: #FF6F00; font-weight: bold');
      prevDiscoverContent.current = discoverContent;
    }
  }, [discoverContent]);

  // Restore scroll position after back-navigation from a place detail page
  useEffect(() => {
    const savedY = sessionStorage.getItem('profile_scroll_y');
    if (savedY) {
      sessionStorage.removeItem('profile_scroll_y');
      // Delay to let content render before scrolling
      requestAnimationFrame(() => {
        window.scrollTo(0, parseInt(savedY, 10));
      });
    }
  }, []);

  // DB is the source of truth — show loading until hydration completes,
  // then use the real profile (no hardcoded demo fallback for auth users)
  const profile = generatedProfile || TASTE_PROFILE;
  const userName = lifeContext?.firstName || user?.email?.split('@')[0] || '';
  const signalCount = allSignals?.length || 0;

  // Build numeric profile for mosaic visualization from radar data
  const numericProfile: NumericProfile = useMemo(() => {
    const result: NumericProfile = { Design: 0.5, Atmosphere: 0.5, Character: 0.5, Service: 0.5, FoodDrink: 0.5, Setting: 0.5, Wellness: 0.5, Sustainability: 0.5 };
    const radarData = (profile as { radarData?: { axis: string; value: number }[] }).radarData;
    if (radarData) {
      for (const r of radarData) {
        if (r.axis in result) {
          result[r.axis as keyof NumericProfile] = Math.max(result[r.axis as keyof NumericProfile], r.value);
        }
      }
    }
    return result;
  }, [profile]);

  // Fire-and-forget: ensure hardcoded fallback places have enrichment triggered
  const triggerHardcodedEnrichment = useCallback(() => {
    // Collect all unique places from hardcoded constants
    const seen = new Set<string>();
    const places: Array<{ googlePlaceId?: string; name: string; location: string }> = [];

    function add(name?: string, location?: string, googlePlaceId?: string) {
      if (!name) return;
      const key = googlePlaceId || `${name}||${location || ''}`;
      if (seen.has(key)) return;
      seen.add(key);
      places.push({ googlePlaceId, name, location: location || '' });
    }

    for (const c of BECAUSE_YOU_CARDS) add(c.place, c.location, c.googlePlaceId);
    for (const p of SIGNAL_THREAD.places) add(p.name, p.location, p.googlePlaceId);
    add(TASTE_TENSION.resolvedBy.name, TASTE_TENSION.resolvedBy.location, TASTE_TENSION.resolvedBy.googlePlaceId);
    for (const p of WEEKLY_COLLECTION.places) add(p.name, p.location, p.googlePlaceId);
    for (const b of MOOD_BOARDS) {
      for (const p of b.places) add(p.name, p.location, p.googlePlaceId);
    }
    add(DEEP_MATCH.name, DEEP_MATCH.location, DEEP_MATCH.googlePlaceId);
    add(STRETCH_PICK.name, STRETCH_PICK.location, STRETCH_PICK.googlePlaceId);
    for (const r of SUMMER_RECS) add(r.name, r.location, r.googlePlaceId);
    if (places.length > 0) {
      apiFetch('/api/profile/discover/ensure-places', {
        method: 'POST',
        body: JSON.stringify({ places }),
      }).catch(() => {}); // fire-and-forget
    }
  }, []);

  // Generate discover content from real profile
  const fetchDiscoverContent = useCallback(async () => {
    if (!generatedProfile) return;

    // Check localStorage cache (with 2-hour TTL)
    const cacheKey = `terrazzo_discover_${generatedProfile.overallArchetype}`;
    try {
      const cached = localStorage.getItem(cacheKey);
      if (cached) {
        const parsed = JSON.parse(cached);
        const cachedAt = parsed._cachedAt as number | undefined;
        if (cachedAt && (Date.now() - cachedAt) < DISCOVER_CACHE_TTL_MS) {
          setDiscoverContent(parsed);
          return;
        }
        // Stale cache — remove and refetch
        localStorage.removeItem(cacheKey);
      }
    } catch { /* ignore cache errors */ }

    setIsLoadingDiscover(true);
    try {
      const data = await apiFetch<DiscoverContent>('/api/profile/discover', {
        method: 'POST',
        body: JSON.stringify({
          userProfile: generatedProfile,
          lifeContext: lifeContext || undefined,
        }),
      });
      setDiscoverContent(data);
      // Store with timestamp for TTL
      try {
        const toCache = { ...data, _cachedAt: Date.now() };
        localStorage.setItem(cacheKey, JSON.stringify(toCache));
      } catch { /* quota exceeded */ }
    } catch {
      // Silently fall back to hardcoded content — trigger enrichment for hardcoded places
      triggerHardcodedEnrichment();
    } finally {
      setIsLoadingDiscover(false);
    }
  }, [generatedProfile, lifeContext]);

  useEffect(() => {
    fetchDiscoverContent();
  }, [fetchDiscoverContent]);

  // ─── Infinite scroll: fetch additional feed pages on demand ───

  // Reset when base content changes (e.g. profile resynthesis)
  useEffect(() => {
    setExtraPages([]);
    setFeedPageIndex(1);
    setHasMoreContent(true);
  }, [discoverContent]);

  const fetchMoreContent = useCallback(async () => {
    // Need either a real profile or at least existing discover content to continue from
    const userProfile = generatedProfile || (discoverContent ? profile : null);
    if (!userProfile || isLoadingMore || !hasMoreContent) return;

    setIsLoadingMore(true);
    try {
      const data = await apiFetch<DiscoverContent>('/api/profile/discover/more', {
        method: 'POST',
        body: JSON.stringify({
          userProfile,
          lifeContext: lifeContext || undefined,
          pageIndex: feedPageIndex,
          excludePlaces: collectAllPlaceNames(discoverContent, extraPages),
        }),
      });
      setExtraPages(prev => [...prev, data]);
      setFeedPageIndex(prev => prev + 1);
      if (feedPageIndex >= 15) setHasMoreContent(false);
    } catch {
      setHasMoreContent(false);
    } finally {
      setIsLoadingMore(false);
    }
  }, [generatedProfile, profile, discoverContent, lifeContext, isLoadingMore, hasMoreContent, feedPageIndex, extraPages]);

  // IntersectionObserver triggers fetchMoreContent when user scrolls near feed bottom
  useEffect(() => {
    const sentinel = sentinelRef.current;
    if (!sentinel) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) {
          fetchMoreContent();
        }
      },
      { rootMargin: '600px' }
    );

    observer.observe(sentinel);
    return () => observer.disconnect();
  }, [fetchMoreContent]);

  const handleSettingTap = (action: string) => {
    const next = expandedSection === action ? null : action;
    setExpandedSection(next);
    // Fetch email status when accounts panel opens
    if (next === 'accounts' && !emailStatus) fetchEmailStatus();
    // Fetch import history when accounts or history panel opens (needed for Google Maps status)
    if ((next === 'accounts' || next === 'history') && importHistory.length === 0) fetchImportHistory();
  };

  const fetchEmailStatus = async () => {
    setEmailLoading(true);
    try {
      const data = await apiFetch<{ connected: boolean; email?: string; provider?: string; connectedAt?: string }>('/api/email/status');
      setEmailStatus(data);
      // If connected and we don't already have scan state, check for latest scan
      if (data.connected && scanState === 'idle') {
        resumeScan();
      }
    } catch { setEmailStatus({ connected: false }); }
    finally { setEmailLoading(false); }
  };

  const handleDisconnect = async () => {
    try {
      await apiFetch('/api/auth/nylas/disconnect', { method: 'POST' });
      setEmailStatus({ connected: false });
      useEmailScanStore.getState().reset();
    } catch (err) { console.error('Disconnect failed:', err); }
  };

  const handleScanNow = () => {
    startScan();
  };

  const handleDebugEmail = async () => {
    try {
      const data = await apiFetch<Record<string, unknown>>('/api/email/debug');
      console.log('[terrazzo] EMAIL DEBUG:', JSON.stringify(data, null, 2));
      alert(`Debug result — check console.\nRecent emails: ${JSON.stringify((data.tests as Record<string, unknown> & { recentMessages: { count: number } })?.recentMessages?.count ?? 'error')}`);
    } catch (err) {
      console.error('[terrazzo] Debug failed:', err);
      alert('Debug failed — check console');
    }
  };

  const fetchImportHistory = async () => {
    setHistoryLoading(true);
    try {
      const data = await apiFetch<{ timeline: Array<{ id: string; type: 'email-scan' | 'url-import' | 'manual'; date: string; title: string; subtitle: string; count: number; status?: string; scanId?: string }> }>('/api/import-history');
      setImportHistory(data.timeline || []);
    } catch { /* ignore */ }
    finally { setHistoryLoading(false); }
  };

  const handleResynthesis = async () => {
    setIsResynthesizing(true);
    setResynthesisResult(null);
    const ok = await triggerResynthesis();
    setIsResynthesizing(false);
    setResynthesisResult(ok ? 'success' : 'error');
    // Clear the discover cache so it regenerates with new profile
    if (ok) {
      try {
        const keys = Object.keys(localStorage).filter(k => k.startsWith('terrazzo_discover_'));
        keys.forEach(k => localStorage.removeItem(k));
      } catch { /* ignore */ }
      // Re-fetch discover content
      fetchDiscoverContent();
    }
    // Auto-clear the result badge after 4s
    setTimeout(() => setResynthesisResult(null), 4000);
  };

  const handleRedoOnboarding = () => {
    resetForRedo();
    router.push('/onboarding');
  };

  // Wait for DB hydration before rendering profile data
  if (!dbHydrated) {
    return <BrandLoader message="Loading your profile…" />;
  }

  // Full-screen overlays
  if (showWrapped) {
    return <WrappedExperience onClose={() => setShowWrapped(false)} />;
  }
  if (showMosaic) {
    return <ExpandMosaicView onClose={() => setShowMosaic(false)} />;
  }

  /* ─── Shared header + tab component ─── */
  const headerBlock = (
    <>
      <div className="flex items-start justify-between mb-5">
        <div className="flex items-center gap-3">
          <div
            className="w-12 h-12 rounded-full flex items-center justify-center"
            style={{ background: 'rgba(238,113,109,0.1)' }}
          >
            <PerriandIcon name="profile" size={24} color="var(--t-honey)" />
          </div>
          <div>
            <div className="text-[15px] font-semibold" style={{ color: TEXT.primary }}>{userName}</div>
            <div className="text-[11px]" style={{ color: TEXT.secondary }}>{profile.overallArchetype}</div>
          </div>
        </div>
        <TerrazzoMosaic profile={numericProfile} size="xs" />
      </div>

      {/* Inner tab toggle */}
      <div
        className="flex gap-1 p-0.5 rounded-lg mb-1"
        style={{ background: 'var(--t-linen)' }}
      >
        {(['discover', 'profile'] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className="flex-1 py-1.5 px-2 rounded-md text-[11px] font-medium transition-all"
            style={{
              background: activeTab === tab ? 'white' : 'transparent',
              color: activeTab === tab ? 'var(--t-ink)' : INK['85'],
              border: 'none',
              cursor: 'pointer',
              fontFamily: FONT.sans,
              boxShadow: activeTab === tab ? '0 1px 3px rgba(0,0,0,0.06)' : 'none',
            }}
          >
            {tab === 'discover' ? 'Discover' : 'My Profile'}
          </button>
        ))}
      </div>
    </>
  );

  const discoverFeed = (
    <>
      {/* Initial feed — all sections visible */}
      <EditorialLetterSection letter={discoverContent?.editorialLetter} />
      <BecauseYouSection cards={discoverContent?.becauseYouCards} />
      <SignalThreadSection thread={discoverContent?.signalThread} />
      <TasteTensionSection tension={discoverContent?.tasteTension} />
      <WeeklyEditSection collection={discoverContent?.weeklyCollection} />
      <MoodBoardSection boards={discoverContent?.moodBoards} />
      <DeepMatchSection match={discoverContent?.deepMatch} />
      <StretchPickSection stretch={discoverContent?.stretchPick} />
      <ContextModeSection recs={discoverContent?.contextRecs} contextLabel={discoverContent?.contextLabel} />
      <VocabTeaser profile={profile} />

      {/* Extra pages loaded via infinite scroll */}
      {extraPages.map((page, i) => (
        <div key={`extra-page-${i}`}>
          {/* Subtle divider between pages */}
          <div className="flex items-center gap-4 my-10 px-4">
            <div className="flex-1 h-px" style={{ background: 'var(--t-linen)' }} />
            <span style={{ fontFamily: FONT.mono, fontSize: 9, color: TEXT.secondary, textTransform: 'uppercase', letterSpacing: '0.15em' }}>
              More for you
            </span>
            <div className="flex-1 h-px" style={{ background: 'var(--t-linen)' }} />
          </div>

          {/* Render whichever sections this page contains */}
          {page.editorialLetter && <EditorialLetterSection letter={page.editorialLetter} />}
          {page.becauseYouCards && <BecauseYouSection cards={page.becauseYouCards} />}
          {page.signalThread && <SignalThreadSection thread={page.signalThread} />}
          {page.tasteTension && <TasteTensionSection tension={page.tasteTension} />}
          {page.weeklyCollection && <WeeklyEditSection collection={page.weeklyCollection} />}
          {page.moodBoards && <MoodBoardSection boards={page.moodBoards} />}
          {page.deepMatch && <DeepMatchSection match={page.deepMatch} />}
          {page.stretchPick && <StretchPickSection stretch={page.stretchPick} />}
          {page.contextRecs && <ContextModeSection recs={page.contextRecs} contextLabel={page.contextLabel} />}
        </div>
      ))}

      {/* Sentinel + loading indicator for infinite scroll */}
      {hasMoreContent && (
        <div
          ref={sentinelRef}
          className="flex flex-col items-center justify-center py-10 gap-2"
          style={{ minHeight: 80 }}
        >
          {isLoadingMore ? (
            <>
              <div className="animate-spin w-5 h-5 rounded-full border-2" style={{ borderColor: 'var(--t-linen)', borderTopColor: 'var(--t-honey)' }} />
              <span style={{ fontFamily: FONT.mono, fontSize: 10, color: TEXT.secondary, letterSpacing: '0.05em' }}>
                Curating more…
              </span>
            </>
          ) : (
            <span
              className="animate-pulse"
              style={{ fontFamily: FONT.mono, fontSize: 10, color: TEXT.secondary, letterSpacing: '0.05em' }}
            >
              Scroll for more
            </span>
          )}
        </div>
      )}
    </>
  );

  /* ─── Desktop Profile layout ─── */
  if (isDesktop) {
    return (
      <PageTransition className="min-h-screen" style={{ background: 'var(--t-cream)' }}>
        <DesktopNav />
        <div style={{ maxWidth: 960, margin: '0 auto', padding: '36px 48px 48px' }}>
          {/* Profile header card — full width, scrolls with page */}
          <div
            className="rounded-2xl overflow-hidden mb-8"
            style={{
              background: '#ffffff',
              border: '1px solid var(--t-linen)',
              boxShadow: '0 2px 8px rgba(0,0,0,0.03)',
            }}
          >
            {/* Dark teal header section — editorial pattern */}
            <div style={{ background: 'var(--t-dark-teal)', padding: '24px 32px 20px' }}>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div
                    className="w-14 h-14 rounded-full flex items-center justify-center flex-shrink-0"
                    style={{ background: 'rgba(224,165,1,0.15)' }}
                  >
                    <PerriandIcon name="profile" size={28} color={COLOR.ochre} />
                  </div>
                  <div className="min-w-0">
                    <div className="text-[15px] font-semibold" style={{ color: '#ffffff', fontFamily: FONT.sans }}>{userName}</div>
                    <div className="text-[11px]" style={{ color: 'rgba(255,255,255,0.72)', fontFamily: FONT.mono }}>{profile.overallArchetype}</div>
                  </div>
                </div>
                <div className="flex items-center gap-5">
                  <TerrazzoMosaic profile={numericProfile} size="xs" />
                  {/* Tabs */}
                  <div
                    className="flex gap-1 p-0.5 rounded-lg"
                    style={{ background: 'rgba(255,255,255,0.08)' }}
                  >
                    {(['discover', 'profile'] as const).map(tab => (
                      <button
                        key={tab}
                        onClick={() => setActiveTab(tab)}
                        className="py-1.5 px-4 rounded-md text-[11px] font-medium transition-all"
                        style={{
                          background: activeTab === tab ? COLOR.ochre : 'transparent',
                          color: activeTab === tab ? 'white' : 'rgba(255,255,255,0.8)',
                          border: 'none',
                          cursor: 'pointer',
                          fontFamily: FONT.sans,
                          boxShadow: activeTab === tab ? '0 2px 6px rgba(0,0,0,0.15)' : 'none',
                        }}
                      >
                        {tab === 'discover' ? 'Discover' : 'My Profile'}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Bottom bar: stats + CTAs — plain pattern with coral gradient */}
            <div className="flex items-center gap-6 px-8 py-4" style={{ background: 'linear-gradient(145deg, rgba(238,113,109,0.06) 0%, rgba(238,113,109,0.12) 100%)' }}>
              {/* Quick stats */}
              <div className="flex items-center gap-6">
                <div className="text-center">
                  <div style={{ fontFamily: FONT.mono, fontSize: 18, fontWeight: 700, color: COLOR.darkTeal }}>{signalCount}</div>
                  <div style={{ fontFamily: FONT.mono, fontSize: 9, color: COLOR.coral, textTransform: 'uppercase', letterSpacing: '0.1em' }}>Signals</div>
                </div>
                <div className="text-center">
                  <div style={{ fontFamily: FONT.mono, fontSize: 18, fontWeight: 700, color: COLOR.darkTeal }}>{profile.contradictions?.length || 0}</div>
                  <div style={{ fontFamily: FONT.mono, fontSize: 9, color: COLOR.coral, textTransform: 'uppercase', letterSpacing: '0.1em' }}>Tensions</div>
                </div>
                <div className="text-center">
                  <div style={{ fontFamily: FONT.mono, fontSize: 18, fontWeight: 700, color: COLOR.darkTeal }}>{Object.values(profile.microTasteSignals || {}).flat().length || 0}</div>
                  <div style={{ fontFamily: FONT.mono, fontSize: 9, color: COLOR.coral, textTransform: 'uppercase', letterSpacing: '0.1em' }}>Terms</div>
                </div>
              </div>

              <div className="h-8 w-px" style={{ background: 'var(--t-linen)' }} />

              {/* CTAs */}
              <div className="flex items-center gap-3 flex-1">
                <SafeMotionButton
                  onClick={() => setShowWrapped(true)}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl cursor-pointer border-none transition-all hover:opacity-90"
                  style={{ background: COLOR.darkTeal }}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <span className="text-[11px] font-semibold" style={{ color: '#ffffff', fontFamily: FONT.sans }}>
                    Taste Dossier
                  </span>
                  <span className="text-[10px]" style={{ color: 'rgba(255,255,255,0.6)', fontFamily: FONT.mono }}>→</span>
                </SafeMotionButton>

                <SafeMotionButton
                  onClick={() => setShowMosaic(true)}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl cursor-pointer border-none transition-all hover:opacity-90"
                  style={{ background: 'linear-gradient(135deg, rgba(238,113,109,0.15) 0%, rgba(238,113,109,0.06) 100%)', border: `1px solid ${INK['06']}` }}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <span className="text-[11px] font-semibold" style={{ color: COLOR.darkTeal, fontFamily: FONT.sans }}>
                    Expand Mosaic
                  </span>
                  <span className="text-[10px]" style={{ color: COLOR.navy, fontFamily: FONT.mono }}>→</span>
                </SafeMotionButton>
              </div>

              {/* Settings gear */}
              <div className="flex items-center gap-3">
                {SETTINGS_LINKS.map(({ label, action }) => (
                  <div key={action} className="relative">
                    <button
                      onClick={() => handleSettingTap(action)}
                      className="text-[11px] px-3 py-1.5 rounded-lg cursor-pointer transition-all"
                      style={{
                        fontSize: 11,
                        color: expandedSection === action ? COLOR.darkTeal : COLOR.navy,
                        fontFamily: FONT.sans,
                        background: expandedSection === action ? 'rgba(238,113,109,0.06)' : 'transparent',
                        border: 'none',
                      }}
                    >
                      {label}
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Settings expanded panels — shown below header when active */}
          {expandedSection && (
            <div className="mb-6 rounded-2xl px-6 py-4" style={{ background: 'white', border: '1px solid var(--t-linen)', boxShadow: '0 1px 4px rgba(0,0,0,0.04)' }}>
              {expandedSection === 'accounts' && (
                <div style={{ fontSize: 12 }}>
                  <h4 className="text-[10px] uppercase tracking-[0.15em] mb-3" style={{ color: INK['50'], fontFamily: FONT.mono, fontWeight: 700 }}>Connected Accounts</h4>
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <PerriandIcon name="email" size={12} color="var(--t-ink)" />
                      <span style={{ color: TEXT.primary }}>Gmail</span>
                    </div>
                    {emailLoading ? (
                      <span className="text-[10px]" style={{ color: TEXT.secondary }}>Checking…</span>
                    ) : emailStatus?.connected ? (
                      <span className="text-[10px] px-2.5 py-0.5 rounded-full" style={{ background: 'rgba(146,206,214,0.08)', color: 'var(--t-teal)' }}>Connected</span>
                    ) : (
                      <a href="/api/auth/nylas/connect" className="text-[10px] font-semibold px-2.5 py-0.5 rounded-full" style={{ background: 'var(--t-teal)', color: 'white', textDecoration: 'none' }}>Connect</a>
                    )}
                  </div>
                  {emailStatus?.connected && (
                    <div className="ml-5 mb-3">
                      <span className="text-[10px] block mb-2" style={{ color: TEXT.secondary }}>{emailStatus.email}</span>
                      <div className="flex items-center gap-2 flex-wrap mb-2">
                        <button onClick={handleScanNow} disabled={scanState === 'scanning' || scanState === 'parsing'} className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer" style={{ background: 'var(--t-teal)', color: 'white', opacity: scanState === 'scanning' || scanState === 'parsing' ? 0.7 : 1 }}>
                          {scanState === 'scanning' ? 'Scanning…' : scanState === 'parsing' ? `Parsing${scanResult?.emailsParsed ? ` ${scanResult.emailsParsed}/${scanResult.emailsFound}` : '…'}` : scanState === 'done' ? '✓ Done' : scanState === 'failed' ? 'Retry Scan' : 'Scan Inbox'}
                        </button>
                        <button onClick={handleDebugEmail} className="text-[10px] px-2 py-1 rounded-full border-none cursor-pointer" style={{ background: 'rgba(0,0,0,0.06)', color: TEXT.secondary }}>
                          Debug
                        </button>
                        {scanState === 'parsing' && scanResult && (scanResult.reservationsFound ?? 0) > 0 && (
                          <button onClick={() => router.push('/email/inbox')} className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer" style={{ background: 'var(--t-coral)', color: 'white' }}>
                            Review {scanResult.reservationsFound} so far →
                          </button>
                        )}
                        {scanState === 'done' && scanResult && (scanResult.reservationsFound ?? 0) > 0 && (
                          <button onClick={() => router.push('/email/inbox')} className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer" style={{ background: 'var(--t-coral)', color: 'white' }}>
                            Review {scanResult.reservationsFound} reservations →
                          </button>
                        )}
                        {scanState === 'done' && scanResult && (scanResult.reservationsFound ?? 0) === 0 && (
                          <span className="text-[10px]" style={{ color: TEXT.secondary }}>
                            {scanResult.emailsFound} emails scanned · no reservations found
                          </span>
                        )}
                      </div>
                      <button onClick={handleDisconnect} className="text-[9px] px-2 py-0.5 rounded-full border-none cursor-pointer" style={{ background: 'rgba(238,113,109,0.08)', color: 'var(--t-coral)' }}>Disconnect</button>
                    </div>
                  )}
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <PerriandIcon name="pin" size={12} color="var(--t-ink)" />
                      <span style={{ color: TEXT.primary }}>Google Maps</span>
                    </div>
                    {hasGoogleMapsImport ? (
                      <span className="text-[10px] px-2.5 py-0.5 rounded-full" style={{ background: 'rgba(146,206,214,0.08)', color: 'var(--t-teal)' }}>Imported</span>
                    ) : (
                      <Link href="/onboarding" className="text-[10px] font-semibold px-2.5 py-0.5 rounded-full" style={{ background: 'var(--t-peach)', color: 'var(--t-navy)', textDecoration: 'none' }}>Import</Link>
                    )}
                  </div>
                </div>
              )}
              {expandedSection === 'history' && (
                <div style={{ fontSize: 12 }}>
                  <h4 className="text-[10px] uppercase tracking-[0.15em] mb-3" style={{ color: INK['50'], fontFamily: FONT.mono, fontWeight: 700 }}>Import History</h4>
                  {historyLoading ? (
                    <span className="text-[10px]" style={{ color: TEXT.secondary }}>Loading history…</span>
                  ) : importHistory.length === 0 ? (
                    <span className="text-[10px]" style={{ color: TEXT.secondary }}>No import history yet. Connect Gmail or import from a URL to get started.</span>
                  ) : (
                    <div className="flex flex-col gap-1.5">
                      {importHistory.slice(0, 10).map((item) => (
                        <div key={item.id} className="flex items-center justify-between py-1 cursor-pointer" onClick={() => item.scanId ? router.push('/email/inbox') : undefined}>
                          <div className="flex items-center gap-2 min-w-0">
                            <PerriandIcon name={item.type === 'email-scan' ? 'email' : item.type === 'url-import' ? 'article' : 'manual'} size={10} color={INK['50']} />
                            <span className="text-[11px] truncate" style={{ color: TEXT.primary }}>{item.title}</span>
                          </div>
                          <span className="text-[10px] flex-shrink-0 ml-2" style={{ color: TEXT.secondary }}>{new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>
                        </div>
                      ))}
                      <button onClick={() => router.push('/email/inbox')} className="text-[10px] font-medium mt-1 bg-transparent border-none cursor-pointer text-left" style={{ color: TEXT.accent }}>View email reservations →</button>
                    </div>
                  )}
                </div>
              )}
              {expandedSection === 'notifications' && (
                <div>
                  <h4 className="text-[10px] uppercase tracking-[0.15em] mb-3" style={{ color: INK['50'], fontFamily: FONT.mono, fontWeight: 700 }}>Notifications</h4>
                  <span className="text-[11px]" style={{ color: TEXT.secondary }}>Notification preferences coming soon.</span>
                </div>
              )}
              {expandedSection === 'about' && (
                <div>
                  <h4 className="text-[10px] uppercase tracking-[0.15em] mb-3" style={{ color: INK['50'], fontFamily: FONT.mono, fontWeight: 700 }}>About</h4>
                  <span className="text-[11px]" style={{ color: TEXT.secondary }}>Terrazzo v0.1 — Your taste-driven travel companion.</span>
                </div>
              )}
              <div className="flex items-center gap-4 mt-4 pt-3" style={{ borderTop: '1px solid var(--t-linen)' }}>
                <button
                  onClick={handleRedoOnboarding}
                  className="flex items-center gap-1.5 bg-transparent border-none cursor-pointer"
                  style={{ fontSize: 11, color: 'var(--t-coral)', fontFamily: FONT.sans }}
                >
                  <PerriandIcon name="discover" size={10} color="var(--t-coral)" />
                  Redo Onboarding
                </button>
                <button
                  onClick={handleResynthesis}
                  disabled={isResynthesizing}
                  className="flex items-center gap-1.5 bg-transparent border-none cursor-pointer"
                  style={{ fontSize: 11, color: isResynthesizing ? INK['30'] : 'var(--t-teal)', fontFamily: FONT.sans, opacity: isResynthesizing ? 0.6 : 1 }}
                >
                  <PerriandIcon name="sparkle" size={10} color={isResynthesizing ? INK['30'] : 'var(--t-teal)'} />
                  {isResynthesizing ? 'Re-synthesizing…' : 'Refresh Taste Profile'}
                  {resynthesisResult === 'success' && <span style={{ color: 'var(--t-teal)', marginLeft: 4 }}>✓</span>}
                  {resynthesisResult === 'error' && <span style={{ color: '#c44', marginLeft: 4 }}>Failed</span>}
                </button>
                {isAuthenticated ? (
                  <div className="ml-auto flex items-center gap-2">
                    <span className="text-[10px]" style={{ color: TEXT.secondary }}>{user?.email}</span>
                    <button onClick={signOut} className="text-[10px] font-medium px-2 py-1 rounded-full cursor-pointer" style={{ background: 'rgba(238,113,109,0.08)', color: 'var(--t-coral)', border: 'none', fontFamily: FONT.sans }}>Sign out</button>
                  </div>
                ) : (
                  <Link href="/login" className="ml-auto text-[11px] font-semibold" style={{ color: 'var(--t-teal)', textDecoration: 'none' }}>Sign in →</Link>
                )}
              </div>
            </div>
          )}

          {/* Content feed — full width */}
          <div>
            {activeTab === 'discover' ? discoverFeed : (
              <>
                <ProfileDeepDive />
              </>
            )}
          </div>
        </div>
      </PageTransition>
    );
  }

  /* ─── Mobile Profile layout (unchanged) ─── */
  return (
    <PageTransition className="min-h-screen" style={{ background: 'var(--t-cream)', maxWidth: 480, margin: '0 auto', paddingBottom: 64 }}>
      <div className="px-5 pt-6 pb-2">
        {headerBlock}
      </div>

      {activeTab === 'discover' ? (
        discoverFeed
      ) : (
        /* ═══════════ MY PROFILE ═══════════ */
        <>
          {/* Action buttons */}
          <div className="px-5 pt-2 pb-4 flex flex-col gap-2.5">
            <SafeMotionButton
              onClick={() => setShowWrapped(true)}
              className="w-full flex items-center justify-between p-3.5 rounded-xl cursor-pointer border-none transition-all hover:opacity-90"
              style={{ background: 'var(--t-navy)' }}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <div className="flex flex-col items-start gap-0.5">
                <span
                  className="text-[12px] font-semibold"
                  style={{ color: 'var(--t-cream)', fontFamily: FONT.sans }}
                >
                  Your Taste Dossier
                </span>
                <span
                  className="text-[9px]"
                  style={{ color: 'rgba(251,245,236,0.45)', fontFamily: FONT.mono }}
                >
                  {signalCount > 0 ? `${signalCount} signals` : 'Your signals'} · {profile.contradictions?.length || 0} tensions
                </span>
              </div>
              <span
                className="text-[10px] px-2.5 py-1 rounded-full font-semibold"
                style={{
                  background: 'rgba(251,245,236,0.15)',
                  color: 'var(--t-cream)',
                  fontFamily: FONT.mono,
                }}
              >
                Replay →
              </span>
            </SafeMotionButton>

            <SafeMotionButton
              onClick={() => setShowMosaic(true)}
              className="w-full flex items-center justify-between p-3.5 rounded-xl cursor-pointer border-none transition-all hover:opacity-90"
              style={{
                background: 'linear-gradient(135deg, #e8dcc8 0%, #f5f0e6 100%)',
                border: '1px solid rgba(238,113,109,0.12)',
              }}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <div className="flex flex-col items-start gap-0.5">
                <span
                  className="text-[12px] font-semibold"
                  style={{ color: TEXT.primary, fontFamily: FONT.sans }}
                >
                  Expand Your Mosaic
                </span>
                <span
                  className="text-[9px]"
                  style={{ color: TEXT.secondary, fontFamily: FONT.mono }}
                >
                  Quick questions that sharpen your matches
                </span>
              </div>
              <span
                className="text-[10px] px-2.5 py-1 rounded-full font-semibold"
                style={{
                  background: 'rgba(0,42,85,0.06)',
                  color: TEXT.primary,
                  fontFamily: FONT.mono,
                }}
              >
                Play →
              </span>
            </SafeMotionButton>
          </div>

          {/* Deep Dive */}
          <ProfileDeepDive />

          {/* Settings */}
          <div className="px-4 py-6 mx-4 mt-2 rounded-2xl" style={{ background: 'white', border: '1px solid var(--t-linen)', boxShadow: '0 1px 4px rgba(0,0,0,0.04)' }}>
            <h3
              className="text-[10px] uppercase tracking-[0.2em] mb-4"
              style={{ color: '#8a6a2a', fontFamily: FONT.mono, fontWeight: 700 }}
            >
              Settings
            </h3>
            <div className="flex flex-col gap-2">
              {SETTINGS_LINKS.map(({ label, action }) => (
                <div key={action}>
                  <div
                    onClick={() => handleSettingTap(action)}
                    className="flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all"
                    style={{ background: expandedSection === action ? 'rgba(238,113,109,0.06)' : INK['03'] }}
                  >
                    <span className="text-[12px]" style={{ color: TEXT.primary }}>{label}</span>
                    <span style={{ color: TEXT.secondary, transform: expandedSection === action ? 'rotate(90deg)' : 'none', transition: 'transform 0.2s' }}>→</span>
                  </div>
                  {expandedSection === 'accounts' && action === 'accounts' && (
                    <div className="px-3 py-3 mt-1 rounded-xl" style={{ background: 'rgba(107,139,154,0.05)' }}>
                      {/* Gmail row — dynamic */}
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <PerriandIcon name="email" size={12} color="var(--t-ink)" />
                          <span className="text-[11px]" style={{ color: TEXT.primary }}>Gmail</span>
                        </div>
                        {emailLoading ? (
                          <span className="text-[10px]" style={{ color: TEXT.secondary }}>Checking…</span>
                        ) : emailStatus?.connected ? (
                          <span className="text-[10px] px-2.5 py-1 rounded-full" style={{ background: 'rgba(58,128,136,0.08)', color: 'var(--t-dark-teal)' }}>
                            Connected
                          </span>
                        ) : (
                          <a
                            href="/api/auth/nylas/connect"
                            className="text-[10px] font-semibold px-2.5 py-1 rounded-full"
                            style={{ background: 'var(--t-dark-teal)', color: 'white', textDecoration: 'none' }}
                          >
                            Connect
                          </a>
                        )}
                      </div>
                      {/* Connected: show email, scan, disconnect */}
                      {emailStatus?.connected && (
                        <div className="ml-5 mb-3">
                          <span className="text-[10px] block mb-2" style={{ color: TEXT.secondary }}>
                            {emailStatus.email}
                          </span>
                          <div className="flex items-center gap-2 flex-wrap mb-2">
                            <button
                              onClick={handleScanNow}
                              disabled={scanState === 'scanning' || scanState === 'parsing'}
                              className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer"
                              style={{ background: '#3a8088', color: 'white', opacity: scanState === 'scanning' || scanState === 'parsing' ? 0.7 : 1 }}
                            >
                              {scanState === 'scanning' ? 'Scanning…' : scanState === 'parsing' ? `Parsing${scanResult?.emailsParsed ? ` ${scanResult.emailsParsed}/${scanResult.emailsFound}` : '…'}` : scanState === 'done' ? '✓ Done' : scanState === 'failed' ? 'Retry Scan' : 'Scan Inbox'}
                            </button>
                            <button onClick={handleDebugEmail} className="text-[10px] px-2 py-1 rounded-full border-none cursor-pointer" style={{ background: 'rgba(0,0,0,0.06)', color: TEXT.secondary }}>
                              Debug
                            </button>
                            {scanState === 'parsing' && scanResult && (scanResult.reservationsFound ?? 0) > 0 && (
                              <button
                                onClick={() => router.push('/email/inbox')}
                                className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer"
                                style={{ background: 'var(--t-honey)', color: 'white' }}
                              >
                                Review {scanResult.reservationsFound} so far →
                              </button>
                            )}
                            {scanState === 'done' && scanResult && (scanResult.reservationsFound ?? 0) > 0 && (
                              <button
                                onClick={() => router.push('/email/inbox')}
                                className="text-[10px] font-semibold px-3 py-1.5 rounded-full border-none cursor-pointer"
                                style={{ background: 'var(--t-honey)', color: 'white' }}
                              >
                                Review {scanResult.reservationsFound} reservations →
                              </button>
                            )}
                            {scanState === 'done' && scanResult && (scanResult.reservationsFound ?? 0) === 0 && (
                              <span className="text-[10px]" style={{ color: TEXT.secondary }}>
                                {scanResult.emailsFound} emails scanned · no reservations found
                              </span>
                            )}
                          </div>
                          <button
                            onClick={handleDisconnect}
                            className="text-[9px] px-2 py-0.5 rounded-full border-none cursor-pointer"
                            style={{ background: 'rgba(196,80,32,0.08)', color: '#c45020' }}
                          >
                            Disconnect
                          </button>
                        </div>
                      )}
                      {/* Google Maps row — static */}
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <PerriandIcon name="pin" size={12} color="var(--t-ink)" />
                          <span className="text-[11px]" style={{ color: TEXT.primary }}>Google Maps</span>
                        </div>
                        <span className="text-[10px] px-2.5 py-1 rounded-full" style={{ background: 'rgba(58,128,136,0.08)', color: 'var(--t-dark-teal)' }}>
                          Via import
                        </span>
                      </div>
                    </div>
                  )}
                  {/* Import History panel */}
                  {expandedSection === 'history' && action === 'history' && (
                    <div className="px-3 py-3 mt-1 rounded-xl" style={{ background: 'rgba(107,139,154,0.05)' }}>
                      {historyLoading ? (
                        <span className="text-[10px]" style={{ color: TEXT.secondary }}>Loading history…</span>
                      ) : importHistory.length === 0 ? (
                        <span className="text-[10px]" style={{ color: TEXT.secondary }}>
                          No import history yet. Connect Gmail or import from a URL to get started.
                        </span>
                      ) : (
                        <div className="flex flex-col gap-2">
                          {importHistory.slice(0, 15).map((item) => (
                            <div
                              key={item.id}
                              className="flex items-center justify-between py-1.5 cursor-pointer"
                              onClick={() => item.scanId ? router.push('/email/inbox') : undefined}
                            >
                              <div className="flex items-center gap-2 min-w-0">
                                <PerriandIcon
                                  name={item.type === 'email-scan' ? 'email' : item.type === 'url-import' ? 'article' : 'manual'}
                                  size={10}
                                  color={INK['50']}
                                />
                                <div className="min-w-0">
                                  <span className="text-[10px] font-medium block truncate" style={{ color: TEXT.primary }}>
                                    {item.title}
                                  </span>
                                  <span className="text-[9px] block" style={{ color: TEXT.secondary }}>
                                    {item.subtitle}
                                  </span>
                                </div>
                              </div>
                              <span className="text-[9px] flex-shrink-0 ml-2" style={{ color: TEXT.secondary }}>
                                {new Date(item.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                              </span>
                            </div>
                          ))}
                          {/* Link to staging inbox */}
                          <button
                            onClick={() => router.push('/email/inbox')}
                            className="text-[10px] font-medium mt-1 bg-transparent border-none cursor-pointer text-left"
                            style={{ color: TEXT.accent }}
                          >
                            View email reservations →
                          </button>
                        </div>
                      )}
                    </div>
                  )}
                  {expandedSection === 'notifications' && action === 'notifications' && (
                    <div className="px-3 py-3 mt-1 rounded-xl text-[11px]" style={{ background: 'rgba(107,139,154,0.05)', color: TEXT.secondary }}>
                      Notification preferences will be available in a future update.
                    </div>
                  )}
                  {expandedSection === 'about' && action === 'about' && (
                    <div className="px-3 py-3 mt-1 rounded-xl text-[11px]" style={{ background: 'rgba(107,139,154,0.05)', color: TEXT.secondary }}>
                      Terrazzo v0.1 — Your taste-driven travel companion. Built with Forme Libere design principles.
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Redo Onboarding */}
            <button
              onClick={handleRedoOnboarding}
              className="w-full flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all mt-2"
              style={{
                background: 'rgba(232,115,58,0.06)',
                border: '1px dashed rgba(232,115,58,0.2)',
              }}
            >
              <div className="flex items-center gap-2">
                <PerriandIcon name="discover" size={12} color="var(--t-coral)" />
                <span className="text-[12px] font-medium" style={{ color: 'var(--t-coral)' }}>
                  Redo Onboarding
                </span>
              </div>
              <span style={{ color: '#c45020', fontSize: 12 }}>→</span>
            </button>

            {/* Refresh Taste Profile */}
            <button
              onClick={handleResynthesis}
              disabled={isResynthesizing}
              className="w-full flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all mt-2"
              style={{
                background: isResynthesizing ? 'rgba(58,128,136,0.03)' : 'rgba(58,128,136,0.06)',
                border: '1px dashed rgba(58,128,136,0.2)',
                opacity: isResynthesizing ? 0.7 : 1,
              }}
            >
              <div className="flex items-center gap-2">
                <PerriandIcon name="sparkle" size={12} color="var(--t-teal)" />
                <span className="text-[12px] font-medium" style={{ color: 'var(--t-teal)' }}>
                  {isResynthesizing ? 'Re-synthesizing…' : 'Refresh Taste Profile'}
                </span>
                {resynthesisResult === 'success' && <span style={{ color: 'var(--t-teal)', fontSize: 12 }}>✓ Updated</span>}
                {resynthesisResult === 'error' && <span style={{ color: '#c44', fontSize: 12 }}>Failed</span>}
              </div>
              {!isResynthesizing && !resynthesisResult && (
                <span style={{ color: 'var(--t-dark-teal)', fontSize: 12 }}>→</span>
              )}
            </button>

            {/* Account / Sign In-Out */}
            <div className="mt-4 p-3 rounded-xl" style={{ background: INK['03'] }}>
              {isAuthenticated ? (
                <div className="flex items-center justify-between">
                  <div>
                    <span className="text-[11px]" style={{ color: TEXT.secondary, fontFamily: FONT.sans }}>
                      Signed in as
                    </span>
                    <span className="text-[12px] ml-1 font-medium" style={{ color: TEXT.primary, fontFamily: FONT.sans }}>
                      {user?.email}
                    </span>
                  </div>
                  <button
                    onClick={signOut}
                    className="text-[11px] font-medium px-3 py-1.5 rounded-full cursor-pointer"
                    style={{
                      background: 'rgba(238,113,109,0.08)',
                      color: 'var(--t-coral)',
                      border: 'none',
                      fontFamily: FONT.sans,
                    }}
                  >
                    Sign out
                  </button>
                </div>
              ) : (
                <div className="flex items-center justify-between">
                  <span className="text-[11px]" style={{ color: TEXT.secondary, fontFamily: FONT.sans }}>
                    Sign in to save your places and trips
                  </span>
                  <Link
                    href="/login"
                    className="text-[11px] font-semibold px-3 py-1.5 rounded-full"
                    style={{
                      background: 'var(--t-teal)',
                      color: 'white',
                      textDecoration: 'none',
                      fontFamily: FONT.sans,
                    }}
                  >
                    Sign in
                  </Link>
                </div>
              )}
            </div>
          </div>
        </>
      )}

      <TabBar />
    </PageTransition>
  );
}


// ═══════════════════════════════════════════
// DISCOVER FEED SECTIONS — Editorial Intelligence
// ═══════════════════════════════════════════

function SectionLabel({ children, color = 'var(--t-coral)' }: { children: React.ReactNode; color?: string }) {
  return (
    <div
      className="text-[10px] uppercase tracking-[0.2em] font-bold"
      style={{ color, fontFamily: FONT.mono }}
    >
      {children}
    </div>
  );
}

// ── EDITORIAL LETTER — The opening essay ──
function EditorialLetterSection({ letter }: { letter?: EditorialLetter }) {
  const l = letter || EDITORIAL_LETTER;
  return (
    <SafeMotionDiv

      className="px-5 pt-5 pb-6 rounded-2xl"
      style={{ background: 'var(--t-dark-teal)' }}
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <div className="mb-4">
        <div className="flex items-center gap-2 mb-4">
          <SafeMotionDiv
            className="w-5 h-[1px]"
            style={{ background: 'var(--t-light-yellow)' }}
            initial={{ scaleX: 0 }}
            whileInView={{ scaleX: 1 }}
            transition={{ duration: 0.8, delay: 0.1 }}
            viewport={{ once: true, margin: '-100px' }}
          />
          <SafeMotionSpan
            className="text-[9px] uppercase tracking-[0.25em]"
            style={{ color: 'var(--t-light-yellow)', fontFamily: FONT.mono }}
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            viewport={{ once: true, margin: '-100px' }}
          >
            A note from Terrazzo
          </SafeMotionSpan>
        </div>
        <SafeMotionH2
          className="text-[20px] leading-snug mb-4"
          style={{ fontFamily: FONT.serif, color: '#ffffff' }}
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.3 }}
          viewport={{ once: true, margin: '-100px' }}
        >
          {l.headline}
        </SafeMotionH2>
        <SafeMotionP
          className="text-[13px] leading-relaxed"
          style={{ color: 'rgba(255,255,255,0.8)', fontFamily: FONT.sans }}
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.4 }}
          viewport={{ once: true, margin: '-100px' }}
        >
          {l.body}
        </SafeMotionP>
      </div>
      <SafeMotionDiv
        className="flex items-center gap-2"
        initial={{ opacity: 0, scale: 0.95 }}
        whileInView={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5, delay: 0.5 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <span className="text-[9px] px-2.5 py-1 rounded-full" style={{ background: 'rgba(235,216,150,0.2)', color: 'var(--t-light-yellow)', fontFamily: FONT.mono }}>
          Sparked by: {l.signalHighlight}
        </span>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

// ── BECAUSE YOU — Signal-to-place insight cards ──
function BecauseYouSection({ cards }: { cards?: BecauseYouCard[] }) {
  const displayCards = cards || BECAUSE_YOU_CARDS;
  return (
    <SafeMotionDiv

      className="mt-4 mb-10 px-5"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <div className="mb-3">
        <SectionLabel color={COLOR.coral}>Because you...</SectionLabel>
      </div>
      <div
        className="flex gap-3 overflow-x-auto pb-2 -mr-5 pr-5"
        style={{ scrollbarWidth: 'none', scrollSnapType: 'x mandatory' }}
      >
        {displayCards.map((card, idx) => {
          const domainColor = DIMENSION_COLORS[card.signalDomain] || '#413800';
          return (
            <PlaceLink key={card.place} name={card.place} location={card.location} googlePlaceId={card.googlePlaceId}>
              <SafeMotionDiv
                className="flex-shrink-0 p-5 rounded-2xl flex flex-col justify-between"
                style={{ background: 'linear-gradient(145deg, rgba(238,113,109,0.06) 0%, rgba(238,113,109,0.12) 100%)', border: `1px solid ${INK['06']}`, width: 280, minHeight: 230, scrollSnapAlign: 'start' }}
                initial={{ opacity: 0, x: -20, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1, x: 0 }}
                transition={{ duration: 0.5, delay: idx * 0.1 }}
                viewport={{ once: true, margin: '-100px' }}
              >
                <div>
                  <div className="flex items-center gap-2 mb-4">
                    <PerriandIcon name="sparkle" size={12} color={COLOR.coral} />
                    <span className="text-[9px] uppercase tracking-wider px-2 py-0.5 rounded-full" style={{ background: `${COLOR.coral}12`, color: COLOR.coral, fontFamily: FONT.mono }}>
                      {card.signalDomain}
                    </span>
                  </div>
                  <p className="text-[12px] leading-relaxed mb-1" style={{ color: COLOR.navy, fontFamily: FONT.sans }}>
                    Because you love
                  </p>
                  <p className="text-[16px] font-semibold mb-4 italic" style={{ color: COLOR.darkTeal, fontFamily: FONT.serif }}>
                    &ldquo;{card.signal}&rdquo;
                  </p>
                </div>
                <div>
                  <div className="flex items-center gap-2.5 mb-2">
                    <ScoreArc score={card.score} size={34} color="var(--t-coral)" />
                    <div>
                      <div className="text-[14px] font-semibold" style={{ color: COLOR.darkTeal }}>{card.place}</div>
                      <div className="text-[11px]" style={{ color: COLOR.navy }}>{card.location}</div>
                    </div>
                  </div>
                  <p className="text-[11px] leading-relaxed" style={{ color: COLOR.navy }}>{card.why}</p>
                </div>
              </SafeMotionDiv>
            </PlaceLink>
          );
        })}
      </div>
    </SafeMotionDiv>
  );
}

// ── SIGNAL THREAD — One signal, many manifestations ──
function SignalThreadSection({ thread }: { thread?: SignalThread }) {
  const t = thread || SIGNAL_THREAD;
  const domainColor = DIMENSION_COLORS[t.domain] || '#413800';
  const TYPE_ICONS: Record<string, string> = { hotel: 'hotel', restaurant: 'restaurant', bar: 'bar', cafe: 'cafe', neighborhood: 'neighborhood' };

  return (
    <SafeMotionDiv
      className="px-5 py-6 mb-10 rounded-2xl"
      style={{ background: 'var(--t-dark-teal)' }}
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel color="var(--t-light-yellow)">The thread</SectionLabel>
      <SafeMotionDiv
        className="mt-3 p-5 rounded-2xl"
        style={{ background: '#ffffff', border: 'none' }}
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.1 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <div className="flex items-center gap-2 mb-3">
          <span className="text-[10px] px-2.5 py-1 rounded-full font-semibold" style={{ background: `${COLOR.ochre}12`, color: COLOR.ochre, fontFamily: FONT.mono }}>
            {t.signal}
          </span>
        </div>
        <p className="text-[13px] leading-relaxed mb-5" style={{ color: COLOR.navy, fontFamily: FONT.sans }}>
          {t.thread}
        </p>
        {/* Vertical thread line connecting places */}
        <div className="flex flex-col gap-0">
          {t.places.map((place, i) => (
            <PlaceLink key={place.name} name={place.name} location={place.location} googlePlaceId={place.googlePlaceId}>
              <SafeMotionDiv
                className="flex gap-3"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.2 + i * 0.1 }}
                viewport={{ once: true, margin: '-100px' }}
              >
                {/* Thread line */}
                <div className="flex flex-col items-center" style={{ width: 20 }}>
                  <SafeMotionDiv
                    className="w-2 h-2 rounded-full flex-shrink-0"
                    style={{ background: domainColor, marginTop: 4 }}
                    initial={{ scale: 0.95 }}
                    whileInView={{ scale: 1 }}
                    transition={{ duration: 0.4, delay: 0.2 + i * 0.1 }}
                    viewport={{ once: true, margin: '-100px' }}
                  />
                  {i < t.places.length - 1 && (
                    <SafeMotionDiv
                      className="w-[1px] flex-1"
                      style={{ background: INK['10'] }}
                      initial={{ scaleY: 0 }}
                      whileInView={{ scaleY: 1 }}
                      transition={{ duration: 0.5, delay: 0.3 + i * 0.1 }}
                      viewport={{ once: true, margin: '-100px' }}
                    />
                  )}
                </div>
                {/* Place card */}
                <div className="flex-1 pb-4">
                  <div className="flex items-center gap-1.5 mb-1">
                    <PerriandIcon name={(TYPE_ICONS[place.type] || 'discover') as import('@/types').PerriandIconName} size={12} color={COLOR.darkTeal} />
                    <span className="text-[9px] uppercase tracking-wider" style={{ color: COLOR.darkTeal, fontFamily: FONT.mono }}>{place.type}</span>
                  </div>
                  <div className="flex items-baseline gap-2 mb-1">
                    <span className="text-[13px] font-semibold" style={{ color: COLOR.ochre }}>{place.name}</span>
                    <span className="text-[10px]" style={{ color: COLOR.navy }}>{place.location}</span>
                    <span className="text-[10px] font-bold ml-auto" style={{ color: COLOR.ochre, fontFamily: FONT.mono }}>{Math.round(place.score)}</span>
                  </div>
                  <p className="text-[11px] leading-relaxed" style={{ color: COLOR.navy }}>{place.connection}</p>
                </div>
              </SafeMotionDiv>
            </PlaceLink>
          ))}
        </div>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

// ── TASTE TENSION — Editorial exploration of a contradiction ──
function TasteTensionSection({ tension }: { tension?: TasteTension }) {
  const t = tension || TASTE_TENSION;
  // Map discover feed TasteTension → intelligence component TasteTension
  const intelTension: IntelTasteTension = {
    title: t.title,
    stated: t.stated,
    revealed: t.revealed,
    editorial: t.editorial,
    resolvedBy: t.resolvedBy,
  };
  return (
    <div className="px-5 mb-10">
      <TasteTensionCard
        tension={intelTension}
        onPlaceTap={undefined}
        variant="mobile"
      />
    </div>
  );
}

// ── THIS WEEK'S EDIT ──
function WeeklyEditSection({ collection: propCollection }: { collection?: { title: string; subtitle: string; places: CollectionPlace[] } }) {
  const collection = propCollection || WEEKLY_COLLECTION;
  return (
    <SafeMotionDiv
      className="px-5 py-6 mb-10 rounded-2xl"
      style={{ background: 'var(--t-dark-teal)' }}
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <div className="mb-1"><SectionLabel color="var(--t-light-yellow)">This week&apos;s edit</SectionLabel></div>
      <div className="mb-3">
        <h3 className="text-[18px] leading-snug mb-1" style={{ fontFamily: FONT.serif, color: '#ffffff' }}>{collection.title}</h3>
        <p className="text-[11px]" style={{ color: 'rgba(255,255,255,0.7)', fontFamily: FONT.mono }}>{collection.subtitle}</p>
      </div>
      <div className="flex gap-3 overflow-x-auto pb-2 -mr-5 pr-5" style={{ scrollbarWidth: 'none', scrollSnapType: 'x mandatory' }}>
        {collection.places.map((place, idx) => {
          const domainColor = DIMENSION_COLORS[place.signalDomain] || '#413800';
          const imageUrl = getPlaceImage(place.name);
          return (
            <PlaceLink key={place.name} name={place.name} location={place.location} googlePlaceId={place.googlePlaceId}>
              <SafeMotionDiv
                className="flex-shrink-0 rounded-xl flex flex-col overflow-hidden"
                style={{ background: 'white', border: '1px solid var(--t-linen)', width: 240, scrollSnapAlign: 'start' }}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: idx * 0.1 }}
                viewport={{ once: true, margin: '-100px' }}
              >
                {imageUrl && (
                  <div style={{ height: 100, overflow: 'hidden', position: 'relative' }}>
                    <PlacePhoto src={imageUrl} alt={place.name} fill sizes="240px" />
                  </div>
                )}
                <div className="p-4 flex flex-col">
                  <div className="flex items-start justify-between mb-2">
                    <div>
                      <div className="text-[14px] font-semibold" style={{ color: COLOR.ochre }}>{place.name}</div>
                      <div className="text-[11px]" style={{ color: COLOR.navy }}>{place.location}</div>
                    </div>
                    <ScoreArc score={place.score} size={38} color={COLOR.ochre} />
                  </div>
                  <div className="flex flex-wrap gap-1 mb-2.5">
                    {(Array.isArray(place.signals) ? place.signals : []).map(s => (
                      <span key={s} className="text-[9px] px-2 py-0.5 rounded-full" style={{ background: `${COLOR.ochre}12`, color: COLOR.ochre, fontFamily: FONT.sans }}>{s}</span>
                    ))}
                  </div>
                  <p className="text-[11px] leading-relaxed" style={{ color: COLOR.navy }}>{place.note}</p>
                </div>
              </SafeMotionDiv>
            </PlaceLink>
          );
        })}
      </div>
    </SafeMotionDiv>
  );
}

// ── MOOD BOARDS — Curated moods ──
function MoodBoardSection({ boards }: { boards?: MoodBoard[] }) {
  const displayBoards = boards || MOOD_BOARDS;
  return (
    <SafeMotionDiv
      className="mb-10 px-5"
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel color={COLOR.coral}>Travel moods</SectionLabel>
      <div className="flex flex-col gap-3 mt-3">
        {displayBoards.map((board, idx) => (
          <SafeMotionDiv
            key={board.mood}
            className="p-4 rounded-2xl"
            style={{ background: 'linear-gradient(145deg, rgba(238,113,109,0.06) 0%, rgba(238,113,109,0.12) 100%)', border: `1px solid ${INK['06']}`, borderLeft: `3px solid ${board.color}` }}
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: idx * 0.1 }}
            viewport={{ once: true, margin: '-100px' }}
          >
            <h4 className="text-[14px] font-semibold mb-1" style={{ fontFamily: FONT.serif, color: COLOR.darkTeal }}>{board.mood}</h4>
            <p className="text-[11px] mb-4" style={{ color: COLOR.navy, fontFamily: FONT.sans }}>{board.description}</p>
            <div className="flex flex-col gap-2">
              {board.places.map((p, pIdx) => {
                const imageUrl = getPlaceImage(p.name);
                return (
                  <PlaceLink key={p.name} name={p.name} location={p.location} googlePlaceId={p.googlePlaceId}>
                    <SafeMotionDiv
                      className="flex items-center gap-3"
                      initial={{ opacity: 0, y: 20 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.4, delay: idx * 0.1 + pIdx * 0.05 }}
                      viewport={{ once: true, margin: '-100px' }}
                    >
                      {imageUrl ? (
                        <div style={{ width: 40, height: 40, borderRadius: 10, overflow: 'hidden', flexShrink: 0, position: 'relative' }}>
                          <PlacePhoto src={imageUrl} alt={p.name} fill sizes="40px" />
                        </div>
                      ) : (
                        <ScoreArc score={p.score} size={40} color={board.color} />
                      )}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-baseline gap-1.5">
                          <span className="text-[12px] font-semibold" style={{ color: COLOR.darkTeal }}>{p.name}</span>
                          <span className="text-[10px]" style={{ color: COLOR.navy }}>{p.location}</span>
                        </div>
                        <p className="text-[10px] italic" style={{ color: COLOR.navy }}>{p.vibe}</p>
                      </div>
                      <span className="text-[10px] font-bold flex-shrink-0" style={{ color: board.color, fontFamily: FONT.mono }}>{Math.round(p.score)}</span>
                    </SafeMotionDiv>
                  </PlaceLink>
                );
              })}
            </div>
          </SafeMotionDiv>
        ))}
      </div>
    </SafeMotionDiv>
  );
}

// ── DEEP MATCH — Signal-by-signal breakdown ──
function DeepMatchSection({ match }: { match?: DeepMatch }) {
  const m = match || DEEP_MATCH;
  // Map discover feed DeepMatch → intelligence component DeepMatch
  const intelMatch: IntelDeepMatch = {
    name: m.name,
    location: m.location,
    score: m.score,
    headline: m.headline,
    signalBreakdown: m.signalBreakdown.map(s => ({
      signal: s.signal,
      domain: s.domain as TasteDomain,
      strength: s.strength,
      note: s.note,
    })),
    tensionResolved: m.tensionResolved,
    googlePlaceId: m.googlePlaceId,
  };
  return (
    <SafeMotionDiv
      className="px-5 py-6 mb-10 rounded-2xl"
      style={{ background: 'var(--t-dark-teal)' }}
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <div className="mb-3"><SectionLabel color="var(--t-light-yellow)">Deep match</SectionLabel></div>
      <div className="rounded-xl overflow-hidden" style={{ background: '#ffffff' }}>
        <DeepMatchBreakdown
          match={intelMatch}
          onPlaceTap={undefined}
          variant="mobile"
        />
      </div>
    </SafeMotionDiv>
  );
}

// ── STRETCH PICK ──
function StretchPickSection({ stretch }: { stretch?: typeof STRETCH_PICK }) {
  const s = stretch || STRETCH_PICK;
  // Map discover feed stretch pick → intelligence component StretchPick
  const intelStretch: IntelStretchPick = {
    name: s.name,
    location: s.location,
    score: s.score,
    type: s.type,
    strongAxis: s.strongAxis as TasteDomain,
    strongScore: s.strongScore,
    weakAxis: s.weakAxis as TasteDomain,
    weakScore: s.weakScore,
    why: s.why,
    tension: s.tension,
    googlePlaceId: s.googlePlaceId,
  };
  return (
    <div className="px-5 mb-10">
      <StretchPickAxis
        pick={intelStretch}
        onPlaceTap={undefined}
        variant="mobile"
      />
    </div>
  );
}

// ── CONTEXT MODE ──
function ContextModeSection({ recs, contextLabel }: { recs?: ContextRec[]; contextLabel?: string }) {
  const displayRecs = recs || SUMMER_RECS;
  const label = contextLabel || 'Summer';
  return (
    <SafeMotionDiv
      className="px-5 py-6 mb-10 rounded-2xl"
      style={{ background: 'var(--t-dark-teal)' }}
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel color="var(--t-light-yellow)">Context mode</SectionLabel>
      <SafeMotionDiv
        className="p-4 rounded-xl mt-3"
        style={{ background: '#ffffff', border: 'none', borderTop: '3px solid var(--t-light-yellow)' }}
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.1 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <div className="flex items-center gap-2 mb-1">
          <PerriandIcon name="summer" size={16} color="var(--t-ink)" />
          <span className="text-[14px] font-semibold" style={{ fontFamily: FONT.serif, color: COLOR.ochre }}>
            If you&apos;re traveling this {label.toLowerCase()}...
          </span>
        </div>
        <p className="text-[11px] mb-4" style={{ color: COLOR.navy, fontFamily: FONT.mono }}>
          {displayRecs.length > 0
            ? displayRecs.slice(0, 3).map(r => r.name).join(' · ')
            : 'Curated for your moment'}
        </p>
        <div className="flex flex-col gap-2.5">
          {displayRecs.map((rec, idx) => {
            const imageUrl = getPlaceImage(rec.name);
            return (
              <PlaceLink key={rec.name} name={rec.name} location={rec.location} googlePlaceId={rec.googlePlaceId}>
                <SafeMotionDiv
                  className="flex items-center gap-3"
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: 0.15 + idx * 0.05 }}
                  viewport={{ once: true, margin: '-100px' }}
                >
                  {imageUrl ? (
                    <div style={{ width: 36, height: 36, borderRadius: 10, overflow: 'hidden', flexShrink: 0, position: 'relative' }}>
                      <PlacePhoto src={imageUrl} alt={rec.name} fill sizes="36px" />
                    </div>
                  ) : (
                    <ScoreArc score={rec.score} size={36} color={COLOR.ochre} />
                  )}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-baseline gap-1.5">
                      <span className="text-[12px] font-semibold" style={{ color: COLOR.ochre }}>{rec.name}</span>
                      <span className="text-[10px]" style={{ color: COLOR.navy }}>{rec.location}</span>
                    </div>
                    <p className="text-[10px] leading-snug" style={{ color: COLOR.navy }}>{rec.whyFits}</p>
                  </div>
                </SafeMotionDiv>
              </PlaceLink>
            );
          })}
        </div>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

// ── VOCAB TEASER ──
function VocabTeaser({ profile }: { profile: typeof TASTE_PROFILE }) {
  const domains = Object.entries(profile.microTasteSignals).slice(0, 4);
  const allTerms: Array<{ term: string; domain: string }> = [];
  domains.forEach(([domain, terms]) => { terms.slice(0, 2).forEach(term => allTerms.push({ term, domain })); });
  const rejections = profile.microTasteSignals['Rejection']?.slice(0, 2) || [];
  rejections.forEach(term => allTerms.push({ term, domain: 'Rejection' }));

  return (
    <SafeMotionDiv
      className="px-5 py-6 mb-10 rounded-2xl"
      style={{ background: 'var(--t-dark-teal)' }}
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
      viewport={{ once: true, margin: '-100px' }}
    >
      <SectionLabel color="var(--t-light-yellow)">Your taste vocabulary</SectionLabel>
      <SafeMotionDiv
        className="p-4 rounded-xl mt-3"
        style={{ background: '#ffffff', border: 'none' }}
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.1 }}
        viewport={{ once: true, margin: '-100px' }}
      >
        <div className="flex flex-wrap gap-1.5 mb-3">
          {allTerms.map(({ term, domain }, idx) => {
            const color = DIMENSION_COLORS[domain] || '#413800';
            const isRejection = domain === 'Rejection';
            const randomDelay = Math.random() * 0.3;
            return (
              <SafeMotionSpan
                key={term}
                className="text-[10px] px-2.5 py-1 rounded-full"
                style={{ background: isRejection ? 'rgba(200,100,100,0.08)' : `${color}12`, color: isRejection ? 'rgba(200,100,100,0.8)' : color, fontFamily: FONT.sans }}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.4, delay: randomDelay }}
                viewport={{ once: true, margin: '-100px' }}
              >
                {term}
              </SafeMotionSpan>
            );
          })}
          <SafeMotionSpan
            className="text-[10px] px-2.5 py-1 rounded-full"
            style={{ background: INK['04'], color: TEXT.secondary }}
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.4, delay: 0.3 }}
            viewport={{ once: true, margin: '-100px' }}
          >
            +{Object.values(profile.microTasteSignals).flat().length - allTerms.length} more
          </SafeMotionSpan>
        </div>
      </SafeMotionDiv>
    </SafeMotionDiv>
  );
}

